### ISSUE TITLE
can't create-release from existing dev-release .yml

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#10]
Did this in the bosh-repo after creating a new dev release with `bundle exec rake release:create_dev_release`
```
$ bosh create-release /Users/<user>/workspace/bosh/release/dev_releases/bosh/bosh-257.9+dev.3.yml --tarball
Internal inconsistency: version 'b26048fd1490b32e64a74c8014df6cfa27300d68' vs '3'

Exit code 1
```

**Comment by cppforlife** [comment]
yeah. currently we raise an error explicitly since we dont expect to see numeric versions (fairly old). planning to remove this error.

**Comment by cppforlife** [comment]
Fixed recently.

**Comment by dpb587-pivotal** [comment]
For those who like details... https://github.com/cloudfoundry/bosh-cli/commit/57771c2fb964071c816587d4885498770b5ec52d

**Comment by voelzmo** [comment]
Thanks for the details, @dpb587-pivotal :)
