### ISSUE TITLE
Incorrectly calling a command (e.g. with missing required parameters) should show help text

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh-cli#103]
If I call a command incorrectly, such as `bosh deploy` with no manifest, the CLI exits 1 with a fairly informative error message, but I'd prefer if it also spit out the help text that you'd get with `bosh deploy --help`.

**Comment by dpb587** [comment]
I think it's a subjective topic, but I disagree. I think the invocation error should be as concisely helpful as possible. I don't want to see a full dump of everything I might possibly find helpful about the command if I typo an option or forget an argument. I find it frustrating when commands do that and I need to scroll back through a bunch of things I really don't care about only to realize it didn't recognize my typo'd option. If I'm interested in full help information or to generally learn, I should be using `--help`.

**Comment by cppforlife** [comment]
agree with @dpb587, though we will descriptions of arguments
