### ISSUE TITLE
Changing Cert Parameters Should Invalidate Generated Values in the `vars-store`

### ISSUE THREAD

**Issue by JesseTAlford** [cloudfoundry/bosh-cli#106]
`cf-deployment` was using a separate CA for each component. We discovered, when adding mutual TLS to CAPI jobs, that the CA needed to match with the one used by Diego jobs.
 Changing the `ca` option of the certs used on the Diego jobs did not result in those certs being regenerated upon performing a deploy to an existing environment. Since the values didn't change, the jobs weren't updated. In order to get the values regenerated and in-place on the jobs, we had to delete them manually from the vars-store and deploy again.

 It would be very useful if BOSH were smart enough to realize that the options changed and that this meant it was necessary to regenerate the value. One reason this is important is that `cf-deployment` might wish to make changes to variable options without imposing (and documenting, and coordinating, etc.) manual work on users.

**Comment by cppforlife** [comment]
@JesseTAlford that's planned for config server configuration, but not cli since --vars-store + bosh deploy is more of a temporary feature.

**Comment by JesseTAlford** [comment]
Cool, it sounds like config server will address our concerns, here. Closing.
