### ISSUE TITLE
sync-blobs should clear out unused blobs

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/bosh-cli#109]
If a blob exists in the `blobs` folder that is not referenced in `blobs.yml` it should be removed when `sync-blobs` is run.

If you don't do this, packages that pull in artifacts using globs can accidentally include files they should not have.

**Comment by cppforlife** [comment]
@jpalermo Got this: https://www.pivotaltracker.com/story/show/138579069

**Comment by tjvman** [comment]
Closing - the linked story has been accepted and the behavior is present in recent CLI versions (>=2.0.1). If you're still seeing problems, feel free to open a new issue.
