### ISSUE TITLE
incorrect deployment manifest should give `no such file` instead of `the required argument `PATH` was not provided`

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh-cli#11]
When bosh CLI is passed a deployment manifest that is either non-existent or unreadable, it returns a misleading
```
the required argument `PATH` was not provided
```
message; instead, it should return either `filename: No such file or directory` or `filename: Permission denied`.

```bash
# non-existent
bosh --version
version 0.0.59-35caccf-2016-09-08T21:29:07Z
bosh deploy -d nginx-ntp-pdns no-such-file-or-directory
the required argument `PATH` was not provided

Exit code 1
# unreadable
bosh deploy -d nginx-ntp-pdns /etc/ssh/ssh_host_key
the required argument `PATH` was not provided

Exit code 1
```

**Comment by cppforlife** [comment]
Need to bump go-flags to include: https://github.com/jessevdk/go-flags/issues/188

**Comment by cppforlife** [comment]
Fixed in https://github.com/cloudfoundry/bosh-cli/commit/5742c6cb07eebaeed338836f8eee972769ddad7f.

**Comment by dpb587-pivotal** [comment]
Nice!

**Comment by viviliv** [comment]
Same with bosh2.

bosh2 --version
version 2.0.23-a5bb0df-2017-05-31T21:21:01Z

bosh2 -e kubosh -d pcf/rbc-manifests/logsearch/logsearch-dev.yml deploy
the required argument `PATH` was not provided
