### ISSUE TITLE
How to get debug log for `bosh create-env`

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-cli#113]
For bosh-init, we can set `BOSH_INIT_LOG_LEVEL=debug` environment variable  to get full debug log.
How to get full debug log for `bosh create-env` using boshcli v2?

**Comment by dpb587-pivotal** [comment]
The environment variable was renamed to [`BOSH_LOG_LEVEL`](https://github.com/cloudfoundry/bosh-cli/blob/47ea06453290186de2610150498d3901d16c4131/main.go#L46).

    BOSH_LOG_LEVEL=debug bosh create-env ...
