### ISSUE TITLE
bosh2 ssh fails where bosh1 ssh works (using gateway)

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#119]
Am I using `bosh2 ssh` correctly?

Version:

```
$ bosh2 -v
version 0.0.155-bad46e9-2017-02-01T06:59:24Z
```

Failing command:

```
$ bosh2 -e lite46 -d cf ssh brain/xxx --gw-user vcap --gw-host 10.58.111.46 --gw-private-key path/to/sshkeys/bosh-lites.pem
Using environment 'https://10.58.111.46:25555' as client 'admin'

Using deployment 'cf'

Task 22. Done
Warning: Permanently added '10.58.111.46' (ECDSA) to the list of known hosts.
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
Permission denied (publickey,password).
ssh_exchange_identification: Connection closed by remote host

Running SSH:
  1 error(s) occurred:

* Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/Users/drnic/.bosh/tmp/ssh-priv-key217728386 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/drnic/.bosh/tmp/ssh-known-hosts928741625 -o ProxyCommand=ssh -tt -W %!h(MISSING):%!p(MISSING) -l vcap 10.58.111.46 -o ServerAliveInterval=30 -o ForwardAgent=no -o ClearAllForwardings=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/Users/drnic/Projects/bosh_deployments/bosh-lites/sshkeys/bosh-lites.pem 10.244.0.106 -l bosh_4f38b31b526b4090', stdout: '', stderr: '': exit status 255

Exit code 1
```

The `-W %!h(MISSING):%!p(MISSING)` looks suspicious.

The same attributes (I think) passed to bosh1 work:

```
bosh -t vsphere-lite-46 -d cf-46-dpg-integration-test.yml ssh --gateway_host 10.58.111.46 --gateway_user vcap --gateway_identity_file path/to/sshkeys/bosh-lites.pem
```

Am I using bosh2 incorrectly?

**Comment by cppforlife** [comment]
does regular ssh to gw work with those params? according to that call it doesnt auth successfully.

**Comment by drnic** [comment]
@cppforlife yeah the `bosh ssh` command works as typed above (except `path/to` replaced by absolute path).

**Comment by cppforlife** [comment]
can you run
```
$ ssh vcap@10.58.111.46 -i path/to/sshkeys/bosh-lites.pem
```

**Comment by drnic** [comment]
```
$ ssh vcap@10.58.111.46 -i path/to/sshkeys/bosh-lites.pem
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
vcap@10.58.111.46's password:
```

**Comment by drnic** [comment]
In the error above it included:

```
-o ProxyCommand=ssh -tt -W %!h(MISSING):%!p(MISSING) -l vcap 10.58.111.46
```

In the code base I see:

```golang
		proxyOpt := fmt.Sprintf(
			// Always force TTY for gateway ssh
			"ProxyCommand=ssh -tt -W %%h:%%p -l %s %s %s",
			gwUsername,
			gwHost,
			strings.Join(gwCmdOpts, " "),
		)
```

Why might the `%%h` convert to `%!h(MISSING)` rather than `%h` (as per the session_test.go)

**Comment by drnic** [comment]
I'll investigate the private key - as you suspect, and I've blindly ignored - its not matching to the private key provided:

```
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: path/to/sshkeys/bosh-lites.pem
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
```

**Comment by drnic** [comment]
Ok, removing the `--gw-private-key path/to/badkey.pem` and it no longer fails. I guess `bosh ssh` used to politefully ignore the bad key and move on to `password`.

```
bosh2 -e lite46 -d cf ssh uaa --gw-user vcap --gw-host 10.58.111.46 --opts=-v
```

Yay for `--opts=-v`

**Comment by drnic** [comment]
Ahh, the crazy `%!h(MISSING)` is in the output even I cleanly exit from the above ssh session:

```
==[]=[ 01:18:19 ]=[ cf uaa/0 ]=[ ~ ]=[]==
$ debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
logout
debug1: channel 0: free: client-session, nchannels 1
Connection to 10.244.0.101 closed.
Transferred: sent 3572, received 3092 bytes, in 78.8 seconds
Bytes per second: sent 45.4, received 39.3
debug1: Exit status 130
Killed by signal 1.

Running SSH:
  1 error(s) occurred:

* Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/Users/drnic/.bosh/tmp/ssh-priv-key670816920 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/drnic/.bosh/tmp/ssh-known-hosts129922327 -o ProxyCommand=ssh -tt -W %!h(MISSING):%!p(MISSING) -l vcap 10.58.111.46 -o ServerAliveInterval=30 -o ForwardAgent=no -o ClearAllForwardings=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v 10.244.0.101 -l bosh_f647ddb89498452b', stdout: '', stderr: '': exit status 130

Exit code 1
```

Not sure why a) the `bosh2 ssh` ends with an exit code 1 and error output; nor b) we see the `-W %!h(MISSING):%!p(MISSING)` in it.

**Comment by drnic** [comment]
If (as I did at the top of the ticket) provide a bad `--gw-private-key`, then `ssh` does not revert to `password` authentication, it just drops out:


Same command above, with `--gw-private-key path/to/bad/key.pem`:

```
bosh2 -e lite46 -d cf ssh uaa --gw-user vcap --gw-host 10.58.111.46 --opts=-v --gw-private-key ../../bosh-lites/sshkeys/bosh-lites.pem
Using environment 'https://10.58.111.46:25555' as client 'admin'

Using deployment 'cf'

Task 50. Done
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Executing proxy command: exec ssh -tt -W 10.244.0.101:22 -l vcap 10.58.111.46 -o ServerAliveInterval=30 -o ForwardAgent=no -o ClearAllForwardings=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=../../bosh-lites/sshkeys/bosh-lites.pem
debug1: key_load_public: No such file or directory
debug1: identity file /Users/drnic/.bosh/tmp/ssh-priv-key934304133 type -1
debug1: permanently_drop_suid: 501
debug1: key_load_public: No such file or directory
debug1: identity file /Users/drnic/.bosh/tmp/ssh-priv-key934304133-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
Warning: Permanently added '10.58.111.46' (ECDSA) to the list of known hosts.
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
Permission denied (publickey,password).
ssh_exchange_identification: Connection closed by remote host
```

**Comment by drnic** [comment]
@cppforlife is there a way to install public keys into `~vcap/.ssh/authorized_keys` into a bosh deployment's VMs? I know we can configure the `vcap` password; not sure if there's a way to setup public keys.

**Comment by cppforlife** [comment]
according to bash exit codes, 130 means script terminated with ctrl+c (http://www.tldp.org/LDP/abs/html/exitcodes.html). bosh cli just propagates the exit code. related issue: https://github.com/cloudfoundry/bosh-cli/issues/41

re: `-W %!h(MISSING):%!p(MISSING)`: this is just poor formatting. we should clean up the error message.

**Comment by cppforlife** [comment]
> is there a way to install public keys into ~vcap/.ssh/authorized_keys into a bosh deployment's VMs?
you shouldn't have to set up ssh keys for your deployed vms, since bosh ssh generates ephemeral keys (except for the gw/jumpbox machine). it seems that in your case you just need to provide correct ssh key for your gw machine. are you using your director as your gateway? which iaas are you using?

**Comment by drnic** [comment]
This is for the conversation above - am deploying bosh-lite via bosh; then using it as gateway into its deployment garden containers. So rather than using vcap & password (which comes from deployment manifest), we would use vcap & private key if the public key was installed into vcap/.ssh/authorized_keys






On Fri, Feb 10, 2017 at 3:26 PM +1000, "Dmitriy Kalinin" <notifications@github.com> wrote:













is there a way to install public keys into ~vcap/.ssh/authorized_keys into a bosh deployment's VMs?

you shouldn't have to set up ssh keys for your deployed vms, since bosh ssh generates ephemeral keys (except for the gw/jumpbox machine). it seems that in your case you just need to provide correct ssh key for your gw machine. are you using your director as your gateway? which iaas are you using?

**Comment by cppforlife** [comment]
@drnic i see, you can:
- use your main director as a jumpbox (or any other machine)
- or, os-conf's user_add job (https://github.com/cloudfoundry/os-conf-release/blob/master/jobs/user_add/spec) to add a diff user you want (dont use vcap as it will be cleared out)

**Comment by drnic** [comment]
@cppforlife to confirm - I can use any other machine as a gateway to access the garden containers inside another machine? Or for access bosh-lite instances, I'll need to use the bosh-lite itself as the gateway?

Thanks for link to https://github.com/cloudfoundry/os-conf-release/blob/master/jobs/user_add/spec

**Comment by cppforlife** [comment]
oops, that's my bad, forgot you have containers. yeah you'll have to use machine holding those containers as gw or any other machine that can route to those containers (though unlikely you've set up routes to route from other machines).

**Comment by dpb587-pivotal** [comment]
Closing - sounds like this is resolved.
