### ISSUE TITLE
What's the bosh cli v2 command that equals to ``bosh create user`` in v1?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-cli#120]
How to create bosh user in bosh cli v2? 
In v1, we can use ``bosh create user admin password`` to create new user or change password of existing user.
What's the bosh cli v2 command that equals to ``bosh create user`` in v1?

**Comment by cppforlife** [comment]
@gu-bin we recommend to use either pre-configured users or UAA integration: http://bosh.io/docs/director-users.html#preconfigured. UAA integration is what gives ability for operators to add users and other authz checks. i would recommend using bosh-deployment repo to enable uaa: https://github.com/cloudfoundry/bosh-deployment/blob/master/test.sh#L38
