### ISSUE TITLE
What is the v2 equivalent of 'bosh download manifest <deployment>'?

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#123]

**Comment by dpb587** [comment]
$ bosh --help | grep download 
      manifest               Download deployment manifest locally (aliases: m, man, download-manifest)

    $ bosh -d <deployment> manifest

**Comment by cppforlife** [comment]
@shalako most of the commands are named the same but they have a - instead of a space.

**Comment by shalako** [comment]
This doesn't download the manifest, it prints it to standard out. Sure, I can pipe it to a file. I recommend an update to the help file description.
