### ISSUE TITLE
Could we support spaces between flags and values eg `-r 10`?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#124]
```
$ bosh2 -e lite45 tasks -r 10
Command '*cmd.TasksOpts' does not support extra arguments: 10

Exit code 1
$ bosh2 -e lite45 tasks -r10
Using environment 'https://10.58.111.45:25555' as client 'admin'
```

The former seems a valid common use case of flags with values.

**Comment by cppforlife** [comment]
@drnic this is how go-flags deals with default params since it's ambiguous whether value is a flag value or a different param. most of the flags work properly with spaces since they dont have defaults.

**Comment by mfine30** [comment]
@drnic I agree this is something that is a bit frustrating and confusing. In reality, I don't think it is something that we are likely to address in the short term. If you'd like to continue the conversation, feel free to re-open the issue though.
