### ISSUE TITLE
Please provide permalink for latest stable and edge builds

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#125]
I don't ever want to go to a website to download a new version of the binary. 

I would like to use a script of my own that downloads from a permalink ([cf cli permalinks](https://github.com/cloudfoundry/cli#installers-and-compressed-binaries)) or homebrew ([cf cli homebrew instructions](https://github.com/cloudfoundry/cli#installing-using-a-package-manager)).

Thanks!

**Comment by cppforlife** [comment]
@shalako cloudfoundry/homebrew-tap is automatically updated: https://github.com/cloudfoundry/homebrew-tap/blob/master/bosh-cli.rb

**Comment by shalako** [comment]
Great news, thank you! I don't know how anyone would have known that so I've provided a PR to document it. I also recommend updating docs at https://bosh.io/docs/cli-v2.html

**Comment by cppforlife** [comment]
PR pulled in. Better docs installation section is upcoming as I write up GA CLI docs.
