### ISSUE TITLE
allow me to target a director and remember it for me, across multiple shells

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#126]
I don't want to type `-e DIRECTOR_ALIAS` with every command. 
I don't want to set an environment variable in every shell.
When I change my target, I don't want to change an env var in every shell.

I can imagine some value in using the env vars to target different directors in different shells, but this is rare.

**Comment by tjvman** [comment]
@shalako Am I correct in reading this as a request to introduce `bosh target` or equivalent to the new CLI? AFAIK, the ability to have stateful env/deployment with `bosh target` was intentionally removed for the sake of greater explicitness in the new CLI, so I'm not sure there's much we can do to fix this in the way you're asking for.

**Comment by shalako** [comment]
The greater explicitness is what is causing all my pain. Maybe these options are helpful for scripting, and maybe even for human use in some cases, but it shouldn't be required. 

Yes, a `target` command would be great, though I imagine the `alias-env` command could be extended for this purpose (or `alias-deployment`). Allow me to save my environment and my gw ssh key; even my deployment if I've provided one (though lately I've found that being explicit about the deployment has been helpful).

Asking around, I'm finding users are creating their own aliases, not only for each environment but for each permutation of environment and command; a `bosh-env1` alias for all commands but ssh (includes `-e`), and a `bosh-env1-ssh` alias for the ssh command that includes the `--gw-key` option. I had to do this with the v1 CLI, there was even the bosh-ssh wrapper project to get around this problem. Surely we can learn from those workarounds.

**Comment by tjvman** [comment]
Allowing `alias-env` to store off gateway credentials makes sense to me, especially since it already can store the ca cert. 

@cppforlife Thoughts regarding stateful env?

**Comment by jraqula** [comment]
Personally I am very glad that the v2 CLi does not have this built-in as it forces me to actively select a director and deployment for every mutation. Saved state in v1 cli is extremely vulnerable to destructive user error.

That being said, you type the same flags many many times in some cases. It's nice to have such a "macro" for that. One way I like to do this is to save a separate file, like `production.env`, with content like
```
-e my-env -d my-deployment <other-flags>
```
and do
```
bosh `cat production.env` whatever
```
which allows me to save the configuration (and do tab-completion!) while still demanding an active choice about what to mutate. I'd be interested in maybe a flag to naturalize this process, like a flag that takes a filename to interpolate configuration from. This is similar to the making of aliases as you say @shalako but doesn't need to be shell/environment-variable integrated. What do you think of that approach?

**Comment by shalako** [comment]
@jraqula I recognize the potential for user error when working with multiple environments. I believe this is what a target or built-in alias is for. If I had to specify `-e foo` everytime it would be ok, as long that target could define the environment, deployment, and key. I'd probably still wrap that in an environment-specific alias.

An enhancement would be a boolean I can flip in ~/.bosh.cfg that would remember the last specified alias; equivalent to setting a target without adding a command for it. 

After banging on this today, here's my current workflow:

.bash_profile
```
alias goshs="gosh -e superman -d cf"
```

add key to keychain
```
echo "$(bbl ssh-key)" | ssh-add -
```

Now I have a command I don't mind running over and over:
```
goshs ssh tcp-emitter/0
```

IMO, the private key should be easier to consume, and the BOSH CLI should wrap all this up for me into a tidy target. Example:
```
gosh alias-env superman -e bosh.superman.cf-app.com -d cf --gw-private-key ~/workspace/deployments/superman/key.pem

gosh -e superman ssh tcp-emitter/0
```

**Comment by dpb587** [comment]
I use `.envrc` with [direnv](https://direnv.net) files for the purpose of separate environments and deployments. Each environment has a directory and when I `cd` between them it reloads the `BOSH_ENVIRONMENT`, `BOSH_DEPLOYMENT`, `BOSH_GW_*` and whatever other values I may want.

I'd recommend trying the `.envrc` approach as a solution to at least a couple concerns you have mentioned.

**Comment by shalako** [comment]
Thanks for the suggestion, @dpb587. I'd prefer not to have to think about what directory I'm in.  I'd love it if the CLI remembered all this for me.

**Comment by dpb587-pivotal** [comment]
Closing - bosh cli isn't planning on resurrecting shared state of which target is being used. Feel free to use the environment variables documented in `--help` if you want to avoid typing `-e`.
