### ISSUE TITLE
allow me to ssh into an instance of a job; I don't care which

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#127]
```
$ gosh -e superman -d cf vms
...
route-emitter/f54bc315-f65f-421f-9f55-eef20a2f18fa  running        z2  10.0.32.10   vm-513f1e6b-2ed5-41a7-403a-bbe295881de5  m3.medium
route-emitter/ff49264e-c02c-47f4-ab15-584f370cf18d  running        z1  10.0.16.10   vm-3f036778-3d44-46ba-47e6-333e7c13a7d4  m3.medium

$ gosh -e superman -d cf ssh tcp-emitter
Using environment 'https://35.184.49.153:25555' as client 'user-JuebXTq'

Using deployment 'cf'

Task 69. Done

Running SSH:
  Interactive SSH only works for a single host at a time

Exit code 1
```

I don't know what this error message means.
If there is more than one instance, ask me to type an integer to pick (interactive) or pick one for me (least friction).

**Comment by cppforlife** [comment]
@shalako do you think a flag (`--any`) or may be `route-emitter/any` notation is acceptable.

**Comment by shalako** [comment]
Thank for the consideration. 

How about just pick one for me when an instance guid isn't provided?

**Comment by cppforlife** [comment]
@shalako bosh ssh allows multi-host ssh in v2 so it would be somewhat ambiguous. for example:

```
$ bosh ssh route-emitter -r -c 'sudo lsof -i|grep LISTEN'
```

shows you all listening ports for all instances in route-emitter group.
