### ISSUE TITLE
Allow me to avoid typing `--gw-private-key=<(bbl ssh-key>`

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#129]
Having to navigate to the same dir as `bbl-state.json` and type `--gw-private-key=<(bbl ssh-key>` every time I want to ssh into a vm is severely limiting.

Requiring use of environment variables is not acceptable for human use as they are scoped to one shell. 

I would like to add the key to my ssh keychain or save it in a config file.

**Comment by Amit-PivotalLabs** [comment]
In the [#bbl-users](https://cloudfoundry.slack.com/messages/bbl-users/) Slack channel, @jvshahid suggested:
> i usually just add it to the ssh agent, e.g. `ssh-add <(bbl ssh-key)`. be aware that the ssh agent on the bosh vms is configured to only accept 3 key attempts.

You may also be able to avoid navigating to the `bbl-state.json` directory by doing:
```
--gw-private-key=<(bbl --state-dir=/path/to/bbl-state-json-directory ssh-key)
```

If you use an absolute `/path/to/bbl-state-json-directory` then you'll have the command in your bash history so it will work from any `$PWD`.  You could also add aliases to your workstation for various bbl environments you typically target.

**Comment by shalako** [comment]
Thanks. I tried that before opening this issue but have had permissions issues I'm working through. 

```
$ ssh-add <(bbl ssh-key)
...
Permissions 0660 for '/dev/fd/63' are too open.

$ chmod 600 /dev/fd/63
chmod: /dev/fd/63: Bad file descriptor

```

**Comment by shalako** [comment]
Routing team found that this works

`echo "$(bbl ssh-key)" | ssh-add -`

This topic is becoming similar to #126

**Comment by ljfranklin** [comment]
Updating `BOSH_GW_PRIVATE_KEY` to take either the contents of the private key or a path to it would be ideal for our workflow.

Our team uses direnv to target a given environment when we `cd` into that env's config directory. The `.envrc` exports values that we pulled out of `bbl`: e.g. `export BOSH_CA_CERT=$(bbl director-ca-cert)`. This work nicely for everything except the private key as `BOSH_GW_PRIVATE_KEY` only takes a path to a file, while `BOSH_CA_CERT` takes either the contents or a path.

**Comment by evanfarrar** [comment]
Now that BBL 5.0 uses BOSH_ALL_PROXY and manages a tunnel such that all of the gateway pre-requisites are set I would say this is no longer an issue with the integration between BOSH cli and BBL.
