### ISSUE TITLE
It would be nice if the global help were grouped by noun (release, stemcell, etc.)

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh-cli#131]
I would like to be able to see everything I can do to a release, followed by everything I can do to a stemcell, etc. This makes it easier to parse the help and find what I'm looking for.

e.g.
```
Stemcells:
  stemcells              List stemcells (aliases: ss, stems)
  delete-stemcell        Delete stemcell (aliases: dels)
  upload-stemcell        Upload stemcell (aliases: us)

Releases:
  releases               List releases (aliases: rs, rels)
  create-release         Create release (aliases: cr)
  delete-release         Delete release (aliases: delr)
  export-release         Export the compiled release to a tarball (aliases: expr)
  finalize-release       Create final release from dev release tarball (aliases: finr)
  init-release           Initialize release
  inspect-release        List all jobs, packages, and compiled packages associated with a release (aliases: insr)
  reset-release          Reset release
  upload-release         Upload release (aliases: ur)
```

**Comment by cppforlife** [comment]
that would be very nice. possibly will have to PR to go-flags.

**Comment by mfine30** [comment]
Closing and re-opening to trigger a github story

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
