### ISSUE TITLE
bosh-cli errors when using a system-trusted CA for alias-env command without --ca-cert flag on OS X

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry/bosh-cli#134]
When I add BOSH director's CA to the system trusted certs on mac OS X (e.g. with `sudo security add-trusted-cert` command) , I expect to be able to omit `--ca-cert` flag. However, if I do so, I receive this error:
```
$ bosh2 alias-env my-super-alias -e <BOSH_DIRECTOR_HOSTNAME>
Fetching info:
  Performing request GET 'https://<BOSH_DIRECTOR_HOSTNAME>:25555/info':
    Performing GET request:
      Retry: Get https://<BOSH_DIRECTOR_HOSTNAME>:25555/info: x509: certificate signed by unknown authority
```

We had the same issue with [credhub-cli](https://github.com/pivotal-cf/credhub-cli), and found that we cannot cross-compile our `darwin` binaries on a linux system.

It would be nice if BOSH CLI `darwin` binary were compatible with OS X keychain, so that I don't have to provide a path to a CA that I already trust.

**Comment by cppforlife** [comment]
as per our conversation, i think it's not recommended procedure to modify system certs and it's also costly to maintain os x worker. as of now not planning to support this feature.
