### ISSUE TITLE
Update doublestar to latest version

### ISSUE THREAD

**Issue by Fydon** [cloudfoundry/bosh-cli#139]
dpb587-pivotal contributed [changes for Windows compatibility][1], which aren't in the version in this repository.

[1]: https://github.com/bmatcuk/doublestar/commit/d1c558fae99034adac78490a5b3082b0c9cd35e0

**Comment by monkeyherder** [comment]
Bumped in commit bc4a54fb7607b91432a1f5873003adccca8b19ae
