### ISSUE TITLE
`bosh create-release --final` creates version 0 as default

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#14]
When there is not final version yet, the first version should probably be 1, not 0.

**Comment by cppforlife** [comment]
https://github.com/cloudfoundry/bosh-cli/blob/master/releasedir/fs_release_dir.go#L17

**Comment by voelzmo** [comment]
and you're saying this is by intention or that I should PR it? :P

-----Original Message-----

**Comment by cppforlife** [comment]
currently it's by intention but i would welcome the change.

**Comment by cppforlife** [comment]
Fixed in latest version.
