### ISSUE TITLE
When interpolating an ops-file with a missing path, I'd like to know which ops-file failed

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh-cli#142]
If I use an ops-file like:

```
- type: replace
  path: /my/name=key/does/name=not/exist
  value: "hello"
```

but the path does not resolve, I get a message like:

```
Evaluating manifest:
  Expected to find a map key 'exist' for path '/my/name=key/does/name=not/exist' (found map keys: 'name')

Exit code 1
```

If I have a lot of ops-files, it might be hard for me to find the offender. I'd like to know which ops-file was getting parsed at the time of the error (and even better, which ~~link~~line the operation was defined on)

**Comment by cppforlife** [comment]
which line you mean?

**Comment by wendorf** [comment]
Yep, sorry. Typo.

**Comment by jfmyers9** [comment]
Closing this as it is a duplicate of https://github.com/cloudfoundry/bosh-cli/issues/68
