### ISSUE TITLE
When generating certificates, the  bosh-cli should complain if it encounters a key it does not support

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/bosh-cli#144]
When cf-deployment merged [this pull request](https://github.com/cloudfoundry/cf-deployment/pull/53) the certificate generation options key that previously was named `ext_key_usage` was renamed to `extended_key_usage`.  That worked for people who updated to the newest version of the `bosh-cli`, but for users who were on an older version of the CLI it silently ignored the unrecognized key.  The consequence of that was that they did not discover the problem until they had:
1. Attempted to deploy (unsuccessfully - hung after some time)
2. Investigated the issue at length themselves
3. Opened an issue on `cf-deployment`
4. Asked Release Integration for help debugging
5. Waited for relint to investigate further
6...

All of this time could have been saved if only the `bosh-cli` would have complained when it encountered an unknown `extended_key_usage` option in the certificate generation.  

Please make this feature request a reality!

Thanks,

Josh && @mingxiao

**Comment by cppforlife** [comment]
i think this is already done.
