### ISSUE TITLE
creating dev release using `version: create` fails with poor error when url with release path is not provided

### ISSUE THREAD

**Issue by abbyachau** [cloudfoundry/bosh-cli#146]
If cf-deployment, we tried using `version: create` for the routing release without `url: file:///<path-to-routing-release>`.

Deploy failed with this error:

```
Task 554

01:29:06 | Preparing deployment: Preparing deployment (00:00:00)
            L Error: Release version 'routing/create' doesn't exist

01:29:06 | Error: Release version 'routing/create' doesn't exist

Started  Thu Feb 23 01:29:06 UTC 2017
Finished Thu Feb 23 01:29:06 UTC 2017
Duration 00:00:00

Task 554 error

Updating deployment:
  Expected task '554' to succeed but was state is 'error'

Exit code 1
```

A better error might be `url not found for release name: routing`

**Comment by jfmyers9** [comment]
Closing and reopening to generate a tracker story.

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
