### ISSUE TITLE
/dev/null on Windows

### ISSUE THREAD

**Issue by Fydon** [cloudfoundry/bosh-cli#147]
`os.DevNull` is the platform independant way of using `/dev/null`, but I'm not sure if `/dev/null/foo` will work as expected [here][1] and [here][2] on Windows.

[1]: https://github.com/cloudfoundry/bosh-cli/blob/master/cmd/temp_root_configurator_test.go#L78
[2]: https://github.com/cloudfoundry/bosh-cli/blob/master/cmd/temp_root_configurator_test.go#L97

**Comment by jfmyers9** [comment]
At this point in time, both the bosh-cli and development are not fully supported on Windows. Going to close this issue. Please feel free to create a new issue if you would like to discuss the larger idea of support on Windows.

**Comment by Fydon** [comment]
@jmcarp I've already created a larger detail of Windows support [here][1]. It is actually very close to being possible, but there are hurdles that only someone inside the bosh team can overcome as currently the development is moving in a different direction, away from cross platform support, e.g. bosh releases for Windows working differently to Linux.

To get `create-env` to work it requires finding what is opening Linux files/streams as though the were Windows files/streams. I only see the point at which the receiver, e.g. `bosh-docker-cpi-release` reading one of the certificate passed as a parameter, can't process the data because the new line characters have been read as though they are just a space character.

[1]: https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/cli-v2-windows.md
