### ISSUE TITLE
upload-blobs does nothing

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#152]
```
$ tree blobs
blobs
├── golang
│   └── go1.8.linux-amd64.tar.gz
└── jq
    └── jq-linux64-1.5 -> /Users/drnic/Projects/bosh_releases/etcd-cf-service-broker-boshrelease/.blobs/d8e36831c3c94bb58be34dd544f44a6c6cb88568
```

When I run `upload-blobs` it drops out quickly with `Succeeded` but didn't do anything.

```
$ bosh2 upload-blobs
Succeeded
$ tree blobs
blobs
├── golang
│   └── go1.8.linux-amd64.tar.gz
└── jq
    └── jq-linux64-1.5 -> /Users/drnic/Projects/bosh_releases/etcd-cf-service-broker-boshrelease/.blobs/d8e36831c3c94bb58be34dd544f44a6c6cb88568
```

But `bosh upload blobs` works as expected (well, I'm actually getting a `Aws::S3::MultipartUploadError` error on the 80M golang tarball; which is why I tried `bosh2 upload-blobs`)

**Comment by cppforlife** [comment]
@drnic `bosh upload-blobs` does not work with old style blobs directory that uses symlinks. it expects that all files in there are actual files and not symlinks. you can run `bosh reset-release` (equivalent to `rm -rf blobs`), then add necessary blob files via bosh add-blob and finally run `bosh upload-blobs` (or see `bosh blobs`).

**Comment by drnic** [comment]
To clarify: if I use bosh2 add-blobs then my release is no longer supported by bosh1 release commands?






On Mon, Feb 27, 2017 at 10:33 AM +1000, "Dmitriy Kalinin" <notifications@github.com> wrote:












@drnic bosh upload-blobs does not work with old style blobs directory that uses symlinks. it expects that all files in there are actual files and not symlinks. you can run bosh reset-release (equivalent to rm -rf blobs), then add necessary blob files via bosh add-blob and finally run bosh upload-blobs (or see bosh blobs).

**Comment by cppforlife** [comment]
its supported, you just cant use both clis pointed at the same local release directory.

**Comment by dpb587-pivotal** [comment]
Closing - use `bosh reset-release` when switching between go/ruby cli.

**Comment by dpb587-pivotal** [comment]
Related to #145
