### ISSUE TITLE
Delete stemcell for one CPI only

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh-cli#154]
At the moment when using multi-cpi, `bosh delete-stemcell <name>/<version>` would delete all stemcells in all cpis.

I think it could be useful to allow for a cpi-specific deletion.
`bosh delete-stemcell <name>/<version> --cpi <cpi-name>`

**Comment by cppforlife** [comment]
yeah, i agree, we currently dont expose cpi except in the table though.

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
