### ISSUE TITLE
Remove gofileutils?

### ISSUE THREAD

**Issue by Fydon** [cloudfoundry/bosh-cli#156]
`github.com\cloudfoundry\gofileutils` also appears to perform the same glob function as `github.com\bmatcuk\doublestar`, although it appears to only work with Unix and doesn't appear to be used anywhere in the code.

**Comment by tylerschultz** [comment]
Removed:
https://github.com/cloudfoundry/bosh-utils/commit/6593370c83ab0f0dba0965c2563a44c78b42a104
https://github.com/cloudfoundry/bosh-cli/commit/a1f37f620ab02833ccfcd117bc605d11b0be3b19

I verified github.com/cloudfoundry/gofileutils was not used in github.com/cloudfoundry/bosh-agent, so the removal should be safe.
