### ISSUE TITLE
Overriding is awkward when the value is an array, provided by a vars file

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh-cli#164]
I have a cloud config template, and a vars-file generated by my CI (after terraforming) which creates my reserved IPs.  I'd like to add some additional reserved IPs because I've got some other stuff in my cluster.  Here's a small reproduction of the issue:

```
$ cat template.yml
array: ((var))

$ cat vars.yml
var: [1, 2]

$ cat override.yml
- type: replace
  path: /array/-
  value: 3

$ bosh int -l vars.yml -o override.yml template.yml
Expected to find an array at path '/array/-' but found 'string'

Exit code 1
```

If I apply the `-l` file and output an intermediate result, then I can apply the `-o` file to the intermediate result and get what I want:

```
$ bosh int -l vars.yml template.yml > intermediate.yml

$ bosh int -o override.yml intermediate.yml
array:
- 1
- 2
- 3

Succeeded
```

/cc @wendorf @drich10

**Comment by Amit-PivotalLabs** [comment]
I'll close this old issue of mine.

**Comment by benjaminguttmann-avtq** [comment]
@Amit-PivotalLabs : Did you find a solution on this one? Issue seems still to be present, it seems like arrays added via ((array_variable)) are handled as a string that means you are not able to further add/remove objects ... Did you find any solution beside storing the intermediate result ?

**Comment by dpb587-pivotal** [comment]
Operations files are executed first, then variable interpolation occurs. Ordering of interpolation and ops files is a bit tricky - seems like there's not a single order which can cover all possible use cases.

The only (hacky) workaround that I can think of right now would be to run multiple `bosh int ...` commands to ensure the variables are interpolated first.

**Comment by scottschulthess** [comment]
Yeah it would also be nice to re-open this issue.  If we had a way to pass variables in for multiple array items it would solve some problems.  Spruce/spiff handles this pretty well in contrast
