### ISSUE TITLE
Is there any way to skip ssl validation ?

### ISSUE THREAD

**Issue by kukgini** [cloudfoundry/bosh-cli#168]
Is there any way to skip ssl validation on bosh-cli v2 like bosh cli 1.0 --skip-ssl-validation option ?

**Comment by drnic** [comment]
Some discussion can be found https://github.com/cloudfoundry/bosh-cli/issues/82

**Comment by tylerschultz** [comment]
It is a product decision that skipping ssl validation is no longer a feature.

The go cli has the ability to generate certificates. Have a peek at [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) for examples.

**Comment by mohag** [comment]
If that is the case, it needs a method to override the hostname checked against the certificate, for situations like SSH tunnels...
