### ISSUE TITLE
Is there a bosh cli v2 command that can give the current bosh director url?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-cli#169]
In bosh cli v1, we have `bosh target` command that can output the bosh director url:
```
bosh target
Current target is https://<director_ip>:25555 (bosh)
```

Now in bosh cli v2, I've set `BOSH_ENVIRONMENT` environment variable. Which command can give the current director url like `https://<director_ip>:25555`?

**Comment by voelzmo** [comment]
I think `bosh2 env` is what you are looking for. See http://bosh.io/docs/cli-v2 for a translation of commands.

**Comment by gu-bin** [comment]
@voelzmo `bosh2 env` is for `bosh status`
```
bosh2 env
Using environment 'director-slcpi-eu-gb.softlayer.com' as client 'admin'

Name      bosh
UUID      f09a2fb3-8111-476d-be5a-934587088e6c
Version   1.3262.14.0 (00000000)
CPI       softlayer_cpi
Features  compiled_package_cache: disabled
          dns: enabled
          snapshots: disabled
User      admin

Succeeded
```

**Comment by voelzmo** [comment]
Your URL to the director is right here:
`Using environment 'director-slcpi-eu-gb.softlayer.com' as client 'admin'`

**Comment by gu-bin** [comment]
I meant `https://<director_ip>:25555` including protocol and port. If no commands provides such output, maybe I need to combine myself?

**Comment by drnic** [comment]
The various envs are stored in `~/.bosh/config` YAML file. With `spruce json | jq` you can pull out the data you put in:

```
cat ~/.bosh/config | spruce json | jq -r ".environments[] | select(.alias == \"alias-goes-here\").url"
```

**Comment by tylerschultz** [comment]
Note that the port is [configurable](http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=261.3#p=director.port), so it may not be safe to always assume it's `25555`. If you've alias'd your env, you'd be forced to specify the non-standard port, so that would be in the url. Appending the default port to the url may not always be safe.

**Comment by cppforlife** [comment]
@gu-bin can you elaborate why you need full url?

@drnic ~/.bosh/config is private to the cli. it may change without notice.

**Comment by gu-bin** [comment]
@cppforlife We need to use it as the prefix to call director API, something like `https://<director_ip or hostname>:25555/deployments/talent3-us-south/vms?format=full`

**Comment by cppforlife** [comment]
@gu-bin i would just hard code configuration instead of relying on a private config file. any reason why not use `bosh -e foo vms --json` ?

**Comment by gu-bin** [comment]
@cppforlife We are converting existing automation scripts that rely on bosh cli v1. The existing script  is just API call `https://<director_ip or hostname>:25555/deployments/<deployment_name>/vms?format=full`. We don't want to change it too much to command line like `bosh instances` but just want to get the prefix information `https://<director_ip or hostname>:25555` which was previously gotten from `bosh target` in bosh cli v1.

If I don't specify a non-standard port, is it always `25555` to call director API?

@tylerschultz For your comment `If you've alias'd your env, you'd be forced to specify the non-standard port, so that would be in the url.` Would you explain how to specify a non-standard port?  Thanks.

**Comment by tylerschultz** [comment]
@gu-bin Using the go cli, you would typically run something like `bosh -e 10.0.0.1:26666 --ca-cert /path/cert alias-env bosh-1` where the `26666` is your non standard port. This would store the url containing the port. If you appended `25555` to the url without checking, you'd have an invalid url.

**Comment by tylerschultz** [comment]
@gu-bin Sorry, I misunderstood your question. 

http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=261.4#p=director.port

**Comment by gu-bin** [comment]
@tylerschultz Thanks. So if I don't specify the port in the director yml, it should be the default 25555, correct?

**Comment by dpb587-pivotal** [comment]
Closing - sounds like some suggestions have been given and the automation scripts should change how they refer to the director, possibly by relying on `$BOSH_ENVIRONMENT` and assuming the default port of `25555`. Adding "URL" to `bosh env` does seem reasonable though; if others have scenarios where that field would be useful, please feel free to follow up to discuss it further.

**Comment by neo-liang-sap** [comment]
in bosh v1 the command is ```bosh status --uuid``` after you set your target via ```bosh target https://xxxxxx:25555 xxx```
