### ISSUE TITLE
bosh ssh without specific instance target fails if errands are deployed

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#18]
I'm using `bosh ssh -d <deployment>` without specifying an instance. In the ruby cli, I was getting a list to select from. The golang cli seems to pick the first instance? If the first instance is an errand, ssh just fails. So I guess the cli should either
- pick the first non-errand instance (or the first with `expects_vm: true`, now that the Director sends this)
- fail and require the user to always specify an instance

Wdyt?

```
$ bosh ssh -d dummy
Using environment '<IP>' as user 'admin'

Using deployment 'dummy'

Task 6814

09:04:00 | Error: 'dummy_errand/cdef8f97-f112-4bae-bdbd-ac530d040a95 (0)' doesn't reference a VM
```

```
$ bosh instances -d dummy
Using environment '<IP>' as user 'admin'

Using deployment 'dummy'

Task 6815. Done

Instance                                                         Process State  AZ  IPs
dummy_errand/cdef8f97-f112-4bae-bdbd-ac530d040a95* (0)           -              -   -
dummy_with_package_z1/eeb7e7c2-8cc9-4cc4-b144-9b5331d83e51* (0)  running        -   192.168.0.8

(*) Bootstrap node

2 instances
```

Here's my cli version

```
$ bosh --version
version 0.0.65-47ea064-2016-09-23T22:57:48Z
```

**Comment by dpb587-pivotal** [comment]
Hey, cool, looks like somebody was already thinking ahead about errands and ssh... https://github.com/cloudfoundry/bosh/pull/1467

Fix there is to have director ignore instances which do not currently have a VM, which then leads to current non-errand behavior where the first SSH is picked.

**Comment by cppforlife** [comment]
Director v260+ fixes the problem.
