### ISSUE TITLE
Please provide the ruby script for converting base64 encoded releases to non-base64 encoded

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-cli#181]
@cppforlife Would you please provide the ruby script for converting base64 encoded releases to non-base64 encoded as described in https://github.com/cloudfoundry/bosh-init/issues/105? Thanks.

**Comment by dpb587-pivotal** [comment]
Recent CLI versions (v0.0.133+) support this natively, so you shouldn't need the script to convert your release YAMLs. Feel free to reopen if you run into issues using the older releases with a recent CLI.

**Comment by gu-bin** [comment]
We have a lot of release tgz files that have binary for packages/jobs like this 
```- name: post-deploy
  version: !binary |-
    NmI2MmVmY2Y0NjY3MmRhNTNhNGUxOWIzZjRlMzYwNGFiZDk5YThhNA==
  fingerprint: !binary |-
    NmI2MmVmY2Y0NjY3MmRhNTNhNGUxOWIzZjRlMzYwNGFiZDk5YThhNA==
  sha1: !binary |-
    YzgyODc0ODA3MDk1ODJmYjI1MjVmNDNjMThiNDA3N2JlMWFhZTI1MA==
```

Seems it's not supported now. Is there a way to convert them to non-binary like this
```- name: golang_1.7.1
  version: 63889d018ded88d660b01994d7b00c74ce6fe8d5
  fingerprint: 63889d018ded88d660b01994d7b00c74ce6fe8d5
  sha1: 5a41368cc3a1c57694ba913cd1612aeafad71334
```

**Comment by gu-bin** [comment]
I can't reopen this issue. Please help reopen it. Thanks.

**Comment by maximilien** [comment]
@gu-bin re-opened

**Comment by dpb587-pivotal** [comment]
Can you confirm this was the same issue as #126 and close? If it's a different issue, can you confirm which version of the CLI you're using, and if you have tried using the latest bosh-cli version?

**Comment by gu-bin** [comment]
I think it's the problem that bosh-init doesn't work well with the new stemcell. When change to the boshcli v2, the problem doesn't exit. It's the same issue as https://github.com/cloudfoundry/bosh-agent/issues/126. So closing it.
