### ISSUE TITLE
boshcli v2 upload-stemcell returns error when the stemcell already exists

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-cli#182]
In boshcli v1, we have `--skip-if-exists` option for `upload stemcell` command to skip for existing stemcell and the command is successful (return code is 0).

But in boshcli v2, we don't have `--skip-if-exists` option for `upload-stemcell`. If no option is specified, the command will return error if the stemcell already exists. There is a `--fix` option, but this will replace the stemcell if already exists. We don't want to replace but just want to skip for the existing stemcell. 

Would you please add `--skip-if-exists` option for boshcli v2? Thanks.

**Comment by cppforlife** [comment]
@gu-bin upload-stemcell should work that way out of the box without any special flags:

```
 $ bosh -e dev us /tmp/stemcell
Using environment '10.10.32.7' as client 'admin'

Stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3392+umask.1' already exists.

Succeeded
 $ bosh -e dev us /tmp/stemcell
Using environment '10.10.32.7' as client 'admin'

Stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3392+umask.1' already exists.

Succeeded
 $ echo $?
0
```

**Comment by gu-bin** [comment]
@cppforlife What's the bosh cli version are you using? I'm using version https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.12-linux-amd64 but got the following error when uploading a remote stemcell which already exists:
```
bosh2 upload-stemcell http://<remote_server_ip>/releases/light-bosh-stemcell/3263.10.8/light-bosh-stemcell-3263.10.8-softlayer-xen-ubuntu-trusty-go_agent.tgz
Using environment 'director-slcpi-eu-gb.softlayer.com' as client 'admin'

Task 875

05:07:45 | Update stemcell: Downloading remote stemcell (00:00:00)
05:07:45 | Update stemcell: Extracting stemcell archive (00:00:00)
05:07:45 | Update stemcell: Verifying stemcell manifest (00:00:00)
05:07:45 | Update stemcell: Checking if this stemcell already exists (00:00:00)
            L Error: Stemcell 'bosh-softlayer-xen-ubuntu-trusty-go_agent/3263.10.8' already exists

05:07:45 | Error: Stemcell 'bosh-softlayer-xen-ubuntu-trusty-go_agent/3263.10.8' already exists

Started  Mon Mar 27 05:07:45 UTC 2017
Finished Mon Mar 27 05:07:45 UTC 2017
Duration 00:00:00

Task 875 error

Uploading remote stemcell 'http://10.106.192.96/releases/light-bosh-stemcell/3263.10.8/light-bosh-stemcell-3263.10.8-softlayer-xen-ubuntu-trusty-go_agent.tgz':
  Expected task '875' to succeed but was state is 'error'

Exit code 1
```

There is no problem when upload a local stemcell which already exists:
bosh2 upload-stemcell light-bosh-stemcell-3263.10.8-softlayer-xen-ubuntu-trusty-go_agent.tgz
Using environment 'director-slcpi-eu-gb.softlayer.com' as client 'admin'

Stemcell 'bosh-softlayer-xen-ubuntu-trusty-go_agent/3263.10.8' already exists.

Succeeded
```

**Comment by cppforlife** [comment]
@gu-bin sounds like your director version is a bit behind. i believe we had to make director task idempotent as well to make this work. recommendation is to update the director.

**Comment by gu-bin** [comment]
bosh 261.4 works. Thanks.
