### ISSUE TITLE
Feature Request: Colorized diffs

### ISSUE THREAD

**Issue by luan** [cloudfoundry/bosh-cli#183]
When doing a deploy I'd like to see a colorized version of the diff, like the old CLI had (maybe improved diffing using some fancier diff mechanism, but at the very least green/red instead of +/-).

**Comment by tyyko** [comment]
+1 
It's feels harder for me to compare manifests during deployment without colors

**Comment by jfmyers9** [comment]
Closing and reopening to generate a tracker story.

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
