### ISSUE TITLE
`bosh logs` to get all logs, including log rotated

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/bosh-cli#184]
We recently tried to use `bosh logs` to get logs from production system.

There was so much data that logs had been rotated. The command did not download those logs.

Is it possible to add an option to do so?

**Comment by cppforlife** [comment]
@jtarchie i believe there is `--only` that takes a filter. you should be able to specify '*/*' to include non *.log files.

**Comment by dpb587-pivotal** [comment]
Closing - I think `--only` would be useful in this case. Feel free to followup if there's something more specific you were interested in.
