### ISSUE TITLE
Allow multiple aliases for a single director

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-cli#185]
Can support be added to allow multiple aliases for a single director URL?

Every time i try to add a second alias, it ends up removing the first, which seems weird.

Also, I can do things like `bosh2 alias-env new-alias -e old-alias`, and see output indicating success, but when i try to use the new alias, I get failure:

```
$ bosh2 alias-env db-proto -e db-eastus-proto
Using environment 'https://10.0.1.4:25555' as client 'admin'

Name      east-us-proto-bosh
UUID      0330dc9a-5850-4a7f-87ea-91135d2c7fa8
Version   260.0.0 (00000000)
CPI       azure_cpi
Features  compiled_package_cache: disabled
          dns: disabled
          snapshots: disabled
User      admin

Succeeded
$ bosh2 envs
URL                     Alias
db-eastus-proto         db-proto
https://10.0.1.4:25555  db-eastus-proto

2 environments

Succeeded
$ bosh2 -e db-proto vms
Fetching info:
  Performing request GET 'https://db-eastus-proto:25555/info':
    Performing GET request:
      Get https://db-eastus-proto:25555/info: dial tcp: lookup db-eastus-proto on 168.63.129.16:53: no such host

Exit code 1
```

**Comment by cppforlife** [comment]
@geofffranks why do you need two aliases for the same director?

**Comment by geofffranks** [comment]
Shared tooling might require a common/explicit alias, but I prefer to use a shorter alias for typing in the CLI manually? Not so much a need as a desire.

Somehow I triggered it to allow me to have two aliases to the same director once, so it seemed like it was semi-supported, but I haven't been able to reproduce that behavior.

**Comment by jfmyers9** [comment]
At the moment you can support multiple aliases by running the full `alias-env -e <director-address>` twice. At this point in time it is unlikely that we will support using another alias as the value for `-e` in the `alias-env` command.

Going to close this due to inactivity. Please feel free to reopen this issue if you have further questions.
