### ISSUE TITLE
Please upload tarballs of actual bosh CLI to your github release

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/bosh-cli#187]
Would make it easier than having to go to S3 and finding the tarball.

**Comment by drnic** [comment]
The only URL + sha1 I've found was for bosh-cli v0.0.147 and `533342d7663c3e5dc731769e157608c74dd9eccb`. Could we please upload linux CLI  to this repo's github release?

**Comment by drnic** [comment]
I don't have access to the bosh CI - if the CLI is in S3, can you reply here with a sample concourse resource that will fetch it when its updated?

**Comment by dpb587-pivotal** [comment]
@drnic you can find the downloads referenced from http://bosh.io/docs/cli-v2.html#install. The CLI can also be installed via [cloudfoundry/tap](https://github.com/cloudfoundry/homebrew-tap).

    brew tap cloudfoundry/tap
    brew install bosh-cli

**Comment by zachgersh** [comment]
@cppforlife - can we get a comment here? Assuming you are using concourse should be pretty easy to get the tarballs on the github release. Would be nice.
