### ISSUE TITLE
bosh2 create-release --final --version 3.0.0 > Release version '3.0.0' already exists

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#189]
I previously ran `bosh2 create-release --final --version 3.0.0 --tarball tmp/cf-subway-3.0.0.tgz` but it failed creating the tarball (perhaps because `tmp/` didn't exist yet) and without thinking I cleaned out all the git changes and went to run the command again:

```
$ bosh2 create-release --final --version 3.0.0
Release version '3.0.0' already exists
```

There is no reference to `3.0.0` that I can see in my repo.

Ahh, yes there is: `dev_releases/cf-subway/cf-subway-3.0.0.yml`. Deleting that and its reference in `dev_releases/cf-subway/index.yml` and ... that fixed it.

**Comment by ckurdekar** [comment]
> I previously ran `bosh2 create-release --final --version 3.0.0 --tarball tmp/cf-subway-3.0.0.tgz` but it failed creating the tarball (perhaps because `tmp/` didn't exist yet) and without thinking I cleaned out all the git changes and went to run the command again:
> 
> ```
> $ bosh2 create-release --final --version 3.0.0
> Release version '3.0.0' already exists
> ```
> There is no reference to `3.0.0` that I can see in my repo.
> 
> Ahh, yes there is: `dev_releases/cf-subway/cf-subway-3.0.0.yml`. Deleting that and its reference in `dev_releases/cf-subway/index.yml` and ... that fixed it.

hey did you got solution how to overwrite the final release?
