### ISSUE TITLE
`tasks` isn't across deployments

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry/bosh-cli#192]
My expectations were for `bosh tasks` to list all active tasks, across deployment, rather than just the current/active deployment.

**Comment by dpb587-pivotal** [comment]
Sounds like you might have BOSH_DEPLOYMENT or -d set, which filters out
other tasks. Can use `bosh -d '' tasks` if you want to leave the
deployment-specific environment setting.
-- 
Danny Berger

**Comment by cppforlife** [comment]
might be worth adding a little info line that says deployment picked up from $BOSH_DEPLOYMENT

**Comment by dpb587-pivotal** [comment]
Or merge together the double messages we often emit into `Using deployment 'foo' on environment 'bar' as user 'baz'` (where the env/user already shows).

**Comment by jfmyers9** [comment]
Going to close this issue due to inactivity. Please feel free to reopen if you have further questions.
