### ISSUE TITLE
Cannot create dev release with bosh2, but can with ruby bosh

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-cli#195]
I'm getting the following error trying to create a dev release of haproxy-boshrelease:

```
- Generating multi digest for blob 'aa936bbe-fe82-49cc-82c8-99d867e5b4bb' for path 'keepalived/keepalived-1.2.24.tar.gz' with digest string 'YTY5YjJjNDA2MjdhOWJkNjk2OThhNTdlODFhOGM4Yzk3ODI2MDI1ZA==':
    Unable to parse digest string. Digest and algorithm key can only contain alpha-numeric characters.
```

I've tried `bosh2 reset-release`, but that isn't helping here. Works fine under the old ruby bosh cli.

**Comment by dpb587-pivotal** [comment]
Ruby/CLI was using non-standard annotations for a while (noticeable mainly in some very old release files). I think the more-correct solution is for maintainers to update their `blobs.yml` file. Unlike release YMLs (which we did add support for inline-fixing [here](https://github.com/cloudfoundry/bosh-cli/commit/5646ea8481b15e3db2dbeb2ec1ddc4bf2189569e#diff-9e5d96d40f698036f1af3492d8df9be2)), `blobs.yml` is something which is more likely to be updated without affecting existing release management workflows. I suspect new CLI intentionally does not try to migrate those annotations, but I do think it leads to poor UX and on-boarding experience.

@cppforlife, any objections if community wants to send a refactor+feature PR so annotation replacement works for both release manifests + blobs?

**Comment by jfmyers9** [comment]
Going to close this due to inactivity. Please feel free to reopen this issue if you have further questions or are still running into this issue.
