### ISSUE TITLE
Display whether runtime config is up-to-date or not

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-cli#196]
In `bosh2 deployments`, the state of cloud-config per deployment is displayed. Can we have the runtime config added in to the output there?

**Comment by jfmyers9** [comment]
Closing and reopening to generate a tracker story.

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
