### ISSUE TITLE
bosh ssh IP

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#198]
One of the main reasons you might `bosh ssh <instance>` is because something has gone wrong. When something goes wrong, the error message typically includes the hostname/IP of the failing instance.

But the following fails:

```
bosh ssh IP
```

You get:
```
13:40:53 | Error: No instances matched {:job=>"10.244.0.146", :deployment_id=>2}
```

Can we please support this?

The current workflow is counterintuitive for this general scenario:

1. `bosh instances`
2. Find the IP in the long list
3. Realise you could grep: `bosh instances | grep IP`
4. Now run `bosh ssh instance_group/eb03c608-c294-47e3-8fa7-e13ba4c1cda5`

The following would be more natural given that you already know the IP address:

```
bosh ssh IP
```

**Comment by cppforlife** [comment]
@dpb587 were chatting about this feature some time ago. it would be pretty handy.

**Comment by dpb587-pivotal** [comment]
Related: https://github.com/cloudfoundry/bosh/pull/1768
