### ISSUE TITLE
CLI skips not uploaded blobs when creating new release

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry/bosh-cli#199]
Old cli:
```
bosh create release 
Syncing blobs...
container-images/gcr.io_google_containers... downloading 27.7M (0%)
...
/Users/pivotal/.gem/ruby/2.3.1/gems/blobstore_client-1.3262.24.0/lib/blobstore_client/base.rb:63:in `rescue in get': Failed to fetch object, underlying error: #<ArgumentError: missing required parameter params[:key]> /Users/pivotal/.gem/ruby/2.3.1/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/param_validator.rb:26:in `validate!' (Bosh::Blobstore::BlobstoreError)
```

New CLI
```
bosh-cli create-release --version 0.0.2-alpha --tarball=../test.tgz
...
Succeeded
```

I would like new CLI fail if it can't download missing blobs from `config/blobs.yml`

**Comment by alex-slynko** [comment]
Little bit more context.
We have versioned blobs for docker images in Kubo.
We process them in packaging script using: `cp containers-*.tgz ...`
As result they are missing from release tarball.

Kubernetes can download missing images from internet. As result - we have successful deployment with not uploaded blobs.

**Comment by mfine30** [comment]
@alex-slynko is this something you're still interested in?

My understanding of your issue is that the Golang bosh cli is not downloading missing blobs, which seems odd. If that is the case you're seeing, could you provide the specific steps/releases used to reproduce this and any relevant logs?

**Comment by alex-slynko** [comment]
Sample packaging:
```
set -e

  mkdir -p "${BOSH_INSTALL_TARGET:?}/dir"
  cp -a dir/* "${BOSH_INSTALL_TARGET:?}/dir"
```

```
$ cat config/blobs.yml

cat config/blobs.yml
dir/test:
  size: 2519
  sha: d9fcfceb451f8e3debaa7e0fcdd295178fdda9a8
dir/test.yml:
  size: 2618
  sha: cff073c454cb1f54c2e45826768cbb2b806e9711
```

```
$ ls blobs/dir
test.yml
```

`bosh create-release` succeeds even though one of the blobs is missing.

We got this issue when we forgot to upload of the blob and had the similar packaging script.
