### ISSUE TITLE
tables are very wide

### ISSUE THREAD

**Issue by zaksoup** [cloudfoundry/bosh-cli#201]
When running bosh commands like `bosh instances --vitals` or `--details` the table is incredibly wide. Can we look into using some ncurses type library to detect window width and render tables slightly differently instead of wrapping lines?

**Comment by drnic** [comment]
I was hoping CFF would sponsor wide screen monitors for all bosh users :)

**Comment by dpb587-pivotal** [comment]
Then the same command becomes very UI/environment dependent and would be outputting different information. I think that would cause a lot of confusion.

Is `[--column {name}]...` a sufficient alternative to show just the information you care about?

**Comment by zaksoup** [comment]
@dpb587 I disagree that it would be outputting different information given a ui/env. The TTY renderer (as opposed to the JSON renderer etc) can detect the width and wrap columns that go over the width down onto new lines.

Format != content.

**Comment by cppforlife** [comment]
> I was hoping CFF would sponsor wide screen monitors for all bosh users :)

@chipchilders what do you think =)

**Comment by chipchilders** [comment]
@cppforlife you find the funding, I'll find a way to administer it.. probably by asking @drnic to do the fulfillment.

**Comment by mfine30** [comment]
I agree it is frustrating. But given this hasn't made much traction, and there is the `--column` solution, I'm going to close this for now. Feel free to re-open if you want to continue the discussion.
