### ISSUE TITLE
Option order matters?

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh-cli#203]
I expect options to work independent of the order they are specified. But it turns out the order matters.

This

```
bosh create-env bosh-deployment/bosh.yml  \
  --state ./state.json  \
  -o bosh-deployment/external-ip-with-registry-not-recommended.yml \
  -o bosh-deployment/aws/cpi.yml  \
  --vars-store ./creds.yml  \
  -l <(bbl bosh-deployment-vars)
```

generates an error

```
Parsing release set manifest '/Users/lexsys/work/tmp/b/bosh.yml':
  Evaluating manifest:
    Expected to find a map key 'ssh_tunnel' for path '/cloud_provider/ssh_tunnel' (found map keys: 'mbus', 'properties')
```

And this (two -o lines swapped) runs fine:

```
bosh create-env bosh-deployment/bosh.yml  \
  --state ./state.json  \
  -o bosh-deployment/aws/cpi.yml  \
  -o bosh-deployment/external-ip-with-registry-not-recommended.yml \
  --vars-store ./creds.yml  \
  -l <(bbl bosh-deployment-vars) 
```

**Comment by dpb587-pivotal** [comment]
Order is important for the ops (and vars) files. In the example you're running, the registry op file is dependent on some other operation having already configured the `ssh_tunnel`. The `ssh_tunnel` is only used by a couple IaaSes (like AWS), so it's not set by default in the `bosh.yml` file.

More specifically, ops can be used to build on top of each other (or potentially disable earlier configurations) so we intentionally rely on the ordering of the arguments. Variables work in a similar way in that ordering affects precedence of the value.

Seem reasonable?

**Comment by lexsys27** [comment]
Sure! For me was unusual the fact that option order matters - typically you can specify different options for Linux CLI utils in which order you want. I have consulted [POSIX spec](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) and indeed it allows ordering of the _same_ option.

> __Guideline 11:__ The order of different options relative to one another should not matter, unless the options are documented as mutually-exclusive and such an option is documented to override any incompatible options preceding it. If an option that has option-arguments is repeated, the option and option-argument combinations should be interpreted in the order specified on the command line.

I have learned something new! :)
