### ISSUE TITLE
Auto-login when env variables/cli options are set?

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-cli#204]
Since `--client`, `--client-secret`, and their env-variable equivalents `BOSH_CLIENT`/`BOSH_CLIENT_SECRET` are described as application-wide flags/variables, it leads me to believe that they should be used automatically, like `BOSH_ENVIRONMENT` and `BOSH_CA_CERT` when running bosh commands. 

However, if i do not first `bosh login`, things like `bosh cloud-config` fail. Seems like either these flags/variables should be globally supported + auto-login, or they should be removed from global options, and set up as `log-in` specific options.

**Comment by geofffranks** [comment]
This is not actually a problem, just confusion based on the error message.

**Comment by cppforlife** [comment]
@geofffranks what did it come back with?

**Comment by geofffranks** [comment]
```
Finding cloud configs:
  Director responded with non-successful status code '401' response 'Not authorized: '/cloud_configs'
'

Exit code 1
```
