### ISSUE TITLE
bosh deploy issue--openstack

### ISSUE THREAD

**Issue by bxlkm** [cloudfoundry/bosh-cli#206]
bosh-init version 0.0.102
bosh.yml:
---
name: bosh

releases:
- name: bosh
  url: file://~/bosh/bosh-261.4.tgz 
    #https://bosh.io/d/github.com/cloudfoundry/bosh?v=261.4
  sha1: 4da9cedbcc8fbf11378ef439fb89de08300ad091
- name: bosh-openstack-cpi
  url: file://~/bosh/bosh-openstack-cpi-release-31.tgz 
    #https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=31
  sha1: ed48a0e021805448e4581764d11d20696a4eaecb

resource_pools:
- name: vms
  network: admin-private
  stemcell:
    url: file://~/bosh/bosh-stemcell-3363.15-openstack-kvm-ubuntu-trusty-go_agent.tgz
     #https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3363.14
    sha1: 15921b89bc340e541ac6f6ede46b2dae52bd7ba2
  cloud_properties:
    availability_zone: nova
    #read_timeout: 1200
    #state_timeout: 1200
    instance_type: m1.xlarge

disk_pools:
- name: disks
  disk_size: 65_536

networks:
- name: admin-private
  type: manual
  subnets:
  - range: 10.100.101.0/24 # <--- Replace with a private subnet CIDR
    gateway: 10.100.101.1 # <--- Replace with a private subnet's gateway
    dns: [192.168.70.181] # <--- Replace with your DNS
    cloud_properties: {net_id: 64eba259-86c2-46ca-a82f-a36f1a1aca13} # <--- # Replace with private network UUID
- name: public-ext
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres-9.4, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: openstack_cpi, release: bosh-openstack-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: admin-private
    static_ips: [10.100.101.10] # <--- Replace with a private IP
    default: [dns, gateway]
  - name: public-ext
    static_ips: [192.168.85.104] # <--- Replace with a floating IP

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: password # <--- Uncomment & change

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: password # <--- Uncomment & change
      database: bosh
      adapter: postgres

    registry:
      address: 10.100.101.10 # <--- Replace with a private IP
      host: 10.100.101.10 # <--- Replace with a private IP
      db: *db
      http:
        user: admin
        password: admin # <--- Uncomment & change
        port: 25777
      username: admin
      password: admin # <--- Uncomment & change
      port: 25777
      endpoint: http://admin:admin@10.100.101.10:25777

    blobstore:
      address: 10.100.101.10 # <--- Replace with a private IP
      port: 25250
      provider: dav
      director:
        user: director
        password: password # <--- Uncomment & change
      agent:
        user: agent
        password: password # <--- Uncomment & change

    director:
      address: 127.0.0.1
      name: peracloud-bosh
      db: *db
      cpi_job: openstack_cpi
      max_threads: 5
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin} # <--- Uncomment & change
          - {name: hm, password: password} # <--- Uncomment & change

    hm:
      director_account:
        user: hm
        password: password # <--- Uncomment & change
      resurrector_enabled: true

 
    openstack: &openstack
      auth_url: http://192.168.70.161:5000/v3
      project: admin
      username: admin
      api_key: admin
      domain: default
      region: RegionOne
      default_key_name: bosh-stemcell-key
      default_security_groups: [bosh]
      human_readable_vm_names: true
    agent: {mbus: "nats://nats:password@10.100.101.10:4222"}
    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: openstack_cpi, release: bosh-openstack-cpi}

  ssh_tunnel:
    host: 192.168.85.104 # <--- Replace with a floating IP
    port: 22
    user: vcap
    private_key: ./bosh-stemcell-key.pem # Path relative to this manifest file

  mbus: "https://mbus:password@192.168.85.104:6868" # <--- Uncomment & change

  properties:
    openstack: *openstack
    agent: {mbus: "https://mbus:password@0.0.0.0:6868"} # <--- Uncomment & change
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
///////////////////////////////////////////////////////////////////////////////////////////////////////
out:
ubuntu@bosh-cli:~/bosh$ sudo bosh-init deploy ./bosh.yml
Deployment manifest: '/home/ubuntu/bosh/bosh.yml'
Deployment state: '/home/ubuntu/bosh/bosh-state.json'

Started validating
  Validating release 'bosh'... Finished (00:00:41)
  Validating release 'bosh-openstack-cpi'... Finished (00:00:05)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:39)
Finished validating (00:01:27)

Started installing CPI
  Compiling package 'ruby_openstack_cpi/6f724febcae828dcbfea470faff5b104d48dd944'... Finished (00:00:00)
  Compiling package 'bosh_openstack_cpi/119de5f71bee352cabba8575aa97fc993b974f56'... Finished (00:00:00)
  Installing packages... Finished (00:00:15)
  Rendering job templates... Finished (00:00:09)
  Installing job 'openstack_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:25)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-openstack-kvm-ubuntu-trusty-go_agent/3363.15'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Waiting for the agent on VM 'aa396ebe-65d5-4fc0-b430-a123a267c905'... Finished (00:00:01)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:00)
  Deleting VM 'aa396ebe-65d5-4fc0-b430-a123a267c905'... Finished (00:00:28)
  Creating VM for instance 'bosh/0' from stemcell '2b743f37-7591-44aa-8a64-c87606180cc4'... Finished (00:00:54)
  Waiting for the agent on VM '14dd6494-3b5d-42ea-ab69-e553c8ffe99d' to be ready... Finished (00:09:43)
  Creating disk... Finished (00:00:30)
  Attaching disk 'b516e00b-821b-41d0-b190-c3f1aa698cd2' to VM '14dd6494-3b5d-42ea-ab69-e553c8ffe99d'... Finished (00:01:07)
  Rendering job templates... Finished (00:02:06)
  Compiling package 'ruby/c1086875b047d112e46756dcb63d8f19e63b3ac4'... Finished (02:09:35)
  Compiling package 'mysql/b7e73acc0bfe05f1c6cbfd97bf92d39b0d3155d5'... Finished (00:27:37)
  Compiling package 'libpq/661f5817afe24fa2f18946d2757bff63246b1d0d'... Finished (00:28:45)
  Compiling package 'ruby_openstack_cpi/6f724febcae828dcbfea470faff5b104d48dd944'... Finished (02:04:48)
  Compiling package 'postgres/3b1089109c074984577a0bac1b38018d7a2890ef'... Finished (01:55:54)
  Compiling package 's3cli/f87a0db2430a633402b76704fda9328d22fea7ad'... Finished (00:00:09)
  Compiling package 'verify_multidigest/8fc5d654cebad7725c34bb08b3f60b912db7094a'... Finished (00:00:05)
  Compiling package 'registry/7751f332d697c84b5137bdbc7a6cea78fffde75d'... Finished (01:11:52)
  Compiling package 'davcli/5f08f8d5ab3addd0e11171f739f072b107b30b8c'... Finished (00:00:12)
  Compiling package 'postgres-9.4/ded764a075ae7513d4718b7cf200642fdbf81ae4'... Finished (02:01:03)
  Compiling package 'nats/63ae42eb73527625307ff522fb402832b407321d'... Finished (00:06:01)
  Compiling package 'health_monitor/3f862a244cfd5e81067300543a537757cb590b7e'... Finished (01:07:48)
  Compiling package 'nginx/2ec2f63293bf6f544e95969bf5e5242bc226a800'... Finished (00:36:54)
  Compiling package 'bosh_openstack_cpi/119de5f71bee352cabba8575aa97fc993b974f56'... Finished (00:00:56)
  Compiling package 'director/a6bbfcee2c7cf65840ec525b6e3181da6cf59598'... Finished (01:27:10)
  Updating instance 'bosh/0'... Finished (00:01:47)
  Waiting for instance 'bosh/0' to be running... Failed (00:26:51)
Failed deploying (14:23:04)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Received non-running job state: 'failing'
/////////////////////////////////////////////////////////////////////////////////////////////////////
error:
ubuntu@bosh-cli:~$ bosh --cpi
/var/lib/gems/2.3.0/gems/bosh_cli-1.3262.26.0/lib/cli/runner.rb:163:in `parse_global_options': invalid option: --cpi (OptionParser::InvalidOption)
	from /var/lib/gems/2.3.0/gems/bosh_cli-1.3262.26.0/lib/cli/runner.rb:33:in `initialize'
	from /var/lib/gems/2.3.0/gems/bosh_cli-1.3262.26.0/bin/bosh:9:in `new'
	from /var/lib/gems/2.3.0/gems/bosh_cli-1.3262.26.0/bin/bosh:9:in `<top (required)>'
	from /usr/local/bin/bosh:22:in `load'
	from /usr/local/bin/bosh:22:in `<main>'
////////////////////////////////////////////////////////////////////////////////////////////////////
The bosh-cli-v2 have the same mistake!!!!

**Comment by dpb587-pivotal** [comment]
A few suggestions (for more help, please post a more specific error message)...

 * it's concerning that the process is taking so long - typically this means a slow network between your workstation and the target VM (not a major issue), or the target VM is significantly underpowered in terms of CPU (potentially causing complications and problems like this). Most environments will provision a director from scratch in around 30 minutes.
 * to find more details about what was failed, you should ssh to the target VM and [investigate](http://bosh.io/docs/tips.html#failed-job). Under `sudo`, you can try `monit summary` which will suggest specific failing jobs. Then you can look into the respective `/var/vcap/sys/log/*` files for full error messages.
 * you may want to use the latest version of CLI (download from http://bosh.io/docs/cli-v2.html).
 * there is no `bosh --cpi` command, so an error is expected.

**Comment by mllives** [comment]
@dpb587-pivotal  Hi!But it required a password for sudo. Where can I find it?
