### ISSUE TITLE
bosh env should display the CPI version

### ISSUE THREAD

**Issue by pdelagrave** [cloudfoundry/bosh-cli#211]
Here is an example output of `bosh env`:
```
Using environment '10.0.8.6' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)

Name      p-bosh                                
UUID      3b2d1dcc-fc55-4074-9294-018469be4ac6  
Version   261.4.0 (00000000)                    
CPI       azure_cpi                             
Features  compiled_package_cache: disabled      
          config_server: disabled               
          dns: disabled                         
          snapshots: disabled                   
User      director                              

Succeeded
```

There is no way to find out what's the CPI version unless you have access to the director VM or to the initial bosh deployment manifest.

In my case I was filling a CPI bug report and needed the CPI version, but that would be an issue for any operator.

I'd suggest to add the CPI release version and maybe the hash in the output.

**Comment by dpb587-pivotal** [comment]
:link: mentioned in [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1493755177285074)

**Comment by freddesbiens** [comment]
Pierre,

We had a closer look at this. At this time, there is no straightforward way for the director to retrieve the CPI version. Moreover, modifying the CPI contract to return the version would be fairly involved. We feel the cost/benefit on this one is not the best. We will close it for now.

**Comment by dpb587-pivotal** [comment]
cc @mfine30 where there had been recent discussions about what information/features are exposed by `bosh env`.

**Comment by anEXPer** [comment]
The CPI docs regularly indicate that they have features available on a certain version plus - being able to look this up from the CLI would be a good thing.
