### ISSUE TITLE
Question: ops-file path syntax: <any> selector?

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/bosh-cli#215]
Is there a way to select any element (or even selecting elements with a name that matches a pattern) in the ops-file path syntax?

My use case is that I'd like to remove all occurrences of `vm_extensions` from `https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml`.

I'm thinking about something like
```
- type: remove
  path: /instance_groups/*/vm_extensions
```

instead of having to do
```
- type: remove
  path: /instance_groups/name=nats/vm_extensions

- type: remove
  path: /instance_groups/name=etcd/vm_extensions

...
```
and catching up with changes `instance_group` entries.

**Comment by cppforlife** [comment]
@bkrannich we are trying to keep ops file functionality very limited. this should help us in general improve core features of bosh director instead of ops files. currently recommend approach would be to configure explicitly which vm_extensions to remove.

i'll give it some more thought for the future of ops files though.

**Comment by bkrannich** [comment]
@cppforlife Just came across https://github.com/cloudfoundry/cf-deployment/blob/master/operations/scale-to-one-az.yml which is another good example of why it would be great to have a more generic way to do these kinds of replacements. Seems like everybody who's adding/changing job names in cf-deployment will also need to change this file.

**Comment by bkrannich** [comment]
@cppforlife Sorry for teasing. I'm starting to see a pattern evolving here with https://github.com/cloudfoundry/cf-deployment/blob/f9be65c45d25f7b257e3775d4307878178a8c5ce/operations/community/change-metron-agent-deployment.yml being the next instance of having such a selector being useful. Would be great if you could re-consider. Thanks in advance.

**Comment by aeijdenberg** [comment]
See also: https://github.com/cppforlife/go-patch/issues/8 which has some PRs against it.

**Comment by bkrannich** [comment]
@aeijdenberg: Thank you very much for the pointer, wasn't aware of that. Now watching cppforlife/go-patch#8.

**Comment by freddesbiens** [comment]
Closing this for now. Please re-open once the PRs or changes have been merged in go-patch.

**Comment by ckurdekar** [comment]
> @bkrannich we are trying to keep ops file functionality very limited. this should help us in general improve core features of bosh director instead of ops files. currently recommend approach would be to configure explicitly which vm_extensions to remove.
> 
> i'll give it some more thought for the future of ops files though.

I am trying to look for remove operation for item if exists. if doesnot exists then should not through error.
e.g. - type: remove
  path: /instance_groups/name=master/jobs/name=docker?
but i am getting error like
Expected to find exactly one matching array item for path '/instance_groups/name=master/jobs/name=docker' but found 0
