### ISSUE TITLE
`bosh create release` should take `private.yml` credentials as arguments

### ISSUE THREAD

**Issue by DanielJonesEB** [cloudfoundry/bosh-cli#22]
Could we please provide `private.yml` credentials as arguments to `bosh create release`? This would make providing credentials via CI (ie Concourse) much easier, as we don't need to template a file.

**Comment by cppforlife** [comment]
@DanielJonesEB what do you think about specifying path to private.yml via cli flag. then you could do `--private <(something here)`. or do you think private.yml should remain in the repo and just work with -l flag to interpolate variables?

cc @vito

**Comment by DanielJonesEB** [comment]
Thanks for taking the time to consider this, @cppforlife.

There are only three supported blobstore types at present, is that correct? Atmos, S3 and Local? If so, I think the user experience would be nicest if there was the option to specify the relevant values purely by command line `--blobstore-type s3 --access-key foo --secret-key bar`, although I can see that leads to three branches of 'special case' code.

Failing that, the variable interpolation would be cool. I'm not familiar with the `-l` flag: is that something new?

**Comment by cppforlife** [comment]
we are planning to add `--private-conf` flag that can be used with bash's standard pipe redirect:

```
$ bosh create-release --final --private-conf <(lpass ... or may be bosh build-manifest ... -l ...)
```

**Comment by bonzofenix** [comment]
@cppforlife is Atmos still supported in bosh cli V2?

**Comment by tylerschultz** [comment]
@bonzofenix `s3` and `local` are the currently supported types: https://github.com/cloudfoundry/bosh-cli/blob/bb528b8072d38785e29cd1e5d19cdb53a4b46409/releasedir/provider.go#L101-L108

cc @cppforlife

**Comment by freddesbiens** [comment]
Hi @DanielJonesEB!

I simply want to check with you if this issue is still relevant to you. If that's still the case, I will have a deeper discussion on it with the engineering team. Please let me know.

**Comment by DanielJonesEB** [comment]
Thanks for following up! It's not causing any acute pain at the moment.
