### ISSUE TITLE
Downloading releases from manifest in parallel

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-cli#221]
When specifying release URIs in your deployment manifest, the CLI seems to download the tarballs from bosh.io in serial. This can take a fair bit of time when using cf-deployment. Could these downloads and the subsequent uploads be done in parallel instead? We'd be willing to throw a PR together if this seems like a reasonable addition.

**Comment by cppforlife** [comment]
@ljfranklin PR would be great! should we use --parallel option?

**Comment by voelzmo** [comment]
Is this about create-env? Or in which cases is it the CLI downloading the releases? When you're taking about cf-deployment, I'm not sure if this should actually go into the director?

**Comment by ljfranklin** [comment]
@cppforlife `--parallel` sounds fine.

@voelzmo This is for the case where you do a `bosh deploy` and your manifest lists the release URLs and SHAs. I guess I assumed the CLI downloaded those releases then uploaded them to the Director, are you saying that the initial download actually takes place on the Director instead of the CLI?

**Comment by cppforlife** [comment]
>  I guess I assumed the CLI downloaded those releases then uploaded them to the Director, are you saying that the initial download actually takes place on the Director instead of the CLI?

depends on the url type, if it's git+https:// local to cli, but if it's https:// then it's on the director

**Comment by ljfranklin** [comment]
@cppforlife So for the director-side downloads, adding a `--parallel` flag on the CLI would need to forward a new request property to the Director? Or would we forget the CLI flag and add a new `parallel_release_downloads` or similar config property to the Director manifest?

**Comment by voelzmo** [comment]
@ljfranklin yup, that's what I meant :)

Is there a reason why we wouldn't want to use parallel downloads by default? Then why add a flag, we could just always do it, right?

**Comment by cppforlife** [comment]
--parallel default to 5. just want to have an option to set it to 1 if some user is stuck.

**Comment by ljfranklin** [comment]
Started a PR here: https://github.com/cloudfoundry/bosh-cli/pull/229
