### ISSUE TITLE
Unclear usage of `bosh tasks --recent`

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-cli#225]
From the CLI documentation it is unclear how to use the `bosh tasks --recent` command. Current help of the command looks like:

```
Usage:
  bosh2 [OPTIONS] tasks [tasks-OPTIONS]

List running or recent tasks

https://bosh.io/docs/cli-v2#tasks

Application Options:
  -v, --version          Show CLI version
      --config=          Config file path (default: ~/.bosh/config) [$BOSH_CONFIG]
  -e, --environment=     Director environment name or URL [$BOSH_ENVIRONMENT]
      --ca-cert=         Director CA certificate path or value [$BOSH_CA_CERT]
      --sha2             Use SHA256 checksums
      --client=          Override username or UAA client [$BOSH_CLIENT]
      --client-secret=   Override password or UAA client secret [$BOSH_CLIENT_SECRET]
  -d, --deployment=      Deployment name [$BOSH_DEPLOYMENT]
      --column=          Filter to show only given column(s)
      --json             Output as JSON
      --tty              Force TTY-like output
      --no-color         Toggle colorized output
  -n, --non-interactive  Don't ask for user input

Help Options:
  -h, --help             Show this help message

[tasks command options]
      -r, --recent=      Number of tasks to show
      -a, --all          Include all task types (ssh, logs, vms, etc)

Succeeded
```

We see in the help multiple options with equal sign like `--client=`. These options could be used in two ways `--client <client>` or `--client=<client>`. If such an option has an optional default value such as `--recent=`, you can use it only with `--recent=<recent-tasks>`. Otherwise an exception is thrown. So currently you get following exception:

```
$ bosh tasks --recent 100
Command '*cmd.TasksOpts' does not support extra arguments: 100

Exit code 1
```
 
According to [go-flags](https://github.com/jessevdk/go-flags) it is the desired behavior for optional values as documented [here](https://godoc.org/github.com/jessevdk/go-flags#hdr-Available_field_tags).

We have two suggestion how to make the `--recent` option more consistent. Bosh help can be improved with mentioning the default value for `--recent` and stating how to use this option. Alternatively the default value can be removed.

**Comment by dpb587-pivotal** [comment]
I think this behavior is confusing or inconvenient, too. If this is the only scenario, I vote to remove the go-flags default value. Dynamically replace an empty value with the current 25/10/whatever, and include it in the help field, if necessary.

**Comment by cppforlife** [comment]
> I think this behavior is confusing or inconvenient, too.

i agree. never liked it myself.

> I vote to remove the go-flags default value. Dynamically replace an empty value with the current 25/10/whatever, and include it in the help field, if necessary.

go-flags has problem parsing this, hence we cannot have default without requiring non-default to be specified via `=` sign. we can always require value to `-r`?

**Comment by cppforlife** [comment]
>  Bosh help can be improved with mentioning the default value for --recent and stating how to use this option. 

do you think that would be good enough?

**Comment by dpb587-pivotal** [comment]
> go-flags has problem parsing this

Right - I meant, as far as go-flags is concerned, make the `--recent` value non-optional. If the user specifies it, use it; otherwise default to 30 in `tasks.go`, or make an accessor on `TaskOpts` which hides the internal defaulting from `tasks.go`.

**Comment by KaiHofstetter** [comment]
Just realized the problem occurs in combination with options and positional-arguments.
If you use options without positional-arguments, options cannot be used without '='!

We created an issue in the go-flags repo:
https://github.com/jessevdk/go-flags/issues/239

**Comment by freddesbiens** [comment]
We improved the help text returned when running `bosh tasks -h`. This will be part of our next CLI release.
