### ISSUE TITLE
bosh vms and instances - bootstrap node shows up with "*" right next to instance_group

### ISSUE THREAD

**Issue by tushar-dadlani** [cloudfoundry/bosh-cli#23]
when I run bosh vms or instances the bootstrap node shows up with a "*" right next to the string of the instance group

example: 
`instance_gropup/random-guid*`

This means that all my UNIX tools like cut , awk, etc need an extra pipe through `tr -d "*"`
It would be useful if this "*" could have an extra space like this:
`instance_gropup/random-guid *`

**Comment by cppforlife** [comment]
@tushar-dadlani sounds like we should put it into a separate column

**Comment by tushar-dadlani** [comment]
Awesome. That works too.

**Comment by cppforlife** [comment]
that was fixed in https://github.com/cloudfoundry/bosh-cli/releases/tag/v0.0.113
