### ISSUE TITLE
How to generate certificates for bosh director which has multiple IPs?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-cli#235]
Our bosh director needs to be accessed via multiple IPs (public IP, private IP and 9.x IP). How to generate certificates for bosh director which has multiple IPs? Thanks.

**Comment by cppforlife** [comment]
@gu-bin if you are using bosh-deployment, you can write an ops file that adds additional values to alternative names. 

if you are doing it manually, see https://bosh.io/docs/director-certs.html#generate. just change yaml to have multiple ips in alternative names for example.
