### ISSUE TITLE
CI Inaccessible

### ISSUE THREAD

**Issue by Everlag** [cloudfoundry/bosh-cli#236]
The CI reference in the README, <https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh:cli>, links to a server which doesn't respond.

`main.bosh-ci.cf-app.com took too long to respond.`

**Comment by cppforlife** [comment]
@Everlag we have decided to block global access to it as an additional security measure. is there any particular information you were looking for? im trying to find out if there needs to be filtered down view that will be visible to everyone.

**Comment by Everlag** [comment]
I'm in the process of onboarding into developing in the bosh ecosystem. Having the concourse pipeline visible in the web interface makes understanding the pipeline's dependency graph significantly easier.

**Comment by freddesbiens** [comment]
Hi @Everlag. As Dmitriy mentioned, CI access requires authentication. To better understand the pipeline, you are welcome to read and deploy [this pipeline](https://github.com/cloudfoundry/bosh/blob/master/ci/pipeline.yml) to your own environment.
