### ISSUE TITLE
create-env manifest validation doesn't catch missing properties - render job templates fails with obtuse erb_render error

### ISSUE THREAD

**Issue by adi-mishra** [cloudfoundry/bosh-cli#240]
When `properties` block is midding from the job block in manifest, `bosh create-env` fails during `Rendering job templates...` step with error 
```
Deploying:
  Building state for instance 'concourse/0':
    Rendering job templates for instance 'concourse/0':
      Rendering templates for job 'unpack/213b9aaf8ee2b59dd4900c6c5435bafc281b8e34':
        Rendering template src: ignoreme, dst: ignoreme:
          Rendering template src: /Users/pivotal/.bosh/installations/3525263c-b10f-4905-6620-381612ee4cf6/tmp/bosh-release-job056632948/templates/ignoreme, dst: /Users/pivotal/.bosh/installations/3525263c-b10f-4905-6620-381612ee4cf6/tmp/rendered-jobs562517277/ignoreme:
            Running ruby to render templates:
              Running command: 'ruby /Users/pivotal/.bosh/installations/3525263c-b10f-4905-6620-381612ee4cf6/tmp/erb-renderer573538776/erb-render.rb /Users/pivotal/.bosh/installations/3525263c-b10f-4905-6620-381612ee4cf6/tmp/erb-renderer573538776/erb-context.json /Users/pivotal/.bosh/installations/3525263c-b10f-4905-6620-381612ee4cf6/tmp/bosh-release-job056632948/templates/ignoreme /Users/pivotal/.bosh/installations/3525263c-b10f-4905-6620-381612ee4cf6/tmp/rendered-jobs562517277/ignoreme', stdout: '', stderr: '/Users/pivotal/.bosh/installations/3525263c-b10f-4905-6620-381612ee4cf6/tmp/erb-renderer573538776/erb-render.rb:11:in `merge!': no implicit conversion of nil into Hash (TypeError)
```
but passes `Validating deployment manifest...` step.

**Comment by adi-mishra** [comment]
@xtreme-gavin-enns

**Comment by cppforlife** [comment]
@adi-mishra properties key should either be on the job level or not. cannot have it as `nil`. if that's not what's happening, you'll have to provide manifest that causes this problem.

**Comment by xtreme-gavin-enns** [comment]
Yeah, exactly. The cli just doesn't catch this error at the validation step. We weren't able to track down which hash was unexpectedly nil except through visual validation of our yaml files.

**Comment by dpb587-pivotal** [comment]
Story: https://www.pivotaltracker.com/story/show/150620709

**Comment by gberche-orange** [comment]
I ran into this issue when deploying a job that was not expecting any properties, and whose deployment manifest omitted the job properties block. Adding a non-empty `properties` block in the job section solved the issue. Thanks for the workaround documentation.

```yml
    properties:
       dummy: dummy # Just to keep bosh-cli happy, see https://github.com/cloudfoundry/bosh-cli/issues/240
```

**Comment by dpb587-pivotal** [comment]
Alternatively, I think you should be able to say `properties: {}` (i.e. can be more concise than a dummy key, if you want).
