### ISSUE TITLE
Gateway user defaults to vcap, not jumpbox

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/bosh-cli#243]
In the modern era, most stemcells will not allow the user "vcap"ssh access. The cli has a sweet feature where it will try "vcap" if a gateway user is not available for the bosh ssh command. I suggest that this should  default to "jumpbox"

**Comment by dpb587-pivotal** [comment]
Good thinking. Technically, the default is configured via `director` property,
 [`director.default_ssh_options.gateway_user`](https://github.com/cloudfoundry/bosh/blob/master/jobs/director/spec#L188), so it'd probably make sense to PR [`jumpbox-user.yml`](https://github.com/cloudfoundry/bosh-deployment/blob/master/jumpbox-user.yml) to also change the default setting to `jumpbox` (if you're interested).

**Comment by cppforlife** [comment]
updated jumpbox-user.yml in bosh-deployment.

**Comment by evanfarrar** [comment]
Thanks! I had no idea this could be done via configuration, so it's great that these two facts can be isolated to the same file.
