### ISSUE TITLE
cf curl to support -d @- like curl does

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#244]
In `curl` you can pass thru STDIN using `-d @-` (see https://curl.haxx.se/mail/archive-2002-01/0093.html) but I tried this with `cf curl` and the error is:

```
cf curl /v2/apps/5ce9f4b7-7485-464d-bdaa-d683fc994f00/droplet/upload -X PUT -d @-
FAILED
open -: no such file or directory
```

Could we add support for `-d @-` syntax to read from STDIN?

**Comment by Amit-PivotalLabs** [comment]
@drnic did you mean to open this on https://github.com/cloudfoundry/cli?

**Comment by drnic** [comment]
Poop. Yes, thanks.
