### ISSUE TITLE
Include Binaries in Github Release

### ISSUE THREAD

**Issue by johnlonganecker** [cloudfoundry/bosh-cli#25]
At Stark & Wayne we have a homebrew tap for some useful CF tools (https://github.com/starkandwayne/homebrew-cf) and it works off of a concourse github-release resource.

It would be really helpful if the bosh-cli binary was included in the github release. The binary could then be downloaded from: 

https://github.com/cloudfoundry/bosh-cli/releases/download/v0.0.70/bosh-cli-darwin-amd64

It is also nice to have the binary and the source code all in one place. I can see exactly what code the binary has by its corresponding git tag.

**Comment by cppforlife** [comment]
@johnlonganecker sounds reasonable. mind doing a PR for the pipeline change?

**Comment by johnlonganecker** [comment]
Sure, I can do that

**Comment by cppforlife** [comment]
github.com/cloudfoundry/homebrew-tap is now being automatically updated thx to @wendorf
