### ISSUE TITLE
upload-release with --rebase flag fails on final releases

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/bosh-cli#250]
Say I try:
```
bosh -e lite upload-release releases/loggregator/loggregator-90.1.yml --rebase
```

The CLI will say (eventually):
```
12:32:43 | Extracting release: Extracting release (00:00:00)
12:32:43 | Verifying manifest: Verifying manifest (00:00:00)

12:32:44 | Error: Failed to Rebase - Invalid Version: #<Bosh::Common::Version::ReleaseVersion:0x0056454ee742f0 @version=#<SemiSemantic::Version:0x0056454ee74368 @release=#<SemiSemantic::VersionSegment:0x0056454ee74408 @components=[90, 1]>, @pre_release=nil, @post_release=nil, @segments=[#<SemiSemantic::VersionSegment:0x0056454ee74408 @components=[90, 1]>]>>
```

I expected the CLI to be smart enough to inspect the release and see that it was a final release and upload it in a normal fashion.

**Comment by cppforlife** [comment]
--rebase only works with release versoins that have a pre prelease (eg `+dev.1`). we are also encouraging to stop using --rebase in general. care elaborating what workflow you are using it in?

**Comment by apoydence** [comment]
We were trying to use the cloudfoundry/bosh-deployment-resource to deploy dev releases to our dev environment. However, in doing so, we need to upload dependencies that are final releases.

Since the bosh-deployment-resource has one step for uploading and deploying, we wanted to "mix" our dev releases with the final and have the CI resource upload and deploy them. That being said, that resource doesn't support yet rebasing.

May I ask why --rebase is discouraged?

**Comment by dpb587-pivotal** [comment]
Rebasing release versions is giving the director responsibility to create new release versions which leads to non-deterministic versions that are not easily reproducible. The "more correct" way is to have the operator/user create the release exactly as they want locally, and then upload it. Director shouldn't be responsible for "creating" new release versions - that's the CLI and source repository's responsibility.

For your particular situation, I think it'd be better if you had a dedicated task for mixing in the dev and final releases. Hopefully it makes it a bit more testable for you as well to ensure everything gets mixed as you expect.

**Comment by apoydence** [comment]
I see what you mean. Thanks.
