### ISSUE TITLE
blobstore upload for large file fails with Riak CS

### ISSUE THREAD

**Issue by MuthuvelkumarS** [cloudfoundry/bosh-cli#253]
I am trying to upload the large file into RiakCS using bosh cli. It is failing with the below error. I am able to upload small files. I don't find required document to support Multipart config option. Does bosh cli support multipart upload  for S3 compatible store such as Riak CS? If so, how to configure it?
```
$ bosh upload-blobs
Blob upload 'SEP_12_1_0_SRV_X.exe' (207 MB) (sha1: abed5785c8030afe6972338a940c6be90016ded7) started
2017/07/05 12:15:13 Upload retry limit exceeded: MultipartUpload: upload multipart failed
        upload id: FkHIkOneSs2eg8zf0SKqnQ==
caused by: SerializationError: failed to decode S3 XML error response
        status code: 403, request id:
```

**Comment by cppforlife** [comment]
@MuthuvelkumarS we are using default aws go sdk (https://github.com/cloudfoundry/bosh-s3cli). i thought they have multi part done automatically.

**Comment by MuthuvelkumarS** [comment]
Even with bosh-S3Cli, I am getting the same error. 
```
bosh@bosh-jumpbox:~/muthu/s3cli$ s3cli -c config.json put SEP_12_1_0_SRV_X.exe SEP_12_1_0_SRV_X.exe
2017/07/18 07:50:15 Upload retry limit exceeded: MultipartUpload: upload multipart failed
        upload id: KuzII3WWTKaQXXe5QIsQRg==
caused by: SerializationError: failed to decode S3 XML error response
        status code: 403, request id: , host id:
caused by: unexpected EOF
2017/07/18 07:50:15 performing operation put: upload retry limit exceeded: MultipartUpload: upload multipart failed
        upload id: KuzII3WWTKaQXXe5QIsQRg==
caused by: SerializationError: failed to decode S3 XML error response
        status code: 403, request id: , host id:
caused by: unexpected EOF
```

**Comment by dpb587-pivotal** [comment]
The 403 Forbidden error suggests that the authentication may be wrong - perhaps you can double check the access/secret key being used?

**Comment by MuthuvelkumarS** [comment]
With same config file, I am able to upload the small text file. It is working fine with out any issue. Only with large files, I am getting issue.
```
$ s3cli -c config.json put small.txt small.txt
```

**Comment by freddesbiens** [comment]
Hi @MuthuvelkumarS. 

Do you still experience this issue?

**Comment by freddesbiens** [comment]
I will close this issue for now since it has been inactive for a while. Please feel free to re-open it if you are still experiencing problems.
