### ISSUE TITLE
JSON output of `inspect-release` is difficult to parse

### ISSUE THREAD

**Issue by poy** [cloudfoundry/bosh-cli#257]
When parsing the `links_consumed` and `links_provided` from:
```
bosh -e lite inspect-release myrelease/0+dev.1 --json
```

The resulting output has:
```
"links_consumed": "- name: myjob\n  type: myjob\n  optional: true",
"links_provided": "- name: myotherjob\n  type: myotherjob"
```

I would have expected this to be better formatted. As an example:
```
"links_consumed": [{
  "name": "myjob",
  "type": "myjob",
  "optional": "true"
}], 
"links_provided": [{
  "name": "myotherjob",
  "type": "myotherjob"
}]
```

I'm running the bosh-cli version: 
```
bosh --version
version 2.0.26-105157c-2017-06-22T18:54:04Z
```

**Comment by cppforlife** [comment]
PR was reverted because it broke integration tests. Planning to fix them at some point but didnt have a chance yet...

**Comment by freddesbiens** [comment]
The `--json` flag returns details on how the table formatting should be like. We will investigate whether we should be doing the change as described for this flag or implement a different method to return raw director responses back to the operator.

Closing and re-opening to create an issue in Tracker.

**Comment by xtreme-andrew-su** [comment]
@poy From the sounds of this, you're trying to script something. For the time being, if your bosh-cli supports the `curl` command you can use something like: `bosh curl /releases/<release_name>?version=<version>` make sure your release name and version is url encoded. That should give you the raw version of the request.

**Comment by dpb587-pivotal** [comment]
* with the caveat that the director API is less officially versioned than the CLI
