### ISSUE TITLE
bosh cli installtion failing in ubuntu user

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry/bosh-cli#26]
I have Inception VM where bosh cli version is 1.3071.0 installed in it.
I want to upgarde to latest bosh cli  1.3262.4.0

When i install the bosh cli using following command in command line as root user it works fine and I get updated version in both ubuntu user and and root user.

```
sudo su
gem install bosh_cli

 bosh --version
BOSH 1.3262.4.0

```
but when I do the installation in ubuntu user it install successfully but shows older version only.

```
sudo gem install bosh_cli 

bosh --version
BOSH 1.3071.0

```

**Comment by cppforlife** [comment]
@chrisrana sounds like your `gem env` is configured to do separations by the user. please consult ruby docs on how to configure gem environment to prefer gems in given locations. alternatively use one of the projects like rbenv, rvm, chruby, etc.

(note: that this repo is not for the currently official ruby bosh cli, but for the new go bosh cli that will eventually replace the ruby one).
