### ISSUE TITLE
`bosh restart` gives no error when supplied non-existent Instance Group

### ISSUE THREAD

**Issue by oppegard** [cloudfoundry/bosh-cli#262]
BOSH CLI version: 2.0.28
BOSH Director version: 262.1.0 (PCF 1.11)

We had a confusing experience when using `bosh restart`. When given a non-existent instance group to restart, the CLI returns a success message. In our specific case we'd renamed the instance group recently, but our docs referenced the old name.

Here's what the interaction currently looks like:
```
/bosh-cli-2.0.28-linux-amd64 -n -d solr-platinum restart foo
Using environment '10.3.2.10' as user 'director' (bosh.*.read, openid, bosh.*.admin, bosh.read, bosh.admin)

Using deployment 'solr-platinum'

Task 1288

20:52:50 | Preparing deployment: Preparing deployment (00:00:00)
20:52:56 | Preparing package compilation: Finding packages to compile (00:00:01)

Started  Thu Jul 13 20:52:50 UTC 2017
Finished Thu Jul 13 20:52:57 UTC 2017
Duration 00:00:07

Task 1288 done

Succeeded
```

In this case, Instance Group *foo* doesn't exist, and we'd hope to get an error in that case.

**Comment by cppforlife** [comment]
@oppegard how about providing an event in the task log that shows that it affected 0 instances

**Comment by oppegard** [comment]
@cppforlife an error would be more useful in this case. If that's not possible then output in the task log is certainly better than nothing. And by task log, do you mean what's output to the operator? Something like:

```
20:52:50 | Preparing deployment: Preparing deployment (00:00:00)
20:52:56 | Preparing package compilation: Finding packages to compile (00:00:01)
...
20:52:57 | 0 instances of group 'foo' restarted (00:00:01)
...
```

**Comment by dpb587-pivotal** [comment]
@cppforlife, I think the task should fail if it was not able to act as the user desired. Seems like instance group with a given name is an unmet prerequisite, which is more of an error.

**Comment by tjvman** [comment]
Related issue/possible duplicate: https://github.com/cloudfoundry/bosh-cli/issues/71

**Comment by freddesbiens** [comment]
Closing this issue to simplify management on our side, as fixing #71 will also solve this one. Please feel free to reopen if you feel this issue needs its own separate conversation.
