### ISSUE TITLE
ssh command does not list VM name upon failure

### ISSUE THREAD

**Issue by poy** [cloudfoundry/bosh-cli#264]
Say I run a ssh command across my VMs:

```
bosh -e lite -d loggregator ssh "" -c "/tmp/some_script.sh"
```

However some of the VMs do not have `/tmp/some_script.sh`. Then I will get a failure message that simply says the ssh command failed:

```
* Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/Users/pivotal/.bosh/tmp/ssh-priv-key948618933 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/pivotal/.bosh/tmp/ssh-known-hosts461621904 10.244.0.131 -l bosh_d05e9849e53d469 /tmp/some_script.sh', stdout: '', stderr: '': exit status 127
* Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/Users/pivotal/.bosh/tmp/ssh-priv-key948618933 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/pivotal/.bosh/tmp/ssh-known-hosts461621904 10.244.0.129 -l bosh_d05e9849e53d469 /tmp/some_script.sh', stdout: '', stderr: '': exit status 127
```

It would be very helpful to see what VM names have failed instead of having to cross reference the given IP for each failure message.

**Comment by cppforlife** [comment]
@apoydence does `-r` help here?

**Comment by apoydence** [comment]
@cppforlife It does as long as the command isn't streaming. 

If I were to try to do something like tail a log, then the `-r` would prevent the command from ever returning.

**Comment by freddesbiens** [comment]
Hey @poy. 

I ran the same command today on a recent BOSH build with the latest CLI and got a different output. 

`test_node/52510542-14a2-42d5-8407-10434296f137: stdout | bash: /tmp/some_script.sh: No such file or directory`

Is still still an issue for you?
