### ISSUE TITLE
create-release --tarball puts tarball in releases/, but yml in dev_releases

### ISSUE THREAD

**Issue by njbennett** [cloudfoundry/bosh-cli#27]
Creating a release with a tarball puts the generated tarball in `releases/`, but it puts the generated yml in `dev_releases/`

The old ruby CLI put both artifacts in `dev_releases/`.

We don't want to pollute our `releases` directory with dev artifacts that shouldn't be committed.

**Comment by cppforlife** [comment]
@njbennett i just tried it with a test release and it placed tgz into dev_releases folder. anything special about the way you create the release?

**Comment by cppforlife** [comment]
the only time that it will be saved into releases/ folder is when version of the release does not contain dev after plus (eg `123+dev.2` is ok; `123-dev.2` is not considered to be a dev version).

**Comment by cppforlife** [comment]
Found the problem.

**Comment by cppforlife** [comment]
We are planning to change --tarball to take a path to the desired location, eg

```
$ bosh create-release --tarball=~/Downloads/blah.tgz
```

cc @vito

**Comment by cppforlife** [comment]
Latest CLI versions require users to specify path with --tarball.
