### ISSUE TITLE
How to generate director certificate using an existing CA certificate?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-cli#270]
I'm referring to the page http://bosh.io/docs/director-certs.html to generate bosh director certificate. It generates both CA certificate and director certificate. Is there any way to generate the director certificate using an existing CA certificate? Thanks.

**Comment by Kiemes** [comment]
@gu-bin You can let the generation of certificates run once so you see the output in `certs.yml`
Delete everything from the `certs.yml` except the `default_ca` hash part which has three sub keys `ca`, `certificate` and `private_key`. Replace the values of those 3 keys with your existing CA certificate and the corresponding private key (`ca` and `certificate` take the same value).

If you run the interpolate command again, the bosh cli will use the values from `certs.yml` to generate the remaining values.

**Comment by gu-bin** [comment]
@Kiemes Thanks for your advise. It perfectly solved my problem!

**Comment by poblin-orange** [comment]
@Kiemes usefull. However a bit counter intuitive . Is there way i could set the ca cert in a vars-file, so the cli can directly populate the values in the cred.yml ?

I tried this in my vars file, with no success :
```
# provision private ca
default_ca:
  ca:  | ...
  certificate: | ...
  private_key:  | ...

```
Could that work ?

**Comment by Kiemes** [comment]
@poblin-orange you can set your ca cert in vars-store directly without doing the first interpolation as you already know how the block looks like.

My description above is for people who do not know how a certificate definition looks like. In your case, you can start already by creating an empty `certs.yml` (vars-store) and put your default ca definition in. Then just hit deploy.

Duplicating information tends to be error prone. Having the same variables in vars-file and vars-store might create confusion.

**Comment by poblin-orange** [comment]
ok thks @Kiemes
