### ISSUE TITLE
Misleading output in `bosh create-release --sha2`

### ISSUE THREAD

**Issue by WesleyJeanette** [cloudfoundry/bosh-cli#272]
When creating a release with SHA2, the output is misleading:

For example:

```
-- Started uploading 'license/<SHA HERE>' (sha1=sha256:<SHA2 HERE>)
```

Note that it says, "sha1=sha256:...".

Also, the artifact in `.final_builds` is likewise misleading:
```
<SOME_VERSION>:
  version: <SOME_VERSION>
  blobstore_id: <BLOBSTORE_ID>
  sha1: sha256:<SHA2>
```
The fact that sha1 and sha256 share the same line with a single space between them appears to be missing the sha256 at first look. The addition of a newline between the two would greatly improve readability.

/cc @enocom

**Comment by cppforlife** [comment]
yeah, this one is an interesting one. what we actually have done is continued using sha1 field for any checksum but now started allowing different algos within. it is too much work right now to refactor and rename everywhere checksum column. over longer period of time we will probably slowly converge to a better name for the field.

regarding "sha1=" ui, that one we can easily fix.

**Comment by jasonkeene** [comment]
![image](https://user-images.githubusercontent.com/161453/28475888-4b1dfa62-6e0b-11e7-9665-46d376fa8f37.png)

**Comment by freddesbiens** [comment]
We think this issue is worth solving, but we need to be careful about the implementation since changing this overnight would break scripts built by our users. Closing and re-opening to create a Tracker story. We will investigate the proper approach to mitigate migration issues.
