### ISSUE TITLE
How to specify the expiration time of the bosh certificates?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-cli#273]
I'm referring to the page http://bosh.io/docs/director-certs.html to generate bosh director certificate. By default, the generated CA and director certificates will expire in 365 days. Is there any way to specify a longer period for expiration? Thanks.

**Comment by cppforlife** [comment]
@gu-bin not possible via CLI atm. it's hard coded: https://github.com/cloudfoundry/bosh-cli/blob/master/vendor/github.com/cloudfoundry/config-server/types/certificate_generator.go#L153. it may be possible via credhub.

**Comment by gu-bin** [comment]
@cppforlife Is there any reason why it's hard coded? One year is too short for us.

**Comment by paolostivanin** [comment]
one year is too short also for us

**Comment by paolostivanin** [comment]
@cppforlife also for us 1y is too short

**Comment by youngm** [comment]
@cppforlife It is possible to set the duration of a certificate generated in Credhub.  However, is their a way to pass that duration from a manifest to credhub?  It would be nice if a property existed that the CLI would honor and could be passed to the config server api as well.

https://credhub-api.cfapps.io/#type-certificate30

**Comment by maplain** [comment]
> @gu-bin not possible via CLI atm. it's hard coded: https://github.com/cloudfoundry/bosh-cli/blob/master/vendor/github.com/cloudfoundry/config-server/types/certificate_generator.go#L153. it may be possible via credhub.

now, it's at: https://github.com/cloudfoundry/bosh-cli/blob/master/vendor/github.com/cloudfoundry/config-server/types/certificate_generator.go#L172

**Comment by mfine30** [comment]
@freddesbiens @xtreme-andrew-su this seems really similar to some work I think you've mentioned recently?

**Comment by xtreme-andrew-su** [comment]
There is a PR https://github.com/cloudfoundry/config-server/pull/13 which propagate the changes to the CLI once it's merged.

**Comment by kitsirota** [comment]
+1 We rotate our certs every year anyways, but having the ability to schedule this on our terms makes this much easier to maintain.

**Comment by h4xnoodle** [comment]
This is now in bosh cli version 6.0.0.
