### ISSUE TITLE
Documentation for `--final` is vague

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/bosh-cli#275]
When creating a release with the `--final` flag, the Bosh CLI writes artifacts to the network which is completely surprising for a new user, especially when the documentation just says, "Make it a final release."

Instead, when running `bosh create-release --help`, I would expect the `--final` flag to say something like, "Create a yml file describing the release and upload bits to s3" or some such.

**Comment by mfine30** [comment]
I agree, this is an area that could be improved. Closing/re-opening to trigger a story for us to track.

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
