### ISSUE TITLE
BOSH2 cli unable to create-release in cf-release due to many symlink redirections

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/bosh-cli#276]
When using the bosh2 CLI to create-release in cf-release v268.  We got several issues with regards to symlink traversal.   Right now bosh2 CLI will not create-release in the cf-release codebase.

Version of bosh2 CLI is version 2.0.29-1f8ec43-2017-07-14T16:10:31Z

This is on OSX

bosh2 create-release
Building a release from directory '/Users/aedgar/workspace/cf-release':
  - Constructing jobs from manifest:
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_clock':
          Fingerprinting source files:
            Fingerprinting file '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_clock/templates/newrelic.yml.erb':
              lstat /Users/aedgar/workspace/cf-release/src/capi-release/shared_job_templates: no such file or directory
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_ng':
          Fingerprinting source files:
            Fingerprinting file '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_ng/templates/blobstore_waiter.sh.erb':
              lstat /Users/aedgar/workspace/cf-release/src/capi-release/shared_job_templates: no such file or directory
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_worker':
          Fingerprinting source files:
            Fingerprinting file '/Users/aedgar/workspace/cf-release/jobs/cloud_controller_worker/templates/blobstore_waiter.sh.erb':
              lstat /Users/aedgar/workspace/cf-release/src/capi-release/shared_job_templates: no such file or directory
      - Reading job from '/Users/aedgar/workspace/cf-release/jobs/java-offline-buildpack':
          stat /Users/aedgar/workspace/cf-release/jobs/java-offline-buildpack: no such file or directory

Exit code 1

Please validate that the bosh2 CLI will work the same way as bosh ruby CLI in the cf-release

**Comment by cppforlife** [comment]
@andrew-edgar bosh cli v2 cleaned up a lot of create release interactions. part of it was to remove some confusing symlink support that was part of cf-release. given that it was a major cli version bump we decided it was a good time, especially as cf-deployment takes form, to stop supporting this symlink features. we are still continuing to support bosh1 cli and we do expect that bosh2 is able to upload cf-release (just not create it).

**Comment by andrew-edgar** [comment]
so I'm not sure I understand.   are you saying that bosh2 cli will never support create-release in the cf-release?

**Comment by dpb587-pivotal** [comment]
Correct - where cf-release was trying to re-package the jobs+packages of other compatible release versions into a new release, cf-deployment is [more correctly] referring to and deploying a set of original, compatible release versions.

Because cf-deployment is the goal, we're not planning on supporting the cf-release-style of release management which symlinks in other releases. It's preferable to refer to those releases directly through a deployment manifest-type approach.

For some scenarios, you may need to work with a patched version of a release. In that case, you'd work with the forked release as you normally would, but instead of updating a symlink/submodule you would patch the deployment manifest to refer to your repo/tarball instead (preferably through an ops file).

**Comment by mseric** [comment]
Hello guys, I also encounter the issue when I run the command 
"bosh create-release" in centOS, I follow the guide from "https://docs.cloudfoundry.org/deploying/aws/setup_bosh_aws.html", which recommends to download the bosh cl v2.
@andrew-edgar , did you figure it out? could you please give me a hand? I have no idea for it now. 

Thanks

**Comment by cppforlife** [comment]
@mseric you can download already created release from http://bosh.io/releases/github.com/cloudfoundry/cf-release?all=1. if you need to run `create release` against cf-release you ll have to use bosh cli v1.

**Comment by mseric** [comment]
@cppforlife Thanks for timely response, the cf-release I am using is the latest version(273). 
um.. let me try if bosh cli v1 works or not. 

but I am confuse that why the cloud foundry still recommend that using bosh cli v2 to run create release on their website.
https://docs.cloudfoundry.org/deploying/aws/deploy-aws.html

**Comment by mseric** [comment]
I got the error after the bosh version down to bosh cli v1.
[root@paas-openshift cf-release]# bosh -v
BOSH 1.3262.26.0
[root@paas-openshift cf-release]# bosh create-release
Unknown command: create-release

It seems that there is not the command "create-release" in bosh cli v1.

**Comment by cppforlife** [comment]
@mseric cli v1 has "create release" command. given that it appears that you are trying things out, i would strongly recommend to give cf-deployment a try: https://github.com/cloudfoundry/cf-deployment. we are in the slow process of deprecating cf-release so some docs might be a bit ahead of its time.

**Comment by mseric** [comment]
@cppforlife thanks a lot for your help, I run the command "create release" with cli v1, it works. and the command returns release summary, packages and jobs, etc with no error.

I will try use cf-deployment later, but for now, if it is ok for create release with cli v1, I need to do next step.

thanks again. :100:
