### ISSUE TITLE
Unclear "cannot find blob" error message

### ISSUE THREAD

**Issue by njbennett** [cloudfoundry/bosh-cli#28]
We were confused by the error message when building our release in a one-off Concourse job.
```
$ gobosh -n create-release --name cf-mysql --version 31.33+g3e3d717 --tarball --force
Building a release from directory '/tmp/build/e55deab7/cf-mysql-release':
  Cannot find blob '' with SHA1 'de370941424b8db054a953bf4dc9925de6f6c33d'
```

It looks like this was caused because we ran it on a workspace polluted with artifacts from the ruby CLI, but we didn't have any idea what to do about this error before talking to the Bosh team.

Some suggestion about what to do to clean up the directory (Dmitriy suggested running `bosh reset-release`) or an indication of what files Bosh was referencing might have allowed us to solve the problem on our own.

**Comment by cppforlife** [comment]
In the next version.
