### ISSUE TITLE
Bosh ssh output contains Windows line endings on Linux

### ISSUE THREAD

**Issue by jsievers** [cloudfoundry/bosh-cli#281]
bosh ssh output lines are terminated by windows line endings on Linux.

steps to reproduce:

```
$ bosh -e <YOUR_ENV> -d cf ssh router_z1  -c 'uname -a' > /tmp/test.txt
$ cat -v /tmp/test.txt
router_z1/a0bdc9e8-bb56-441b-8a13-37ab7b8785c0: stderr | Unauthorized use is strictly prohibited. All access and activity
router_z1/a0bdc9e8-bb56-441b-8a13-37ab7b8785c0: stderr | is subject to logging and monitoring.
router_z1/a0bdc9e8-bb56-441b-8a13-37ab7b8785c0: stdout | Linux 3c33555f-5fd1-4a1e-a1bf-4ff243b3a780 4.4.0-81-generic #104~14.04.1-Ubuntu SMP Wed Jun 14 12:45:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux^M
router_z1/a0bdc9e8-bb56-441b-8a13-37ab7b8785c0: stderr | Connection to 10.0.65.8 closed.^M
```

cat -v  shows the ^M line endings

we noticed this because some line-based unix utilities like `xargs -L1`  will get confused by windows line endings.

workaround is to remove windows line endings by piping output into `tr -d '\015'`

**Comment by mfine30** [comment]
Looks like this is still a problem with CLI v 5.3.1
```
 $ bosh -d zookeeper ssh zookeeper/0  -c 'uname -a' > /tmp/test.txt

 $ cat -v /tmp/test.txt
zookeeper/76e90505-521a-4ad7-93f3-d8dea99894e2: stderr | Unauthorized use is strictly prohibited. All access and activity
zookeeper/76e90505-521a-4ad7-93f3-d8dea99894e2: stderr | is subject to logging and monitoring.
zookeeper/76e90505-521a-4ad7-93f3-d8dea99894e2: stdout | Linux 4fcfa047-85ff-4ef6-8a0f-f5ff76ea898b 4.4.0-139-generic #165~14.04.1-Ubuntu SMP Wed Oct 31 10:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux^M
zookeeper/76e90505-521a-4ad7-93f3-d8dea99894e2: stderr | Connection to 10.0.1.0 closed.^M

 $ bosh -v
version 5.3.1-8366c6fd-2018-09-25T18:25:48Z

Succeeded
```

**Comment by mfine30** [comment]
closing and re-opening to trigger a tracker story

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
