### ISSUE TITLE
Bosh CLI command that can remove an environment alias?

### ISSUE THREAD

**Issue by nwoike** [cloudfoundry/bosh-cli#284]
We are working on teardown scripts and `delete-env` does not remove the environment alias. Is there an argument that can be provided to `bosh alias-env` to remove a previously created alias? Or maybe there could be a new `delete-alias` command?

For now we are forced to manually clean up our `~/.bosh/config` but since we have multiple alias its an ugly shell script.

**Comment by dpb587-pivotal** [comment]
There's not currently a `delete-alias` command, but feel free to send a pull request.

However, I believe `bosh alias-env ...` should be overwriting an environment if its alias already exists. Is that not working for you?

**Comment by Velann** [comment]
Its not getting over written rather its throwing below error.
bosh alias-env kubo -e <ip> --ca-cert <(bosh int /root/bosh-1/bosh-deployment/creds.yml --path /director_ssl/ca)
Using environment <ip> as client 'admin'

Fetching info:
  Performing request GET 'https://<ip>:25555/info':
    Performing GET request:
      Requesting token via client credentials grant: UAA responded with non-successful status code '401' response '{"error":"unauthorized","error_description":"Bad credentials"}'

Exit code 1

After i edited kubo to kubo1 then it worked:

bosh alias-env kubo1 -e <ip> --ca-cert <(bosh int /root/bosh-1/bosh-deployment/creds.yml --path /director_ssl/ca)
Using environment '<ip>' as anonymous user

Name      <----->  
UUID      <----->  
Version   264.7.0 (00000000)  
CPI       vsphere_cpi  
Features  compiled_package_cache: disabled  
          config_server: enabled  
          dns: disabled  
          snapshots: disabled  
User      (not logged in)  

Succeeded

**Comment by mfine30** [comment]
This should be resolved in the next bosh-cli release. The current release is v5.4.0.
