### ISSUE TITLE
Support -l log level as argument

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh-cli#285]
How about adding a new argument to the CLI -l for BOSH_LOG_LEVEL?
Users who don't know about it have to search for it instead of using the CLI help.

**Comment by dpb587-pivotal** [comment]
I agree that it should be documented within the CLI help output.

Related... https://github.com/jessevdk/go-flags/issues/204

Tricky part is that our CLI creates some objects which rely on log configuration before go-flags parses the args/env.

**Comment by Kiemes** [comment]
I can't remove the label, but the Info about BOSH_LOG_LEVEL is still not visible in `bosh --help`. I would still like to see this. Thx
