### ISSUE TITLE
interpolate incorrectly modifies YML file

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/bosh-cli#289]
When my property name is 'y' or 'n'.   bosh2 CLI will change that to 'true' 'false' respectively.

sample.yml:

properties:
  test:
    n: yes
    y: no

Command:

bosh2 interpolate sample.yml --path /properties/test

false: true
true: false

We have some properties in our deployments called 'n' and this is causing us problems during deployments.

@qu1queee

**Comment by dpb587-pivotal** [comment]
Per the YAML spec, `n` and `y` are [boolean types](http://yaml.org/type/bool.html). If this was working with the old, ruby CLI it may have been due to improper parsing behavior. CLI is using an upstream library for YAML parsing, and since this is working per the spec, I don't think we'll try to work against it.

In the future you might consider avoiding using reserved YAML tokens for property names. For existing documents, you can try one of the following alternatives which results in string values...

```
$ cat sample.yml
properties:
  quote:
    "n": "yes"
    "y": "no"
  type:
    !!str n: !!str yes
    !!str y: !!str no
$ bosh int sample.yml
properties:
  quote:
    "n": "yes"
    "y": "no"
  type:
    "n": "yes"
    "y": "no"
```

**Comment by andrew-edgar** [comment]
OK so the problem is we are "encoding" the "n" with double quotes.  

The problem is if we download the manifest with bosh2 from bosh director the double quotes are not preserved and so if I download the manifest form bosh2 and then go to deploy it again using the bosh2 cli.  The "n" gets replaces with "false".

The download from bosh director needs to preserve the encoding.

**Comment by dpb587-pivotal** [comment]
Thanks for looking into it.

I see the following in Psych, director's YAML parsing, which seems unfortunate and wrong.

    ###
    # YAML spec says "y" and "Y" may be used as true, but Syck treats them
    # as literal strings
    def test_y
      assert_equal "y", Psych.load("--- y")
      assert_equal "Y", Psych.load("--- Y")
    end


    ###
    # YAML spec says "n" and "N" may be used as false, but Syck treats them
    # as literal strings
    def test_n
      assert_equal "n", Psych.load("--- n")
      assert_equal "N", Psych.load("--- N")

https://github.com/ruby/psych/blob/4039a811248de7b0b9ae9e4a97854f00ba985255/test/psych/test_boolean.rb#L21-L34

Not sure if that's something we can practically change. For now and for compatibility, at the very least... I'd recommend avoiding `n`/`y`/`Y`/`N`.

**Comment by andrew-edgar** [comment]
It's a little late now to make that change as it would require code changes by another team who are not willing to change it at the moment.

The basic requirement though is if I deploy using a manifest and then retrieve the manifest from the bosh director and deploy again.  there should be NO changes.   This seems like it is a bug in the boshcli or the bosh director to not preserve what is being provided.

Why does the retrieve of the manifest from the bosh director then escape the 'n' or 'y' instead of leaving it unescaped and causing the problem when redeploying?

**Comment by andrew-edgar** [comment]
Any feedback on this requirement?   

We need for manifests to not get changed when deploying and then retrieving the manifest back.

**Comment by cppforlife** [comment]
@andrew-edgar im not sure we can do much about go-yaml library following the yaml spec. it just happens to be that ruby has a bug in its yaml library. is there a reason you cannot change your manifest to avoid using these yaml shorthands?

**Comment by andrew-edgar** [comment]
@cppforlife we cannot change this.  this is not our team who provided the bosh release to us.  they have it in their spec to have a property named "n" which in fact makes sense in their context.

We are correctly escaping the value and deploys work.  The problem is if we get the manifest FROM the director with bosh2 manifest.  It comes back without the value escaped!  We deployed the value correctly escaped so when we retrieve the manifest back from the director it should not be changed

**Comment by andrew-edgar** [comment]
I would also point to this #150423538 as the last line definitely fits here ...

"bosh manifest should return the same content and order that the user passed to bosh deploy (ie don't save the sorted manifest)"

which in my case means when I do bosh manifest I should get back the "escaped" values rather than non-escaped which would solve this problem

**Comment by cppforlife** [comment]
@andrew-edgar ah, i see what you mean here. story entered: https://www.pivotaltracker.com/story/show/150869116

**Comment by andrew-edgar** [comment]
Is there any update on this?  We are still seeing this error.  Can you please tell us if and when this will be fixed?

**Comment by dpb587-pivotal** [comment]
The fix to ensure director keeps and returns a raw copy of the manifest was made in November, but it didn't make the most recent director release of 265. It should be available whenever the next major version, 266, is released.

**Comment by andrew-edgar** [comment]
This is still required.  Has this been resolved?  Can the bosh team comment if this did in fact make it into 266 and if this can be confirmed?  If this did make it into 266 it should have been closed by the bosh team
