### ISSUE TITLE
bosh delete-cloud-config

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#291]
So I just accidentally applied a cloud-config to a BOSH director that does not have one (and the cloud-config was for an entirely different CPI); but there is no `bosh delete-cloud-config` (nor `bosh undo-that-last-thing-I-did`) Is this a difficult feature to implement; or could we add it for future me who does this again?

Bonus question: how do I revert this?

**Comment by Kiemes** [comment]
@drnic you can upload an empty cloud config. Create an empty file and do ```bosh update-cloud-config <empty-file>```

You can also just ignore the cloud-config. If you keep deploying releases in manifest version 1, BOSH will ignore cloud-config for those deployments. You will see a warning when deploying ```Deprecation: Ignoring cloud config. Manifest contains 'networks' section.```

Also with [generic config](https://github.com/cloudfoundry/bosh-notes/blob/master/configs-api.md), deleting a config will be possible. So I guess we will not implement a `delete-cloud-config` anymore.

**Comment by drnic** [comment]
Thanks Tom.

________________________________
