### ISSUE TITLE
Creation of boshrelease fails with bosh2 cli

### ISSUE THREAD

**Issue by vinaybheri** [cloudfoundry/bosh-cli#292]
Hi,

The creation of a boshrelease required for our project works fine with bosh cli1 but fails in bosh cli2 command.

```shell
i336516:vcap@AWS:SF-AWS-DEVOPS:~/i336516/service-fabrik-boshrelease$ bosh2 --version
version 2.0.29-1f8ec43-2017-07-14T16:10:28Z

Succeeded
i336516:vcap@AWS:SF-AWS-DEVOPS:~/i336516/service-fabrik-boshrelease$ bosh2 create-release --force
Building a release from directory '/home/vcap/i336516/service-fabrik-boshrelease':
  - Constructing packages from directory:
      - Reading package from '/home/vcap/i336516/service-fabrik-boshrelease/packages/bosh-helpers':
          Collecting package files:
            Unmarshalling package spec:
              yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into []string
      - Reading package from '/home/vcap/i336516/service-fabrik-boshrelease/packages/docker':
          Collecting package files:
            Unmarshalling package spec:
              yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into []string
      - Reading package from '/home/vcap/i336516/service-fabrik-boshrelease/packages/golang':
          Collecting package files:
            Unmarshalling package spec:
              yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into []string
      - Expected to find package 'golang' since it's a dependency of package 'lvmvd'
      - Expected to find package 'golang' since it's a dependency of package 'swarm'
  - Constructing jobs from manifest:
      - Expected to find package 'bosh-helpers' since it's a dependency of job 'docker'
      - Expected to find package 'bosh-helpers' since it's a dependency of job 'service-fabrik-broker'
      - Expected to find package 'bosh-helpers' since it's a dependency of job 'service-fabrik-scheduler'
      - Expected to find package 'bosh-helpers' since it's a dependency of job 'swarm_manager'

Exit code 1
i336516:vcap@AWS:SF-AWS-DEVOPS:~/i336516/service-fabrik-boshrelease$ bosh --version
BOSH 1.3262.26.0
i336516:vcap@AWS:SF-AWS-DEVOPS:~/i336516/service-fabrik-boshrelease$ bosh create release --force
Syncing blobs...
..
....
...
Release name: service-fabrik
Release version: 2.9.0+dev.1
Release manifest: /home/vcap/i336516/service-fabrik-boshrelease/dev_releases/service-fabrik/service-fabrik-2.9.0+dev.1.yml


```

**Comment by dpb587-pivotal** [comment]
Hi - sounds like you might need to switch the `dependencies` in `bosh-helpers`/`docker`/`golang` to be an array instead of a hash (even if they're empty).

**Comment by vinaybheri** [comment]
Thanks @dpb587-pivotal,
It helped us.

We replaced curly braces '{}' with square brackets '[]' while specifying dependencies in spec files.

**Comment by vinaybheri** [comment]
@dpb587-pivotal ,

But now, we are facing issue with downloading of blobs.

when we run bosh create-release --force (bosh2), we get this error. But it works fine with bosh cli v1
```shell
Getting blob '67e8628d-c7a4-4182-8fdd-4cddd60bcaa0' for path 'apt/lvm2/libdevmapper-event1.02.1_2:1.02.77-6ubuntu2_amd64.deb':
    Getting blob from inner blobstore:
      Getting blob from inner blobstore:
        NoSuchKey: The specified key does not exist.
        status code: 404, request id: A575D1195D853E72, host id: dWE4wyBKxFLAdg/MTWOmGLlBgNecK0uNOA28UtzECRLaLA0gHxUUkeVBtpqDzYsGSTV8pJ7+sO4=

```

**Comment by jochenehret** [comment]
We should add that we use folders to organize our buckets. So in our `config/final.yml`, we have this structure:
```
final_name: ...
blobstore:
  provider: s3
  options:
    bucket_name: ...
    folder: ...
    secret_access_key: ...
    access_key_id: ...
```
Is the "folder" parameter still evaluated?

**Comment by jochenehret** [comment]
We have found a workaround: Appending the folder name to the bucket_name plus specifying the signature version works:
```
---
final_name: <redacted>
blobstore:
  provider: s3
  options:
    bucket_name: <bucket_name>/<folder>
    signature_version: "2"
    secret_access_key: <redacted>
    access_key_id: <redacted>
```
The signature version should be selected automatically, depending on the region. Can you please check?

**Comment by vinaybheri** [comment]
After this workaround, bosh create-release is working with both bosh1 and bosh2 cli commands.

Thanks @jochenehret

**Comment by tyyko** [comment]
@dpb587-pivotal Can you please confirm if this is the official solution to migrate from the ruby bosh_cli to the new one:

merging in the same line `bucket_name` and `folder` and adding `signature_version: "2"`

I think it should be documented and announced somewhere as this breaks all 'create release' scripts/automations of everyone who has S3 as release blobstore and used the old ruby cli

**Comment by dpb587-pivotal** [comment]
No, I would not recommend collapsing folder into the `bucket_name` property. This may happen to work now, but there may be additional validation in the future to ensure the value is only a bucket name (potentially mandated for underlying API changes).

Currently, the proper solution is to use separate buckets because, unfortunately, the `folder` option was dropped with new [s3cli](https://github.com/cloudfoundry/bosh-s3cli).

**Comment by tyyko** [comment]
thanks for the clarification, we will need some refactoring then.

**Comment by vinaybheri** [comment]
Reopening this issue.

As the solution Appending bucket name and folder name in one parameter worked only for bosh dev create release

```shell
bosh create-release --force
```

But didn't work for final create release

```shell
bosh create-release --final

Error:
Creating blob for path '/home/vcap/.bosh/cache/b9feed7703893d21e79679931120af853bcaa77e':
  Creating blob in inner blobstore:
    Generating blobstore ID:
      the client operates in read only mode. Change 'credentials_source' parameter value 

Exit code 1
```

So, finally we created final release using bosh cli v1 (reverting appending of folder name with bucket name).

**Comment by dpb587-pivotal** [comment]
Related Story: https://www.pivotaltracker.com/story/show/150908130

**Comment by giner** [comment]
We are in transition from ruby-bosh to go-bosh and this issue makes the moving process inconvenient. Every time we need to something using one bosh or another we have to change `config/final.yml`.

**Comment by dpb587-pivotal** [comment]
Story: https://www.pivotaltracker.com/story/show/152119929

**Comment by giner** [comment]
Any updates on this?

**Comment by dpb587-pivotal** [comment]
It looks the s3 dependency was bumped as a side-effect of some [other changes](https://github.com/cloudfoundry/bosh-cli/commit/98d64c208ef1f25e98c224eb374aced89f64b080), so [v2.0.46+](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.46) should have support for `folder_name`.

Want to give the [most recent version](http://bosh.io/docs/cli-v2#install) a try and see if it works for you?
