### ISSUE TITLE
 cli doesn't play well with http proxy

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/bosh-cli#297]
Following the guide at http://bosh.io/docs/cli-tunnel.html I want to tunnel to a jump box for both BOSH traffic and http traffic.

Main issue is, bosh2 cli only seems to work well if **only** `BOSH_ALL_PROXY=socks5://localhost:5000` is set. 

When I set a generic `http_proxy=socks5://localhost:5000` and try to list VMs in a deployment I get the following error:

```
bosh2 -e https://192.168.1.11:25555 --ca-cert <mycert> --client admin --client-secret **** deployments
Fetching info:
  Performing request GET 'https://192.168.1.11:25555/info':
    Performing GET request:
      Retry: Get https://192.168.1.11:25555/info: http: error connecting to proxy http://socks5://localhost:5000: proxy: failed to parse port number:

Exit code 1
```

Mind you, when I do a regular `curl -k https://192.168.1.11:25555/info` it works perfectly fine over the proxy.

My suspicion is a bug in the underlying http client which might do a hard assumption on http as a proxy protocol instead of socks5.

Use case: I wanted to query the IPs from a bosh deployment's VM and then perform some test against it. So I need to proxy both the bosh director traffic and regular http traffic to talk to the VM deployed by bosh.

**Comment by domdom82** [comment]
Did some more investigation: I think I might have tracked down the issue to a basic go problem in `net/http/transport.go`

```
func ProxyFromEnvironment
(...)

proxyURL, err := url.Parse(proxy)
	if err != nil || !strings.HasPrefix(proxyURL.Scheme, "http") {
		// proxy was bogus. Try prepending "http://" to it and
		// see if that parses correctly. If not, we fall
		// through and complain about the original one.
		if proxyURL, err := url.Parse("http://" + proxy); err == nil {
			return proxyURL, nil
		}
	}
```

However I think this might become a non-issue as I found a commit in go that seems to fix it: https://github.com/golang/go/commit/36f55a8b6125c9ae951487a0ad074b5c991f7b92

Should be included in golang 1.9rc2 - will test it.

**Comment by domdom82** [comment]
Another update: I built bosh-cli with go1.9rc2 and verified that the fix works. I can now set the `http_proxy=socks5://localhost:5000` variable and do a `bosh2 -e https://192.168.1.11:25555 --ca-cert <mycert> --client admin --client-secret **** deployments`

However, now the `BOSH_ALL_PROXY` env variable **must not be set** or else I get this:

```
Fetching info:
  Performing request GET 'https://192.168.1.11:25555/info':
    Performing GET request:
      Retry: Get https://192.168.1.11:25555/info: proxyconnect tcp: proxy: failed to read connect reply from SOCKS5 proxy at localhost:5000: EOF

Exit code 1
```

So it only works if just the regular `http_proxy` variable **or** the `BOSH_ALL_PROXY` variable is set, but not **both**. So I still consider this a bug.

**Comment by domdom82** [comment]
@istvan.zoltan.ballok FYI

**Comment by ramonskie** [comment]
@cppforlife any idea's if this is still up for discussion?
as this bug still persists after a year
