### ISSUE TITLE
Debugging + Logging should not print to stdout

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-cli#301]
Right now `BOSH_LOG_LEVEL=debug bosh cloud-config` (and many other bosh commands) send the debug logging to stdout, alongside the command output. It would be very nice if this could split into two streams, and use stderr for error/debug logging, and stdout for the output of the command, so that `BOSH_LOG_LEVEL=debug bosh cloud-config | yaml2json | jq this.that.theother` works the same as `bosh cloud-config | yaml2json | jq this.that.theother`

**Comment by dpb587-pivotal** [comment]
+1

**Comment by tylerschultz** [comment]
Change will be in upcoming version of bosh-cli:

https://github.com/cloudfoundry/bosh-cli/commit/e73a765b8541120c9d248e7fe62272f7128e440f
