### ISSUE TITLE
Faster feedback loop for mistyped cli flags

### ISSUE THREAD

**Issue by ctaymor** [cloudfoundry/bosh-cli#306]
When deploying with a vars store, we accidentally typed with only one dash, like so `-vars-store`. This led to some of our vms failing to become healthy, because they didn't have the variables we needed. However, this is a very slow feedback loop to realize you made a typo.

It would be really helpful to add a feature to the CLI to reduce that feedback loop.

A few different ways I could see such a feature working:
- Print what flags were unrecognized and will be ignored
- Check for flags which are close to the specified flag, (for instance common mispellings or the wrong number of dashes) and ask the operator if they intended to use the correct flag instead.

This would reduce the feedback loop for typos from 20+ minutes to upwards of an hour, down to just a few seconds.
- Caroline && @swetharepakula

**Comment by cppforlife** [comment]
as of bosh release 263 director checks for all ((...)) before starting to deploy.

**Comment by ctaymor** [comment]
:+1: We're on 262. We'll roll forward.
