### ISSUE TITLE
Allow operator to specify job order via ops file

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-cli#317]
## Use Case

We would like to deploy an HA Proxy instance group at the start of our deployment as other jobs depend on it. However, ops-files only allow instance groups to be appended to the end of the deployment. Could a feature be added to prepend to an array?

A slightly different use case would be specifying a given index at which to insert the instance group. For example, the bits-service ops file currently requires a two stage deploy as the bit service VM must be deployed after the WebDav VM but before the CC VM.

## Workaround

Rel-Int currently has [this hack](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/community/use-haproxy.yml) that replaces the smoke-test job with the HA Proxy job to make it appear earlier in the list.

Our current process for deploying the bits-service is to deploy the bits-service in one deploy, then configure CC to use the bits-service in a second deploy.

**Comment by cppforlife** [comment]
related: https://github.com/cppforlife/go-patch/issues/11

**Comment by cppforlife** [comment]
v2.0.42 has :before/:after syntax. see syntax details in http://bosh.io/docs/cli-ops-files
