### ISSUE TITLE
Feature request: fast failure when a template cannot be filled

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/bosh-cli#32]
When using `--var-files`, we accidentally forgot to add a variable to our file.  We should have added the line `some_variable_name: correct-value` in our variable file, but missed it.

The manifest got deployed with a property value set to the literal string `((some_variable_name))`, and we had to look through logs to discover that.  This was surprising.

It would be great if the `deploy` command gave us fast feedback that our template couldn't be completely filled in, because a variable wasn't set.

cc: @markstgodard

**Comment by cppforlife** [comment]
@rosenhouse we have `build-manifest` command with `--var-errs` flag that will force CLI to list any missing variables. the reason why `deploy` cmd doesnt do it is that we are planning for the Director to do interpolation as well, so soon enough it will raise errors. In summary: two levels of interpolation, one in CLI, and one is in the Director and the Director part isn't complete yet.

**Comment by rosenhouse** [comment]
makes sense, thanks for the quick response!
