### ISSUE TITLE
repack-stemcell --format shouldn't be required flag

### ISSUE THREAD

**Issue by cdutra** [cloudfoundry/bosh-cli#321]
BOSH cli version 2.0.38+ introduced a bug that makes the flag `--format` required.
Older versions of stemcells do not have `stemcell_formats` field in stemcell.MF.

Example:
`bosh repack-stemcell ...` causes the following issue for stemcell bosh-aws-xen-ubuntu-trusty-go_agent/3312.38 when uploading the repacked stemcell:
```
Error: stemcell_formats of this stemcell are not supported by available cpis
```

bug introduced on PR #309

**Comment by Kiemes** [comment]
We are on it https://www.pivotaltracker.com/story/show/144851625.
Waiting for bosh-utils PR to be merged to fix this issue.

**Comment by cdutra** [comment]
@cppforlife Could we merge the PR, our AWS pipelines are still using cli version 38 to avoid this issue. Thanks!

**Comment by cppforlife** [comment]
@Kiemes @ansd why do we need to use property object instead of a normal map? i want to remove Property entirely since it doesnt appear to bring much benefit.

**Comment by loewenstein** [comment]
@cppforlife we had seen the duplication between https://github.com/cloudfoundry/bosh-cli/blob/master/stemcell/reader.go and https://github.com/cloudfoundry/bosh-cli/blob/master/stemcell/stemcell.go#L121-L129 and were going to remove it in favor of the public datastructure.

**Comment by voelzmo** [comment]
I'm not sure what the state is now. Did we agree on the refactoring done in https://github.com/KaiHofstetter/bosh-cli/commit/334d6c065aabd84a49033c50d31d079d67184490 or should we do it differently, @cppforlife ?

**Comment by ansd** [comment]
Solved by story https://www.pivotaltracker.com/n/projects/1456570
