### ISSUE TITLE
Automatically create a socks5 proxy for environments with a jumpbox

### ISSUE THREAD

**Issue by genevieve** [cloudfoundry/bosh-cli#324]
`bbl` 5.0 is shipping soon and will stand up environments with a jumpbox.

In order to talk to the bosh director, users can do the following:

```
eval "$(bbl print-env)"
```

`bbl print-env` picks a port for the tunnel, and outputs these two lines (in addition to the other stuff necessary to target a bosh director):

```
export BOSH_ALL_PROXY=socks5://localhost:$port
ssh -f -N -o StrictHostKeyChecking=no -D $port jumpbox@$jumpbox-url -i $jumpbox-key
```

In `bbl`, we do this automatically already, and we recently [created a PR](https://github.com/cloudfoundry/bosh-deployment-resource/pull/29) to do this in the `bosh-deployment-resource`.

In the PR, these two properties are set to open a tunnel when a bosh command is run: `JumpboxSSHKey` and `JumpboxURL`.  (Check out the PR for more details on how that proxy is started.)

It'd be cool if the bosh-cli would accept these two flags/environment variables natively as an alternative to setting `BOSH_ALL_PROXY` and automatically open a tunnel when a command is run.

**Comment by evanfarrar** [comment]
Would you be open to this as a PR? we have already done this for two Go repos, and are getting pretty practiced at setting up a proxy. We also plan to make a similar functionality in CredHub if they'll allow it.

**Comment by dsabeti** [comment]
+1

**Comment by cppforlife** [comment]
@genevievelesperance @evanfarrar im not opposed to it. how do you all feel about extending https://github.com/cloudfoundry/bosh-utils/blob/master/httpclient/socksify.go#L15 to handle 

`export BOSH_ALL_PROXY=ssh+socks5://localhost:5000?private-key=/path`

or some format like that in addition to simple socks5://

**Comment by evanfarrar** [comment]
I'm a little confused. It would also the IP address of the jumpbox? And the user?

export BOSH_ALL_PROXY=ssh+socks5://jumpbox@57.12.44.87.19:5000?private-key=/path

**Comment by cppforlife** [comment]
yup, something like that

**Comment by evanfarrar** [comment]
I'm fine with it if you're fine with it. My team will talk it over in IPM Monday and make the PR. It doesn't seem exactly intuitive how to add/omit things into this syntax, but I haven't really met a person who understands exactly what happens when they `bosh ssh` either, so I don't really care about the rhythm of this rain dance.

**Comment by genevievelesperance** [comment]
@cppforlife Do you want `socksify` to return the socks5-proxy dialer when `ssh+socks5` is passed, then the bosh-cli start the proxy with the `JumpboxSSHKey` and `JumpboxURL` (since socksify does not have access to those parameters)?

**Comment by genevieve** [comment]
Think we can close this ...
