### ISSUE TITLE
Bosh errand writes all output to stdout

### ISSUE THREAD

**Issue by poy** [cloudfoundry/bosh-cli#325]
An errand script writes data to both stderr and stdout. However, the bosh-cli takes all the output and puts everything on stdout. 

It would be helpful to have the stderr respected and written to stderr.

**Comment by cppforlife** [comment]
what is the use case to redirecting this to stderr?

the reason why it's currently like this is because cli's stderr is for
error during operation of cli. errand's stderr is just plain part of errand
api response from the director which cli shows successfully.

**Comment by apoydence** [comment]
Normal command line uses would be simpler is the cli followed the model curl does:

Human readable information comes out Stderr and information you might want to grep (or any other tool) comes out Stdout.

The errand output is an obvious place for this.
