### ISSUE TITLE
Have we considered using ssh agent to supply the ssh key for `bosh ssh`?

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/bosh-cli#327]
Currently we write keys to disk in the process of running `bosh ssh` e.g. locations like`/Users/efarrar/.bosh/tmp/ssh-priv-key229428263`.

I know that this SSH key is deleted on exit, and that the acceptance of the key by the job VM is short-lived, but it is still on disk and valid for a period of time. BBL does a similar thing, and I've been searching for a way to avoid writing SSH keys to disk.

By setting IdentityAgent to something started by the CLI, you could run an SSH agent entirely implemented in Go, that would supply the keys directly from memory.

https://godoc.org/golang.org/x/crypto/ssh/agent

**Comment by cppforlife** [comment]
it's possible however the challenge is with already loaded keys in an existing agent that may be necessary for gateway host. there is probably some way to forward from one agent to another, but that's a bit more complex. cc @dpb587-pivotal

**Comment by dpb587-pivotal** [comment]
I've previously done some work with the crypto/ssh/agent package which provides keys. Generally and in theory, the `bbl eval-thing` which sets `BOSH_*` stuff could set+fork its own implementation of an SSH agent (like `bbl jumpbox-agent`?) which simply prepends the `bbl`-managed jumpbox ssh key to the user's existing `SSH_AUTH_SOCK`. Maybe not directly related to your question.
