### ISSUE TITLE
can the director client library be in a separate repo than bosh-cli codebase

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh-cli#329]
I want to use the bosh director client library in my code and it's unfortunate that I have to pull down all the dependencies for the cli.

If I use `dep` to pull down `bosh-cli` as a dependency, it will not copy the inner `vendor` directory, so I end up having to deal with issues like this:

```
# github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/vendor/github.com/cloudfoundry/bosh-cli/ui
vendor/github.com/cloudfoundry/bosh-cli/ui/file_reporter.go:32:42: cannot use r.buildBar(size) (type *pb.ProgressBar) as type io.Writer in argument to io.MultiWriter:
	*pb.ProgressBar does not implement io.Writer (missing Write method)
		have pb.write()
		want Write([]byte) (int, error)
vendor/github.com/cloudfoundry/bosh-cli/ui/file_reporter.go:36:9: undefined: pb.New
vendor/github.com/cloudfoundry/bosh-cli/ui/file_reporter.go:44:15: undefined: pb.U_BYTES
```

This requires me to have to manually lock dependencies to the versions that the `bosh-cli` wants, which means that I constantly have to make sure my dependencies match what the `bosh-cli` mainline wants.

It would be awesome if the bosh client library had very minimal dependencies so that app developers who would like to programmatically integrate with bosh don't need to pull down the universe.

**Comment by kieron-pivotal** [comment]
We've just come across this problem as well. Would it be a solution to include 
```
[[constraint]]
name = "github.com/cheggaaa/pb"
version = "=1.0.18"
```
in Gopkg.toml so that it resolves correctly as a transitive dependency?

**Comment by jfmyers9** [comment]
If anyone is looking for an example on how to successfully do this, [this is a great example](https://github.com/cloudfoundry/bosh-deployment-resource/blob/24b8989c59e846b0b3afd2816469ea39afbc868f/Gopkg.toml).

Also, since this is the preferred library for programatic access to the bosh director, are there any plans to improve this user experience any time soon?

**Comment by jfmyers9** [comment]
With recent changes, `go mod` and other vendoring tools should be able to successfully vendor the director library. Due to this, I'm going to close this issue. Please feel free to open a new issue if you are still having problems.
