### ISSUE TITLE
Feature request: print error messages to stderr

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/bosh-cli#33]
I am missing some vars required by my manifest, so I see this error
```bash
bosh-cli build-manifest --var-files=deployment-env-vars.yml \
   --var-errs ~/workspace/cf-deployment/cf-deployment.yml

Expected to find variables: etcd_require_ssl, network_policy_server_uri

Exit code 1
```

Except this was running in a script, with the output piped to a file:
```bash
bosh-cli build-manifest --var-files=deployment-env-vars.yml \
   --var-errs ~/workspace/cf-deployment/cf-deployment.yml \
   > /tmp/generated-manifest


```
The script exited with code 1, but I didn't see any error output.  It was difficult to diagnose the problem.

If error messages were printed to stderr, then they would appear in the console output, even when stdout is redirected to a file.

cc: @mcwumbly

**Comment by cppforlife** [comment]
@rosenhouse looks like non_tty_ui.go (https://github.com/cloudfoundry/bosh-cli/blob/master/ui/non_tty_ui.go#L15) kicked in and didn't print any decorative output (including errors).

**Comment by cppforlife** [comment]
In the next version.
