### ISSUE TITLE
Interpolation breaks with % characters in value

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry/bosh-cli#330]
I had a vCenter password in a BOSH variable that looks something like **"hello%[==there"**.  

Because BOSH CLI interpolation uses golang Sprintf, this value gets interpolated as **"hello%!=(BADINDEX)=there"**.   Workaround is to escape the % with %% in the value.

**Comment by cppforlife** [comment]
interesting, sounds like we should fix it.

**Comment by cppforlife** [comment]
```
 $ cat /tmp/lol
items:
  lol: ((lol))

 $ bosh int /tmp/lol -v lol=foo%foo
items:
  lol: foo%foo

Succeeded
```

**Comment by svrc-pivotal** [comment]
This was as part of kubo and ODB let me see if I can replicate in an easier way

**Comment by svrc-pivotal** [comment]
Seems this is likely an ODB service broker issue in how it handles Ops files / interopolation.  I'll close.
