### ISSUE TITLE
Feature Request: Allow manifests to specify minimum director and CLI versions

### ISSUE THREAD

**Issue by dsabeti** [cloudfoundry/bosh-cli#335]
As part of [cf-deployment](https://github.com/cloudfoundry/cf-deployment), we'd like to be able to encode in the manifest the minimum compatible versions of the BOSH Director and the CLI.

In the past, we've had to build out [compatibility matrices](https://github.com/cloudfoundry/diego-cf-compatibility/blob/master/compatibility-v11.csv), or leave notes in release notes of cf-release. We really like the pattern that has emerged from cf-deployment, where the manifest itself contains the information about which releases and stemcells are considered compatible. We'd like to extend that UX to BOSH compatibility as well.

This is especially valuable because we want to stay on top of integrating against new BOSH features -- both on the Director and the CLI. For example, our [compiled-releases ops-file](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-compiled-releases.yml) depends on BOSH CLI [2.0.30](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.30), but there's not an easy place to specify that. Just a few weeks later, cf-deployment started to depend on CLI [2.0.42](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.42) to use the `:before/:after` syntax in ops-files.

### Proposal
I can specify something like this in the manifest:
```
---
name: cf
minimum_bosh_director: 263.3.0
minimum_bosh_cli: 2.0.42
instance_groups:
...
```

And see the following behaviors:
- If the BOSH CLI version is less that `2.0.42`, the BOSH CLI should return some error, asking the user to upgrade their CLI.
- If the targeted BOSH Director is less than `263.3.0`, the BOSH CLI (or BOSH director, perhaps) should return an error, asking the user to upgrade their director.
- Otherwise, the deployment should proceed as planned.

**Comment by evanfarrar** [comment]
Definitely. I would like to remember our friends who don't have directors yet and suggest following additional behavior
* If I run `bosh create-env bosh.yml` and the `minimum_bosh_cli specified in `bosh.yml` is higher than `bosh version` then the cli should return some error, asking the user to upgrade their CLI.
* director version is ignored by create-env
