### ISSUE TITLE
bosh ssh and partial match

### ISSUE THREAD

**Issue by giner** [cloudfoundry/bosh-cli#336]
`bosh ssh` should try to do partial match, something like `bosh ssh myjob/2ad9`. This would allow operators to cut instance ids for monitoring dashboard (such as Grafana) while keeping it useful for operations.

**Comment by cppforlife** [comment]
commands to follow: ssh, stop, start, recreate, deploy, run-errand

**Comment by oliverralbertini** [comment]
@tjvman, a couple more thoughts on this: it is still possible to have a collision (or ambiguity) when more than one uuid strings begin with the same 4 characters. Also, our solution from yesterday doesn't account for uuids that begin with 4 numerical characters. But I don't know how likely it is to encounter these scenarios--probably not likely.

**Comment by cppforlife** [comment]
i think if we have more than one result we should raise an error since it's ambigious. prolly worth checking again indexes as well if it's all numeric.

**Comment by dpb587-pivotal** [comment]
Pivotal Tracker: [Story 152692984](https://www.pivotaltracker.com/story/show/152692984)
