### ISSUE TITLE
bosh v2 cli seems to break blobs.yml for v1 cli users

### ISSUE THREAD

**Issue by spikymonkey** [cloudfoundry/bosh-cli#337]
Hi Bosh,

We hit an interesting issue when adding blobs to our release yesterday. We're at the start of a v2 cli migration across the team - some developers have v2 installed whilst others are still using v1, and as yet our CI is still using v1.

A developer with v2 successfully added a new blob to the release, and committed the `blobs.yml` update to source control. Since this was the first time v2 had been used to update `blobs.yml`, we noted that the keys within the yaml maps in that file had been re-ordered. We didn't think should matter to anything, so shrugged and continued.

Our CI job then ran, which uses v1 to update two blobs in the release to new versions (artifacts generated in the previous build step).

This resulted in `blobs.yml` being corrupted and `bosh add blob` failing:
```
Adding blob /tmp/build/660fa31b/artifacts/spring-cloud-service-broker-1.5.0-build.85.jar to spring-cloud-service-broker
Incorrect YAML structure in '/tmp/build/660fa31b/scs-broker-release/config/blobs.yml': Found duplicate key 'object_id'
```

So it seems that v1 is not able to modify a `blobs.yml` which has already been processed by v2. To fix this, we had to revert the commit, re-add the new blob with bosh cli v1, and then re-commit.

Clearly this wouldn't be a problem if we were using v2 across the board, but it does mean that it's tricky to migrate over to v2 in a non big-bang style, which is hard to synchronise across large teams and multiple CI pipelines etc. We wondered if, to help people out with migration, either the bosh v1 cli could be updated to be agnostic to the `blobs.yml` key ordering, or v2 could be updated to generate `blobs.yml` with the same key ordering as v1?

**Comment by cppforlife** [comment]
can include what that problematic blobs.yml looks like?

**Comment by spikymonkey** [comment]
Sorry @cppforlife, this turns out to be a problem on our side. It turns out we do some pre-processing of blobs.yml - removing old blobs - before using bosh v1 to add new ones. That removal step breaks with the bosh v2 key ordering, and then hands bosh v1 a broken file to work on.

When we jump to bosh v2 across the board we'll replace that broken script with `bosh remove-blob`. Sorry for hassling you with this one!
