### ISSUE TITLE
bosh 'interpolate' prints 'Succeeded' to stdout

### ISSUE THREAD

**Issue by rerooted** [cloudfoundry/bosh-cli#338]
When running `bosh interpolate` a message is printed after the interpolation succeeds.  This is printed to stdout.  This means that before using the output from `bosh interpolate` the 'Succeeded' message needs to be removed.

```
$ CF_BOSH_director_az1_reserved_ip6=10.0.0.6/24 Bosh-static-ips.yml --vars-env=CF_BOSH
bosh_lite_private_ip: 10.0.0.6/24

Succeeded
```

See https://github.com/cloudfoundry/bosh-cli/blob/47ea06453290186de2610150498d3901d16c4131/main.go#L129

It would be nice if this 'Succeeded' message could be printed to stderr.

**Comment by cppforlife** [comment]
its not printed when output is redirected (no tty) so it should be fine.

**Comment by rerooted** [comment]
You are right, redirecting elsewhere causes it not to be printed.

Apologies for the noise.
