### ISSUE TITLE
Feature request: deployment name can be inferred

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/bosh-cli#339]
I was perusing http://ultimateguidetobosh.com/targeting-bosh-envs/
 and wondered: why is this not the case?

If the full path of my bosh deployment manifest matches */X-deployment/X.yml
And the manifest has a deployment name X
And BOSH_DEPLOYMENT is not set
And -d is not supplied
then the deployment name is assumed to be X

**Comment by cppforlife** [comment]
we are actually planning to remove `name` key from the manifest similar to how pipeline configuration files dont have pipeline name.

**Comment by evanfarrar** [comment]
OK, fair, we're only suggesting a decent default deployment name twice, not three times. But it still stands to reason like this:

If the full path of my bosh deployment manifest matches */X-deployment/X.yml
And BOSH_DEPLOYMENT is not set
And -d is not supplied
then the deployment name is assumed to be X

**Comment by evanfarrar** [comment]
I definitely see how we wouldn't want someone to accidentally target the wrong deployment, that they should explicitly select one. But also, docs. Is there any way we could combat the problem of mistargeting more directly, rather than always requiring the user to specify?

**Comment by cppforlife** [comment]
hmm, it probably makes sense to have a generic name for Y in */X-deployment/Y.yml like `default.yml` or `basic.yml`. @dsabeti what do you think?

**Comment by dsabeti** [comment]
Oh wow, so like `bosh-deployment/default.yml` or `cf-deployment/basic.yml`? It's a little jarring, but I'm warming up to it. It could be nice for cf-deployment because we could maybe introduce other manifests: 
- `cf-deployment/minimal.yml` for a small footprint cf
- `cf-deployment/control-plane.yml`, `cf-deployment/cells.yml`, and `cf-deployment/routers.yml` for split deployments.

**Comment by evanfarrar** [comment]
So if I understand correctly, you are suggesting we could omit the deployment manifest instead of the deployment name?
```
git clone cf-deployment && cd cf-deployment && bosh -d cf deploy
```
would deploy basic.yml, vs where I think I was heading with my earlier suggestion to allow this:
```
git clone cf-deployment && cd cf-deployment && bosh deploy cf.yml
```
And then, we haven't backtracked on intentional targeting, but we have still eased the number of arguments that a new bosh user has to understand while they are bootstrapping?

**Comment by cppforlife** [comment]
i meant:

```
git clone cf-deployment && bosh -d cf deploy cf-deployment/basic.yml
```

**Comment by drnic** [comment]
As an aside, I did rewrite the section on targetting BOSH environments/deployments. As for all the content, I might rewrite it again in future.

https://ultimateguidetobosh.com/targeting-bosh-envs/
