### ISSUE TITLE
bosh start instance missing confirmation message

### ISSUE THREAD

**Issue by shubhaat** [cloudfoundry/bosh-cli#342]
```
Shubhas-MacBook-Pro-2:deployments-routing sanjurtupil$ bosh2 -e superman -d  cf start router/3b51bf1e-3f3e-480d-b5b4-c39552dad3bd
Using environment 'https://35.188.221.176:25555' as client 'admin'

Using deployment 'cf'

Continue? [yN]: y

Task 1906

Task 1906 | 21:21:02 | Preparing deployment: Preparing deployment (00:00:02)
```

I would have expected to see a message like `Starting router instance 3b51bf1e-3f3e-480d-b5b4-c39552dad3bd. Continue?`

**Comment by dpb587-pivotal** [comment]
In this case, the command you used is requesting the start of a specific instance, so the confirmation at the start of the command is implied. I think that covers your use case.

Are you suggesting that if you ran `bosh start router` you would want it to interactively prompt right before it started every instance, one/many at a time? Currently the start commands are executed as a single task, so there's no way to interact with a task once it has started (aside from canceling it altogether).

An alternative if you were wanting to interactively run the command per instance would be to use `xargs` - something like `bosh instances --column=name | grep router/ | xargs bosh start`.
