### ISSUE TITLE
bosh ssh non-interactive and control sockets don't play well

### ISSUE THREAD

**Issue by hphde** [cloudfoundry/bosh-cli#345]
When using eg `ControlMaster auto` (reusable ssh sessions) on all hosts `Host *`, bosh shows an error:
`process_mux_new_session: tcgetattr: Inappropriate ioctl for device`
This behavior is due to the nature that ssh wants to keep a control session running even after it got disconnected but bosh expects ssh to end.

Two workarounds I found:

a) Try to exclude IP addresses from the environment in the users ssh config before `Host *`
```
# Don't use control sockets for IP addresses (simplified match)
Host *.*.???.* *.*.??.* *.*.?.*
  ControlMaster no
```
Of course you could have the IP addresses in your match like `192.168.*.*` but if you don't know them for whatever reason above may be appropriate.

b) Pass in a ssh option for bosh
```
bosh -e vbox -d cf ssh --opts " -o ControlMaster=false" uaa/0 -c 'ls -l /'
```

I believe it should be standard for the cmdOpts in https://github.com/cloudfoundry/bosh-cli/blob/master/ssh/session.go since this ssh sessions will never be reused

Option b) doesn't work with scp since that doesn't accept options.

**Comment by cppforlife** [comment]
> Option b) doesn't work with scp since that doesn't accept options.

you mean scp command in bosh doesn accept `--opts`, not that scp doesnt respect `ControlMaster=false`?

cc @evanfarrar @cunnie @coreyti

**Comment by hphde** [comment]
At least not when I opened that issue
