### ISSUE TITLE
support https_proxy for socks5

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#349]
I'm sorry if I'm missing something, I'm new to socks5 proxies.

Since go1.9 has native `export https_proxy=socks5://localhost:9999` support, could we move to using that (for consistency with other CLIs) rather than an explicitly new `$BOSH_ALL_PROXY` env var?

https://github.com/golang/go/commit/36f55a8b6125c9ae951487a0ad074b5c991f7b92

**Comment by cppforlife** [comment]
the reason why BOSH_ALL_PROXY was picked is to avoid accidentally proxying all your other software (git, etc) through your jumpbox.

**Comment by cppforlife** [comment]
when eventually cli is built with go 1.9 it will just work i guess but BOSH_ALL_PROXY will continue to exist.

**Comment by drnic** [comment]
FYI (and anyone googling errors), currently if `https_proxy` is set and `BOSH_ALL_PROXY` is unset, `bosh` looks to slap `http://` on the front of it:

```
export https_proxy=socks5://localhost:9999
unset BOSH_ALL_PROXY
$ bosh env
Fetching info:
  Performing request GET 'https://10.10.1.4:25555/info':
    Performing GET request:
      Retry: Get https://10.10.1.4:25555/info: http: error connecting to proxy http://socks5://localhost:9999: dial tcp: lookup socks5 on 8.8.4.4:53: no such host
```

**Comment by drnic** [comment]
Actually its worse than that, if `BOSH_ALL_PROXY` AND `https_proxy` is set, then `bosh` will ignore `BOSH_ALL_PROXY` and misuse `https_proxy`
