### ISSUE TITLE
create-release and finalize-release should complain when config/private.yml is missing

### ISSUE THREAD

**Issue by tylerschultz** [cloudfoundry/bosh-cli#352]
We were incorrectly supplying our `config/private.yml` and received errors that lead us to believe our final.yml or private.yml was incorrectly formed. 
```
Creating blob in inner blobstore:
    Generating blobstore ID:
      the client operates in read only mode. Change 'credentials_source' parameter value 
```
It would be helpful if the cli noted that the file is not present when it's expected.

**Comment by chinangela** [comment]
+1 -- Just ran into this issue was well. Didn't realize I needed to move where my `private.yml` was, as I do this infrequently.

**Comment by ameowlia** [comment]
Just ran into this issue, too!

**Comment by tylerschultz** [comment]
@mfine30 friendly bump

**Comment by mfine30** [comment]
Thanks gang. Closing/re-opening to trigger a tracker story

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty

**Comment by ameowlia** [comment]
I still care! @tylerschultz can you reopen?

**Comment by ameowlia** [comment]
Thanks @aashah!
