### ISSUE TITLE
Support for upload-release creating a dev release?

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh-cli#353]
During development, I often find myself running `bosh create-release && bosh upload-release`. Given that `create` can be used as `version` in a deployment manifest with a local directory, I think it would be helpful if `upload-release` could support that, too.

    bosh upload-release --version=create

Currently it errors saying `releases/{{name}}/{{name}}-create.yml: no such file or directory`.

**Comment by drnic** [comment]
Thanks to deployment manifests including `url` I now only use `upload-release` after a `create-release`No think. A `—version=create` might be handy.
