### ISSUE TITLE
resurrect all vms simultaneously please?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#356]
In 2013 at PlatformCF https://www.youtube.com/watch?v=RV-QPkPsXs4 I demonstrated BOSH ability to resurrect VMs, but bemoaned that it brought them all up one at a time - soo slow. Its 2017 and its still only resurrects vms one at a time.

Is this deliberate/is there a benefit to this?

If I choose `2: Recreate VM without waiting for processes to start` for every VM, could we please move to recreating all the vms simultaneously (up to the bosh thread limit, etc)?

Resurrecting them all simultaneously has to be better than the current method of randomly choosing vms to resurrect even if they have well defined links/dependencies to other vms.

**Comment by voelzmo** [comment]
+1
resurrection should just follow the regular `bosh deploy` flow, thus doing everything in parallel that can be done, according to your manifest ordering and `update` section specifications.
