### ISSUE TITLE
Could bosh set vm metadata by cli?

### ISSUE THREAD

**Issue by EdwardStudy** [cloudfoundry/bosh-cli#357]
What methods can we use to set vm metadata except for call set_vm_metadata by the director after create_vm finish? Can we set metadata by cli? This is a very important step when users need to set metadata.

Thank you~

**Comment by loewenstein** [comment]
Hi @EdwardStudy,

To my knowledge there is no BOSH cli command to set metadata. Depending on your use case you can of course use whatever IaaS means to set those.

Would be great to hear the use case of setting metadata *after* the deployment instead of *as part of* the deployment.

Best
Jan

**Comment by EdwardStudy** [comment]
@loewenstein As I know, the director can invoke set_vm_metadata with deployment level tags. In my use case, I want to specify tags to some vms in operation. It also could be done by IaaS management. Do you have any plan to add this feature about specify tags to specific vms?

**Comment by Kiemes** [comment]
@EdwardStudy just some thought about you putting tags on the VM after deployment. What would happen if a VM breaks down and is resurrected by BOSH? You would need to set your additional tag manually again as BOSH does just a redeployment of what you specified in the manifest at deploy-time. You would lose the intended benefits of BOSH here in my opinion.

**Comment by EdwardStudy** [comment]
@Kiemes Thank you. That was a good operation scenario. In my opinion, the deployment level of tags operation is too broad. I thought that some tags can be added to the intance_groups block. These tags could label which apps/services in those VMs.

**Comment by cppforlife** [comment]
@EdwardStudy can you describe a bit more in detail how would you use tags that are only applied to an instance group?

**Comment by cppforlife** [comment]
closing given absence of more info.
