### ISSUE TITLE
enforce jobs/<name> to match the spec name

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#359]
See https://github.com/cloudfoundry-incubator/kubo-release/pull/132 - I think `bosh create-release` should have failed if the job spec name didn't match the jobs folder name. It is spontaneously confusing to the casual reader when job names in source repo don't match the names in the final releases/manifests.

**Comment by pivotal-jamil-shamy** [comment]
Story created https://www.pivotaltracker.com/story/show/153460843
