### ISSUE TITLE
Don't fail for "options.organization" in certificate variables

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#362]
In kubo-deployment's base manifest they are assuming that `options.organization` is a valid attribute. This breaks for `bosh deploy --vars-store`. Could we allow it as a noop attribute?

```
$ bosh deploy --vars-store ...

Evaluating manifest:
  Getting all variables from variable definitions sections:
    Generating variable 'tls-kubelet':
      Failed to generate certificate, parameters are invalid:
        Unsupported certificate parameter 'organization'
```

Current work around is to provide an operator file to remove all `options.organization` attributes from known variables.

**Comment by drnic** [comment]
Implemented upstream in https://github.com/cloudfoundry/config-server/pull/7

**Comment by karampok** [comment]
Hello, any update on this issue? Do we expect to be solved because of the change in the config-server?

thx!

**Comment by karampok** [comment]
Hi again! any update?

The reason why I am asking again is that In CFCR team we are going to enforce authorization between apiserver and kubelet. This authorization depends on a cert and specifically on the value of the  `organization` field.  Therefore `--var-store` probably will stop working.

Thanks!

**Comment by drnic** [comment]
This came up again for me due to https://github.com/cloudfoundry-incubator/cfdev (which does not include a config-server).

**Comment by drnic** [comment]
I have a PR on config-serverthat adds support for `organization` field: https://github.com/cloudfoundry/config-server/pull/12

**Comment by DanielJonesEB** [comment]
What's the status of this? Just ran into the issue myself trying to deploy CFCR.
