### ISSUE TITLE
create-release fails when using gcs as the blobstore and config/private.yml is not present

### ISSUE THREAD

**Issue by aaronshurley** [cloudfoundry/bosh-cli#363]
we've setup a blobstore for a bosh release on gcs but when we try to create a dev release without the `config/private.yml` (acting as a general consumer) we encounter an error:

```
$ bosh cr --force
Blob download 'envoy-linux/envoy-06d62d5c67ccec06bb5c3f1985683fcd542945a2.tgz' (3.6 MB) (id: 1076036f-a604-4ee6-6a1c-e011a49a9c9d sha1: d436d85277954ac3060594469a70bf43edbb580f) started

Blob download 'envoy-linux/envoy-06d62d5c67ccec06bb5c3f1985683fcd542945a2.tgz' (id: 1076036f-a604-4ee6-6a1c-e011a49a9c9d) failed

- Getting blob '1076036f-a604-4ee6-6a1c-e011a49a9c9d' for path 'envoy-linux/envoy-06d62d5c67ccec06bb5c3f1985683fcd542945a2.tgz':
    Reading config:
      json_key must be set

Exit code 1
```

Perhaps bumping bosh-cli's bosh-gcscli to [this commit](https://github.com/cloudfoundry/bosh-gcscli/commit/464c3ab83d79201071318a641f4fec5498fdc901) would fix things.

Please let us know if you need anything further.

**Comment by dpb587-pivotal** [comment]
Looks like we updated to the latest gcscli in #343 and was included in [v2.0.46+](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.46).

Give it a try, when you get a chance, and feel free to reopen if you continue to see issues.
