### ISSUE TITLE
delete-release doesn't fail for unknown releases

### ISSUE THREAD

**Issue by poy** [cloudfoundry/bosh-cli#365]
If I were to do:
```
bosh -e lite delete-release INVALID_RELEASE_NAME -n
```
I get an exit code 0 with a messages saying "Succeeded".

I think this is misleading.

```
bosh --version
version 2.0.28-cb77557-2017-07-11T23:04:21Z
```

**Comment by tjvman** [comment]
`delete-release` (and the other deletion commands) are intended to be idempotent for use in CI, so the `Succeeded` that it outputs signifies that the CLI did not encounter any errors while running. 

That being said, I wholeheartedly agree that the lack of any message saying `No releases deleted` or something similar is confusing and forces users to run an additional `bosh releases` to make sure that the command actually did what they expect.

See also: 
* https://github.com/cloudfoundry/bosh-cli/issues/174
* https://github.com/cloudfoundry/bosh-cli/issues/141
* https://github.com/cloudfoundry/bosh-cli/issues/107

**Comment by apoydence** [comment]
I agree that a CI would want the existing behavior, however it seems like that should exist behind a flag. There is precedence for this from Unix (rm -f).
