### ISSUE TITLE
Extra args error prints the type instead of the name of the command

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-cli#37]
We are running the new CLI in CI and the logs showed the following error:

```bash
Command '*cmd.EnvironmentOpts' does not support extra arguments: 10.85.57.6

Exit code 1
```

This was due to the change from `env` to `alias-env`. It would have been easier to debug if the error showed the command instead of the Golang type:

```bash
Command 'env' does not support extra arguments: 10.85.57.6

Exit code 1
```

**Comment by cppforlife** [comment]
yup, need to figure out how to avoid duplicating name in the BoshOpts struct and every command (String method).

**Comment by cppforlife** [comment]
Error message is generated here: https://github.com/cloudfoundry/bosh-cli/blob/e5e3823da8b9844d77b195e69a183ea3a9650511/cmd/factory.go#L61. May be some kind of look up against BoshOpts makes sense.

**Comment by freddesbiens** [comment]
Hi.

I created a tracker story to take care of the issue. You can find it here: https://www.pivotaltracker.com/story/show/160556633

Thank you for your patience!
