### ISSUE TITLE
private.yml should be able to handle variables from credhub

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/bosh-cli#370]
My use cases are upload-blobs and create-release.   When bosh is integrated with credhub then the private.yml file should be allowed to have credhub variables.   In this way private.yml can be checked into the source tree without exposing variables.

**Comment by cppforlife** [comment]
@norman-abramovitz yeah, i agree. 

any suggestion at which point to ask for config server urls, certs and creds to access necessary values?
