### ISSUE TITLE
create-env re-compile ruby-2.4

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#371]
Deploying with AWS CPI:
```
Started deploying
  Deleting VM 'i-0dd88d07d318906ee'... Skipped [VM not found] (00:00:05)
  Creating VM for instance 'bosh/0' from stemcell 'ami-1084a875 light'... Finished (00:00:25)
  Waiting for the agent on VM 'i-05e3d2a60f31bafd2' to be ready... Finished (00:00:34)
  Attaching disk 'vol-01db759cc79098065' to VM 'i-05e3d2a60f31bafd2'... Finished (00:00:17)
  Rendering job templates... Finished (00:00:10)
  Compiling package 'ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'otherthings/xxxx'... Skipped [Package already compiled] (00:00:02)
[Package already compiled] (00:00:01)
  Compiling package 'ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e'... Finished (00:01:47)
```

If `ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e` is already compiled, why did it then spend 2 minutes re-compiling it?

**Comment by drnic** [comment]
Is it fair (in a future fix) to reuse the compiled version if available? Or important to recompile it?

**Comment by dpb587-pivotal** [comment]
Technically we could try to be clever enough to prioritize package+checksum, with compiled packages taking precedence, and then skipping the upload/compile stage for the second ones. Probably a nice optimization, but may not be trivial, and not a high priority for us.

**Comment by cppforlife** [comment]
currently we dont "jump the boundary" of releases, even if pkgs are the same. we may in future. this is true for cli and the director.
