### ISSUE TITLE
Assumes director and uaa share same ca cert

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/bosh-cli#375]
The cli assumes that the director cert and uaa cert are signed by the same ca. If that's not the case, and the user sets `BOSH_CA_CERT` to the director ca cert, it's impossible to authenticate via uaa. It would be useful to allow different ca certs for the director and uaa--we could add an optional `BOSH_UAA_CA_CERT` option and default to the director ca cert if not provided.

@LinuxBozo

**Comment by dpb587-pivotal** [comment]
For what it's worth, the CA cert passed to BOSH can contain multiple, independent certificates. The CLI then trusts certs based from any of the certificates passed in the CA cert data. That's one alternative to trusting system certs or requiring the same CA for both.
