### ISSUE TITLE
When specifying an environment with port but config file doesn't have port, x509 error occurs (and vice versa)

### ISSUE THREAD

**Issue by dennisjbell** [cloudfoundry/bosh-cli#378]
Because now the default director port of 25555 doesn't need to be specified, it is acceptable for the the url for a given director in .bosh/config not specify the port.  It is also acceptable to specify the actual url with or without the port in the -e option to bosh command.  However, if there is a mismatch between what's specified in the config file and what's specified on the command line regarding port presence or absence, it won't pick up the certificate and a x509 error will occur.

Absence of explicit port in either location should be treated as if :25555 was provided to allow lookup of corresponding certificate.

**Comment by cppforlife** [comment]
@dennisjbell to clarify this happens when `alias-env` command was given one url and then subsequent command are given diff value in `-e` flag, right?

**Comment by dennisjbell** [comment]
Correct.  In both cases, the protocol and the IP address are the same, just one is specified without the port (relying on the default of 25555) and one explicitly states the default port.  They are equivalent, but not identical.

**Comment by dennisjbell** [comment]
This is mainly causing a problem in automation scripts that explicitly state the port, but are being used by many people, some that did specify the port in `alias-env` and some that did not.  And while its easy to say everyone should just do the same thing, since the cli allows either, its hard to enforce (aka herding cats).
