### ISSUE TITLE
bosh interpolate fails when BOSH_USER env var is set

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry/bosh-cli#379]
Hi,

We are in a situation where we are using `bosh interpolate` to generate a manifest and using the old bosh cli (v1) to deploy via `bosh deploy PATH`. In our shell session we are setting the `BOSH_USER` and `BOSH_PASSWORD` env var so that `bosh (v1) target` will authenticate.

We noticed that `interpolate` fails with the following message:
```
$ bosh2 interpolate manifest.yml -l vars.yml --vars-store creds.yml
BOSH_USER is deprecated use BOSH_CLIENT instead
```

Since `interpolate` does not interact with the director I wouldn't expect this to fail. We have a workaround but this seemed like a bug.

**Comment by cppforlife** [comment]
@kkallday it's working as expected, though i can see your point. i dont think it makes sense to chagne this behaviour especially that cli v1 is almost over horizon.

**Comment by kkallday** [comment]
Yep! That makes sense. We are redeploying our director now with the new CLI.

Thanks
