### ISSUE TITLE
Password visible in the logs

### ISSUE THREAD

**Issue by mkuratczyk** [cloudfoundry/bosh-cli#38]
Hi,

While using https://github.com/cloudfoundry-community/bosh_exporter which consumes this library, I ran into a problem where my BOSH password was logged into the log files:

time="2016-11-03T12:11:36Z" level=error msg="Error reading BOSH Info: Fetching info: Performing request GET 'https://10.193.60.31:25555/info': Performing GET request: Get https://director:MY_REAL_PASSWORD_IN_PLAIN_TEXT@10.193.60.31:25555/info: x509: certificate signed by unknown authority" source="bosh_exporter.go:211"

The passwords seems to be included in the error returned here https://github.com/cloudfoundry/bosh-cli/blob/master/director/info.go#L121

Thanks,

**Comment by dpb587-pivotal** [comment]
Good catch. We should definitely fix that.

Story: https://www.pivotaltracker.com/story/show/129998715

**Comment by cppforlife** [comment]
we recently fixed that i believe. could you try using latest library version?

**Comment by dpb587-pivotal** [comment]
@cppforlife, still fixing and not yet pushed

**Comment by dpb587-pivotal** [comment]
err, meant published; still in the pipeline

**Comment by dpb587-pivotal** [comment]
Fixed in [v0.0.101](https://github.com/cloudfoundry/bosh-cli/releases/tag/v0.0.101).
