### ISSUE TITLE
How can I tell to create-env process that I have already uploaded stemcell image to Openstack

### ISSUE THREAD

**Issue by MadHosoi** [cloudfoundry/bosh-cli#380]
Hi all,
I'm working in a deployment of Bosh in a customized Openstack, that doesn't allow us to upload images via Glance API. But I create the stemcell image manually with the same metas that if it were uploaded from bosh create-env task.
How can I customize the bosh deployment ymls to search to a specific image before trying to upload it to Openstack?

Thank you & Happy New Year!!

**Comment by voelzmo** [comment]
Hi @MadHosoi 

you'd have to create a light stemcell yourself and provide it to create-env instead of a heavy stemcell. This is described in the official docs, let me know if this works out for you: http://bosh.io/docs/openstack-light-stemcells.html

**Comment by MadHosoi** [comment]
Hi @voelzmo, works perfectly!
Thank you so much!!
