### ISSUE TITLE
Feature Request: Ability to filter by instance group with the `bosh instances` command

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry/bosh-cli#385]
As an operator, sometimes I would like to see all instances in a given instance group. Currently you can achieve similar result by `grep` or `awk` to filter the instance group I'm looking for.

##### Specific use case
After deploying cloud foundry, I would like to open Application Security Groups for internal traffic to the mysql cluster deployed with cloud foundry. I would like to automate it with a concourse task, such that after each deploy I get the IPs of the mysql cluster via bosh cli, and then update/create appropriate ASGs with cf cli.

**Comment by dpb587-pivotal** [comment]
There has been some discussion around generic filtering of any table commands, but there isn't anything planned for it. I could see filtering by instance group being useful.

So you would be interested in something like the following?

    $ bosh -d mysql instances --instance=cluster --column=ips
    192.0.2.10
    192.0.2.11
    192.0.2.12

Do you have any use cases where the instances may have multiple networks resulting in multiple IPs per node?

**Comment by ishustava** [comment]
Yes, the command you've mentioned is exactly what I'm looking for.

I have not seen a case where multiple networks would be used for a mysql cluster, although I could see it being possible for use cases other than deploying mysql as part of CF, or when deploying other services (i.e. not necessarily mysql).
