### ISSUE TITLE
create-env and delete-env should cleanup stemcell images, maybe

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/bosh-cli#388]
Recently we received a question from a BBL user (cc: @ryanmoran) who deploys, destroys, and upgrades their BOSH director often who had hundreds of orphaned images in their account. In GCP, each time you upload a stemcell this results in a new image in your account, even if using the light image. As it happens, the `create-env` uploads a stemcell for the director. Furthermore, we suspect that `bosh cleanup` and `bosh delete-env` do not remove these.

Do I correctly understand the source of the VM image leak? How can these be cleaned up automatically? I am not only making a feature request here, but also seeking guidance on a possible PR. It seems that references to the stemcells are stored in the `bosh-state.json` already. Is the only work that remains to make delete-env delete those stemcells? Also, create-env can be called again with a different manifest with a different stemcell, should create-env also delete the stemcell in the state if it is about to upload a new one?

**Comment by dpb587-pivotal** [comment]
The `bosh clean-up` command should indeed be deleting unreferenced resources, but be aware that it leaves the 3 most recent versions of most resources (like stemcells). When completely tearing down an environment you should use the `--all` flag to no longer try and keep a buffer of three. If this doesn't help, it might be useful to add a `bosh stemcells` to verify it is not the culprit of abandoning stemcells. I suspect a missing `--all` is the main reason behind the abandoned images.

When running `bosh delete-env`, the referenced stemcell should indeed be removed. We run through this scenario when tearing down in our CI environments. The output should look something like the following from our BATS test. If there are still stemcells hanging around, it would be helpful to know if you're seeing the "Deleting stemcell" in your `delete-env` commands.

```
Started deleting deployment
  Waiting for the agent on VM 'vm-ccfc8bff-dc1d-435c-93f5-ecf83b2fce1a'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:00)
  Unmounting disk 'disk-e114cf1c-3c37-4b45-aba2-22e83cf22541'... Finished (00:00:01)
  Deleting VM 'vm-ccfc8bff-dc1d-435c-93f5-ecf83b2fce1a'... Finished (00:00:16)
  Deleting disk 'disk-e114cf1c-3c37-4b45-aba2-22e83cf22541'... Finished (00:00:04)
  Deleting stemcell 'sc-4617eb00-0ecb-42db-b5d7-f0f9c0d7f505'... Finished (00:00:04)
```

When it comes to `create-env`, it should also be destroying all stemcells which are not the "active" stemcell being used by the VM. The output will look similar to `delete-env`, but happens right after finishing the deployment. The output should look something like the following from an environment upgrader...

```
  Running the post-start scripts 'bosh/0'... Finished (00:00:00)
Finished deploying (00:06:37)

Deleting unused stemcell 'ami-f1745b8b light'... Finished (00:00:05)
Stopping registry... Finished (00:00:00)
```

If you can find more info/output to confirm some of these behaviors, I think that would be helpful. I think this should be working as you want/expect.

**Comment by evanfarrar** [comment]
I will close for now. It is helpful just to know that this is not an expected behavior; we will re-open if we can further narrow the conditions under which it happens.
