### ISSUE TITLE
When using ECC private key: Parsing private key: asn1: structure error: tags don't match

### ISSUE THREAD

**Issue by grahamja** [cloudfoundry/bosh-cli#397]
I receive this error when doing a bosh deploy where I provided the ca-chain and key with the key being an ECC key.

`Evaluating manifest:
  Getting all variables from variable definitions sections:
    Generating variable 'consul-tls':
      Loading certificates:
        Parsing private key:
          asn1: structure error: tags don't match (16 vs {class:0 tag:6 length:8 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2`

It works fine if the key is RSA. Is it expected that ECC keys are not supported?

**Comment by dpb587-pivotal** [comment]
Hi - the bosh-cli does not currently support ECC keys for the CA certificate. Do you have a specific business requirement for this to be supported?
