### ISSUE TITLE
bosh ssh via $BOSH_ALL_PROXY and $BOSH_GW_HOST

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#406]
I have `$BOSH_ALL_PROXY` and `$BOSH_GW_HOST` set - the former to route traffic via the jumpbox, the latter for `ssh` requests to be routed via an additional gateway. If both are set then I'd like `ssh` commands to be routed via the jumpbox -> gateway -> instance, please?

My use case here is to `bosh ssh` into garden containers within a bosh-lite running behind a jumpbox.

**Comment by dpb587-pivotal** [comment]
What currently happens in this case?

**Comment by cwlbraa** [comment]
socks5 proxy settings override gateway environment variables and flags for bosh ssh.

see https://github.com/cloudfoundry/bosh-cli/blob/master/ssh/ssh_args.go
