### ISSUE TITLE
bosh instances command for all deployments of an environment returns incorrect output

### ISSUE THREAD

**Issue by sukhil-suresh** [cloudfoundry/bosh-cli#410]
For director `264.7.0` and cli version `3.0.1-712bfd7-2018-03-13T23:26:43Z`, when I run the command `bosh -e myenv instances` it returns a bunch of Task Ids. 

**Expected** to see instance ids across all deployments

**Actual output listed below:**
```
○ → bosh -e prod instances
Using environment 'bosh.run.pivotal.io' as client 'xyz'

Task 3969718
Task 3969719
Task 3969717
Task 3969716
Task 3969720. Done

Task 3969718 done

Task 3969716 done

Task 3969717 done
...
```

**Comment by pivotal-sukhil-suresh** [comment]
Ok... seems like weird UX. The instances are eventually listed after a whole bunch of `Task X, Task X. Done` messages.

Not Ideal UX, but yes, the command does work :)

**Comment by cppforlife** [comment]
@pivotal-sukhil-suresh we are planning to start outputting instances once they are (per deployment) so that output is shown as soon as possible.
