### ISSUE TITLE
re-evaluating vm extensions without a deploy (Feature request / Request For Comment)

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/bosh-cli#416]
Hello, I wanted to raise a scenario that I have observed users struggling with on multiple occasions: 
1) make a load balancer
2) upload cloud config with a vm extension pointing to that LB
3) deploy CF or concourse
4) see load balancer connected and working well
4) edit the LB significantly, maybe delete them or change type
5) upload the cloud config
6) not see their load balancers connected to VMs and not understand why

The answer that I give to a stuck user here is that they need to re-deploy, re-create, or otherwise trigger BOSH to re-evaluate that vm_extension. I guess that makes sense: uploading a cloud config should not be interpreted by BOSH as a desire to redeploy/change anything that may be critical to production uptime. But I also see users struggling with this frequently, so I'd like to think about solutions.

Here are some possible solutions, but there are probably more/better ones:
1) a command / api endpoint that one could use instead of `bosh recreate`.  Ideally this could be keyed by the vm extension name or the actual property, rather than the job VMs. E.g. "fix every vm attached to *this* load balancer" "change the IAM profile on any VM that uses *this* profile name" instead of needing to know the magic information that `bosh recreate router` or `bosh recreate k8s_master` were what you needed to run.
2) a flag or default to `upload-cloud-config` that causes any VM extensions in the cloud config that are attached to VMs to be "re-deployed" or have the implications of their VM extensions re-calculated

**Comment by drnic** [comment]
3. Running `bosh update-cloud-config` displays a list of deployments that are affected by the changes and suggests they need re-deploying to benefit.
