### ISSUE TITLE
Unclear how to use `--skip-drain=` in bosh deploy

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#42]
on version `0.0.101-33f5c26-2016-11-08T03:36:51Z` documentation just has 
```
--skip-drain=       Skip running drain scripts
```

It wasn't very obvious to me, that
* Instances or Instance group names go in there
* Wildcard `*` is possible

Not sure how to document these things with go-flags, wdyt?

**Comment by cppforlife** [comment]
yup looks like `value-name` is missing similar to what we've done here: https://github.com/cloudfoundry/bosh-cli/commit/33f5c26b0b7c960778ab7284eed13eeb700f16f9

**Comment by cppforlife** [comment]
Related: https://www.pivotaltracker.com/story/show/130417399

**Comment by tjvman** [comment]
@voelzmo I believe the commits in the above story should cover the cases you mentioned, though explicitly specifying wildcard still isn't in the `-h` output because it's the default behavior. 

It might be nice to update the documentation to state more clearly that you pass `--skip-drain` multiple times if you want to skip more than 1 instance group. @cppforlife thoughts?

**Comment by voelzmo** [comment]
@tjvman not sure what you mean by specifying a wildcard "is the default behavior". I had to look into the code to figure out that `*` is a valid value. Right now, this is what I get for `bosh deploy --help` in terms of skipping `drain`:
```
--skip-drain=INSTANCE-GROUP    Skip running drain scripts for specific instance groups
```

While that is better than before, there are some details missing:
* I can enter individual instances in the form `instance-group/uuid`
* I can enter `*` as a wildcard
* I can specify this option multiple times (this also applies to many other options like `-o`, `-v`, etc)

As stated in my original comment, I'm not sure how to best do this with go-flags here.

**Comment by jfmyers9** [comment]
Going to close and reopen to generate a tracker story.

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty

**Comment by voelzmo** [comment]
Reopened as requested. Not sure this triggers creation of a new story though.

**Comment by aashah** [comment]
Hey, we took a look at this issue and think it ought to be discussed with our PM. We gave the story a label (`pre-ipm`) to ensure we discuss it this coming Friday.

Thanks,
Aakash & @jaresty

**Comment by h4xnoodle** [comment]
Seems this is at least different now:

```
$ bosh -v
version 5.4.0-891ff634-2018-11-14T00:21:14Z

$ bosh deploy -h
...
   --skip-drain=INSTANCE-GROUP     Skip running drain scripts for specific instance groups
...
```

**Comment by dlresende** [comment]
The CLI output was fixed [here](https://github.com/cloudfoundry/bosh-cli/commit/78f43f45492739f6732c90097e5141600bb5ab08) and the docs updated. The change should be available in the next version of the CLI.

Diego & @rkoster
