### ISSUE TITLE
Unable to add aws session token?

### ISSUE THREAD

**Issue by TimonB** [cloudfoundry/bosh-cli#423]
Hello,

I'm trying to add the aws session token to bosh create-env as "-v session_token" but I only get the message "AWS was not able to validate the provided access credentials".

Here is my code:

`
bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/aws/cpi.yml \
    -v director_name=bosh-1 \
    -v internal_cidr=10.0.0.0/24 \
    -v internal_gw=10.0.0.1 \
    -v internal_ip=10.0.0.6 \
    -v access_key_id=$AWS_ACCESS_KEY_ID \
    -v secret_access_key=$AWS_SECRET_ACCESS_KEY \
    -v session_token=$AWS_SESSION_TOKEN  
...
`

Is this the correct way to inject the session token? I need to use the session because the account hast mfa activated...

**Comment by TimonB** [comment]
@jhuntoo 

I had to modify the "/instance_groups/name=bosh/properties/aws?" (file bosh-deployment/aws/cpi.yml): 

  path: /instance_groups/name=bosh/properties/aws?
  value: &aws
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    session_token: ((session_token))
    default_key_name: ((default_key_name))
    default_security_groups: ((default_security_groups))
    region: ((region))

**Comment by jhuntoo** [comment]
Thankyou @TimonB that did the trick!

I've created this PR to address it the repo that's referenced in the getting started tutorial. 

https://github.com/cloudfoundry/bosh-deployment/pull/246
