### ISSUE TITLE
Add support for forcing release upload on deploy

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/bosh-cli#426]
If I put compiled release urls in my deployment manifest and then later upgrade my stemcell and upgrade my release urls to new compiled releases that match the new stemcell then deploy fails with errors like:

```
Can't use release 'loggregator/102.1'. It references packages without source code and are not compiled against stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.7':
```

Even though my deployment manifest has release config like:
```
- name: loggregator
  version: 102.1
  url: https://storage.googleapis.com/cf-deployment-compiled-releases/loggregator-102.1-ubuntu-trusty-3586.7-20180509-180237-948649107.tgz
```

It would be nice to provide a switch on `deploy` to force the re-upload of releases.

**Comment by drnic** [comment]
I think your use case here is that you've got a new major stemcell version (3586.7) and need to upload the new compiled releases?

Try adding the following to include `releases` item:

```
  stemcell:
    os: ubuntu-trusty
    version: "3586.7"
```

For example https://github.com/cloudfoundry-community/cf-containers-broker-boshrelease/blob/master/manifests/docker-broker.yml#L117-L145

**Comment by youngm** [comment]
Woah!  Thanks @drnic , that's perfect.
