### ISSUE TITLE
How do I install this CLI?

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/bosh-cli#43]
The README says "Relevant documentation pages from bosh.io", and links to the Installing BOSH section of the BOSH docs.

Then there's a heading, "Install BOSH CLI", which [links to here](https://bosh.io/docs/bosh-cli.html).

Those instructions are for the Ruby CLI.

**Comment by dpb587-pivotal** [comment]
One of the teams started a brew tap if you're interested: https://github.com/cloudfoundry/homebrew-tap/pull/19.

Alternatively you can get the latest build from our pipeline: https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh:cli/resources/release-bucket-darwin

Or, if you're feeling adventurous, feel free to `go get github.com/cloudfoundry/bosh-cli`

Probably should include those options somewhere in the readme until official docs suggest the new cli.

**Comment by cppforlife** [comment]
I've updated http://bosh.io/docs/cli-v2.html#install and also updated readme link is going thru the pipeline.
