### ISSUE TITLE
BOSH_ALL_PROXY hangs when proxy username is not 'jumpbox'

### ISSUE THREAD

**Issue by jamesjoshuahill** [cloudfoundry/bosh-cli#432]
### Scenario
- When I use bosh-cli v3.0.1
- And I set `BOSH_ALL_PROXY` with the `ssh+socks5` scheme and username `ubuntu`, e.g.
`export BOSH_ALL_PROXY="ssh+socks5://ubuntu@jumpbox.example.com:22?private-key=path/to/private.key"`.
- And I have set `BOSH_CLIENT`, `BOSH_CLIENT_SECRET`, `BOSH_CA_CERT` and `BOSH_ENVIRONMENT` correctly.
- Then when I run `bosh deps` the command hangs indefinitely.

### Cause
The lack of error message took some time to track down the cause. However, we discovered that the username `jumpbox` is hard-coded in the version of socks5-proxy vendored in `bosh-cli`:

- [proxy.HostKeyGetter#Get()](https://github.com/cloudfoundry/socks5-proxy/blob/6afb711f4b32a266b51160288e98fd3c4b28f0cb/host_key_getter.go#L33)
- [proxy.Socks5Proxy#Dialer()](https://github.com/cloudfoundry/socks5-proxy/blob/6afb711f4b32a266b51160288e98fd3c4b28f0cb/socks5_proxy.go#L68)

The username is parameterised in the latest version of socks5-proxy following https://github.com/cloudfoundry/socks5-proxy/pull/8.

Also, `bosh-utils` was updated to extract the username from `BOSH_ALL_PROXY` and pass it to `proxy.Socks5Proxy#Dialer()` by: https://github.com/cloudfoundry/bosh-utils/commit/9a2bb19b92823974d44fcf1e84e326c4d4a63061#diff-6ad96d4dfbd3afcf55af4923999befa8 on Feb 22 2018.

### Suggestion
This issue could be resolved by bumping the version of `bosh-utils` vendored in `bosh-cli`.

The ssh.ClientConfig structs in `socks5-proxy` should have timeouts, so that dial does not hang forever.

Josh and @mirahimage

**Comment by Amit-PivotalLabs** [comment]
Oh, nice find!  I wonder if this is the cause of the issue I'm seeing here: https://github.com/cloudfoundry-incubator/bosh-alicloud-cpi-release/issues/37

**Comment by Amit-PivotalLabs** [comment]
@jamesjoshuahill maybe this is solved in BOSH CLI v4.0.1: https://github.com/cloudfoundry/bosh-cli/compare/v3.0.1...v4.0.1#diff-04718f634183d74a691e00cb3a485ef1R79

**Comment by Amit-PivotalLabs** [comment]
I was able to `brew upgrade` to v4.0.1 and get passed this issue.

**Comment by jamesjoshuahill** [comment]
Good spot @Amit-PivotalLabs. I can confirm this issue is fixed in bosh-cli v4.0.1
