### ISSUE TITLE
Run `bosh upload-stemcell` command with empty `--sha1` value

### ISSUE THREAD

**Issue by norshtein** [cloudfoundry/bosh-cli#433]
Hi, I'm using `version 2.0.48-e94aeeb-2018-01-09T23:08:07Z`. I accidentally run the following command:
`bosh -e azure upload-stemcell --sha1= https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3586.16` 
 It is noticed the sha1 option is used but it's value  is empty, but the bosh cli takes this command and processes it as the sha1 is correct, the running log is: 
```
Task 27

Task 27 | 06:58:58 | Update stemcell: Downloading remote stemcell (00:00:08)
Task 27 | 06:59:06 | Update stemcell: Extracting stemcell archive (00:00:04)
Task 27 | 06:59:10 | Update stemcell: Verifying stemcell manifest (00:00:00)
Task 27 | 06:59:12 | Update stemcell: Checking if this stemcell already exists (00:00:00)
Task 27 | 06:59:12 | Update stemcell: Uploading stemcell bosh-azure-hyperv-ubuntu-trusty-go_agent/3586.16 to the cloud (00:01:25)
Task 27 | 07:00:37 | Update stemcell: Save stemcell bosh-azure-hyperv-ubuntu-trusty-go_agent/3586.16 (bosh-stemcell-fc3ce5c2-8708-4109-90b5-5ab69c94d788) (00:00:00)

Task 27 Started  Tue May 29 06:58:58 UTC 2018
Task 27 Finished Tue May 29 07:00:37 UTC 2018
Task 27 Duration 00:01:39
Task 27 done

Succeeded
```
Is this behavior a bug or this behavior is by design?

**Comment by dpb587-pivotal** [comment]
In most scenarios, I'd expect if the value is missing, it's an ignored, undefined variable that went missing. Regardless, if the user is specifying `--sha1` in any form, I'd assume their expectation would be to have the download be verified. From that perspective, at least I would consider this a bug.
