### ISSUE TITLE
bosh ssh should follow shell conventions

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh-cli#434]
`bosh ssh` does not follow conventions generally used by POSIX shells. This introduces extra complexity when trying to use `bosh ssh` as part of a script.

Specifically:
1) stdout of commands should not be reformatted
2) stdout and stderr should not be merged (unless redirected by the user)
3) the shell's exit code should be the exit code of the last command, unless the shell itself encountered an error

When using openssh, retrieval of stdout, stderr, and exit code of a remote command is trivial:
```
ssh "echo output; >&2 echo error; exit 123;" > ssh_out.txt 2> ssh_err.txt

echo $?
123

cat ssh_out.txt
output

cat ssh_err.txt
error
```

Compared to `bosh ssh`:
```
bosh ssh -c "echo output; >&2 echo error; exit 123;" > bosh_out.txt 2> bosh_err.txt

echo $?
0

cat bosh_out.txt
vm/0: stderr | Unauthorized use is strictly prohibited. All access and activity
vm/0: stderr | is subject to logging and monitoring.
vm/0: stdout | output
vm/0: stdout | error
vm/0: stderr | Connection to ip closed.
vm/0: stderr | Killed by signal 1.

cat bosh_err.txt
Running SSH:
  1 error(s) occurred:

* Running command: 'ssh <flags omitted> echo output; >&2 echo error; exit 123;', stdout: '', stderr: '': exit status 123
Exit code 1
```

Using `bosh ssh` in a script requires workarounds to retrieve the desired information:
```
bosh ssh -c "echo OUT:output; >&2 echo ERR:error; exit 123;" > bosh_out.txt 2> bosh_err.txt

grep stdout bosh_out.txt | cut -d' ' -f4- | grep "OUT:" | cut -d':' -f2-
output

grep stdout bosh_out.txt | cut -d' ' -f4- | grep "ERR:" | cut -d':' -f2-
error 

grep "exit status" bosh_err.txt | cut -d':' -f6 | cut -d' ' -f4
123
```

Discussion of stderr and exit handling have come up a few times in different contexts:
https://github.com/cloudfoundry/bosh-cli/issues/33
https://github.com/cloudfoundry/bosh-cli/issues/41
https://github.com/cloudfoundry/bosh-cli/issues/108
https://github.com/cloudfoundry/bosh-cli/issues/141
https://github.com/cloudfoundry/bosh-cli/issues/153
https://github.com/cloudfoundry/bosh-cli/issues/301
https://github.com/cloudfoundry/bosh-cli/issues/325
https://github.com/cloudfoundry/bosh-cli/issues/365

**Comment by cppforlife** [comment]
@xtreme-conor-nosal do you have any recommendation for handling multiple machine results (`bosh ssh instance-group ...` will run against multiple machines for examples, and each machine can have different exit code, output, etc.)?

**Comment by xtreme-conor-nosal** [comment]
@cppforlife I think the default behaviour should be:
- all stdout streams interleaved into bosh's stdout
- all stderr streams interleaved into bosh's stderr (messages can be verbose and include vm name, exit code etc)
- exit code should be non-zero if any of the remote invocations returned a non-zero exit code (probably return the first error code seen)

Additional formatting/structure should be opt-in. Some possibilities could be:
- If using the --json global flag I would expect the instance group, vm and message to be separate keys
- Format flags could be defined (similar to `date +%H%M%S`) so if we defined %i(nstancegroup) %v(m) and %m(essage) the user could specify `--format "%i/%v :: %m"` (the individual streams would be piped through a stream editor before being interleaved)

While looking into this I stumbled on https://www.gnu.org/software/parallel/ - it may be interesting to see how they handle these concerns.

**Comment by domdom82** [comment]
any movement on this? It is really annoying for me as I am trying to stream binary from a bosh vm back to my machine via bosh ssh and it is getting garbled with the `stdout | ` bosh cli output. I do get the issue with multiple instance execution on instance groups but it would be just nice if there were a flag to make bosh ssh behave like regular ssh in terms of stdout/stderr output and leave the problem of interleaved output streams to me. I mean when I do

```
for vm in $vms; do
  ssh $vm echo hello from $vm &
done
```

you also get no guarantees on the response order of stdout/stderr of those ssh calls. But that still gives me the option to handle it on my end. Right now I am stuck because bosh ssh gives me no option to shut it up.
