### ISSUE TITLE
bosh interpolate does not merge objects

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/bosh-cli#437]
When we use `bosh interpolate` with more than one vars file, we don't see nested properties merging.

For example, with the following YAML files.

`test.yml`

```yaml
d: ((a.b))
e: ((a.c))
```

`vars1.yml`

```yaml
a:
  b: testing
```

`vars2.yml`

```yaml
a:
  c: 123
```

When we run `bosh int test.yml --vars-file vars1.yml --vars-file vars2.yml`, we expected to see:

```
d: testing
e: 123
```

When we actually see:

```
Finding variable 'a.b':
  Expected to find a map key 'b' for path '/b' (found map keys: 'c')

Exit code 1
```

Is this intended behaviour?

**Comment by jtarchie** [comment]
It looks like there is a [great library](https://github.com/imdario/mergo) that can do this out of the box™.

**Comment by alex-slynko** [comment]
Connected to #117, I am not sure if the great library will fix that case as well.

**Comment by jtarchie** [comment]
@cppforlife has informed that this issue is intentional.

**Comment by jtarchie** [comment]
![screen shot 2018-06-11 at 9 31 49 am](https://user-images.githubusercontent.com/75184/41241503-5489a804-6d5a-11e8-8a4c-cf85f3b91e4a.png)

**Comment by jtarchie** [comment]
@cppforlife: I think there might be some inconsistent behaviour.

If we present the vars yml file above using dot notation instead of YAML object notation, it works.

`vars1.yml`

```yaml
a.b: testing
```

`vars2.yml`

```yaml
a.c: 123
```

When we run `bosh int test.yml --vars-file vars1.yml --vars-file vars2.yml`, we see:

```yaml
d: testing
e: 123
```

Why is this different?
