### ISSUE TITLE
Add Subject Key Identifiers to generated certificates

### ISSUE THREAD

**Issue by bandesz** [cloudfoundry/bosh-cli#438]
We use the BOSH cli to generate the Cloud Foundry certificates into the variable store.
There is a known issue if you try to rotate the CA certificates outlined in [1].

The root of the problem is that when OpenSSL is configured to trust multiple CAs, and two of them have the same subject name, OpenSSL will only verify certificates against the first one (see [2] in OpenSSL code).

One solution for the CA certificate rotation problem is to set the Subject Key Identifiers so OpenSSL will be able to handle multiple certificates with the same subject name.

We opened https://github.com/cloudfoundry/config-server/pull/9 which will solve the problem long-term.

[1] https://docs.google.com/document/d/1vKxziTEvIgKHubukoyAGaJzGqrMBjun7JffbunlLBPg/edit#heading=h.wftyivqbaag4
[2] https://github.com/openssl/openssl/blob/49f6cb968ff63793f6671d9026fb2a7034dad79a/crypto/x509/x509_lu.c#L613-L617

**Comment by keymon** [comment]
This is fixed in theory in https://github.com/cloudfoundry/config-server/pull/9#issuecomment-415172770

**Comment by dpb587-pivotal** [comment]
Closing - this is available in [v5.2.1](https://github.com/cloudfoundry/bosh-cli/releases/tag/v5.2.1)+.

@keymon, thanks for the reminder.
