### ISSUE TITLE
Cannot pipe or redirect output of tasks expecting a confirmation

### ISSUE THREAD

**Issue by jomora** [cloudfoundry/bosh-cli#440]
Hi,
it is not possible to pipe or redirect output of bosh tasks  if those tasks prompt the user for input.
For example,
`bosh cloud-config | tee test.log` works perfectly fine, but  `bosh  -d <xxx> start | tee test.log` as well as `bosh  -d <xxx> deploy  <path> | tee test.log` fail with the following message:
``` 
$ bosh  -d <xxx> start | tee test.log
Asking for confirmation:
  inappropriate ioctl for device
```
The same applies to redirection with `>`:
`bosh cloud-config > test.log` works perfectly fine, but  `bosh  -d <xxx> start > test.log` as well as `bosh  -d <xxx> deploy <path>  > test.log` fail with the following message:
```
$ bosh  -d <xxx> start > test.log
Asking for confirmation:
  function not implemented
Exit code 1
```

I tracked this down to the go-interact library and [opened a bug on the project](https://github.com/vito/go-interact/issues/11).

Why is this so important?
Apart from the obvious problem that one might want to redirect/pipe stuff in the terminal, it is not possible to write other programs (in my case a tool written in go) which forward `stdin` and `stdout` of bosh-cli.

Is this a known issue?

**Comment by aeijdenberg** [comment]
We've used the `-n` option in the context of `bosh deploy` and that's worked well for us.

```bash
$ bosh help

...
  -n, --non-interactive  Don't ask for user input [$BOSH_NON_INTERACTIVE]
...
```

Have you tried that with `bosh start` ?

**Comment by jomora** [comment]
Using `-n` is obviously not a solution since it suppresses any prompting and so the desired behaviour is not available.

Regarding your question:
```
$ bosh -d <xxx> start | tee test.log

Asking for confirmation:
  inappropriate ioctl for device
Exit code 1
```
Are you going to investigate this flaw?

**Comment by jomora** [comment]
I provided a fix for the go-interact library. 
[https://github.com/vito/go-interact/pull/12](https://github.com/vito/go-interact/pull/12)
