### ISSUE TITLE
It is impossible to add additional ca certificate via Ops File

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry/bosh-cli#450]
```
$ cat 1.yml
something: ((tls))

variables:
- name: kubo_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca

- name: tls
  type: certificate
  options:
    ca: kubo_ca
    common_name: kubelet.cfcr.internal

$ cat ops.yml
- type: replace
  path: /variables/-
  value:
    name: kubo-master-ca
    type: certificate
    options:
      is_ca: true
      common_name: kubo-master-ca

- type: replace
  path: /variables/name=tls/options/ca
  value: kubo-master-ca

$ bosh int 1.yml --ops-file ops.yml --vars-store /tmp/store.yml
Getting all variables from variable definitions sections:
  Generating variable 'tls':
    Loading certificates:
      Expected to find variable 'kubo-master-ca' with a certificate

Exit code 1
```

**Comment by degaurab** [comment]
Hi Alex,
Bosh variables are generated in sequence. Based on the opsfile contents seems like the new CA `(kubo-master-ca)` is added at the end of the variables array and `tls` is updated to use new kubo-master-ca which is causing the failure as CA is not generated before `tls`. 
So changing the sequence of variables (putting `kubo-master-ca` before `tls`) should fix the issues.

For more details on sequencing follow the go-patch docs: https://github.com/cppforlife/go-patch/blob/master/docs/examples.md#array


Please let me know if it works.

Thanks,
Gaurab

**Comment by degaurab** [comment]
@alex-slynko closing issue right now. Feel free to re-open if still have any issues.
