### ISSUE TITLE
capturing the deployment diff in json

### ISSUE THREAD

**Issue by scottillogical** [cloudfoundry/bosh-cli#472]
Hey all, I'd like to be able to capture the deployment diff for displaying in slack for dry runs and bosh deploys.

Currently `bosh deploy --json` with the  returns the diff in the unformated "Lines" block 

```
{
  "Tables": null,
  "Blocks": [
    "\nTask 16415 | 15:23:01 | ",
    "Preparing deployment: Preparing deployment",
    " (00:00:05)"
  ],
  "Lines": [
    "Using environment 'https://bosh-url' as client 'username'",
    "Using deployment 'deployment-name'",
    "Release 'xxx/2.0.0' already exists.",
    "Release 'xxx/3.4.0' already exists.",
        "  releases:\n",
        "  - name: release\n",
        "-   sha1: sha\n",
        "+   sha1: sha\n",
        "-   url: https://bosh.io/d/something\n",
        "+   url: https://bosh.io/d/something1\n",
        "-   version: '100.0'\n",
        "+   version: 70.0.1\n",
    "Task 16415",
    "\n",
    "\n\nTask 16415 Started  Mon Aug 27 15:23:01 UTC 2018\nTask 16415 Finished Mon Aug 27 15:23:06 UTC 2018\nTask 16415 Duration 00:00:05",
    "\nTask 16415 done\n",
    "Succeeded"
  ]
}
```
This format makes it a bit difficult  to parse out what happened (or at least the diff).  

Is there some easier way to capture result of deploys (and dry runs) as a JSON block? (Possibly the /diff endpoint, though I'd like to avoid using curl for this)?  Or can we separate out the deployment diff into a separate JSON block for easy capture?

edit: 
Ideally it would just be returned entirely as structured json, including the sections of the diff (releases, etc)

**Comment by dpb587-pivotal** [comment]
cc @mfine30 as semi-related to deployment impact discussions

**Comment by jaresty** [comment]
@scottillogical this feature is really a feature request for the bosh director, since the bosh-cli is only able to display information that it can receive from the bosh director. Please reopen this issue on the [bosh director repository](https://github.com/cloudfoundry/bosh).
