### ISSUE TITLE
[Feature] As a release author, I want `bosh create-job` to create a scaffold with BPM, such that I can easily follow best pratices for my new releases

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#475]
The old-style shellscript copypasta should no longer be encouraged. Documentation at https://bosh.io/docs/create-release/ could stay the same in most parts, we probably just need to remove the references to the startup scripts.
Wdyt?

**Comment by dpb587-pivotal** [comment]
cc @jfmyers9 @xoebus @aramprice - I think this and related release author UX goals may have been discussed a bit before.

**Comment by mhoran** [comment]
Given BPM does not support Windows, this UX wouldn't make much sense for Windows releases. `bosh create-job` doesn't currently take an OS -- and I wouldn't want to complicate the process too much.

**Comment by jfmyers9** [comment]
At one point someone suggested having a `--adapter bpm` flag or something to `generate-job` which would be a bit more opinionated in one direction or another.

The issues I see with this approach is that I'm not sure what the other values to `--adapter` could possibly be. I'm also not 100% how much value is added. In some ways it may just be better to have explicit documentation in the `create-release` docs.

**Comment by voelzmo** [comment]
@mhoran I think I'm missing some context from the discussion that @dpb587-pivotal is alluding to in his comment. Therefore, I'm looking at this from the current point-of-view:
* we have documentation how to create a release for linux: https://bosh.io/docs/create-release/
  * this uses templating with `bosh generate-job` and contains shell scripts which people copy-paste into their own releases
* we have delta documentation for what's different when creating a release for windows: https://bosh.io/docs/windows/#releases

Not sure if your discussion focused around getting rid of the windows delta documentation, for example, but as long as we have this: Why don't we change the linux documentation and generators to make it easier for people to do the right thing? I don't think the situation for windows release would change much or even at all.
