### ISSUE TITLE
Unable to delete runtime config

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/bosh-cli#478]
We can delete a runtime config's contents via `update-runtime-config` but it would be preferable if there were a `delete-runtime-config` command.

**Comment by mfine30** [comment]
@MasslessParticle this should be possible via 
`bosh delete-config --type=runtime` to delete the default runtime config. You can also specify a specific `--name=NAME` to delete a specific config

https://bosh.io/docs/cli-v2/#configs-mgmt

**Comment by MasslessParticle** [comment]
Perfect, thanks!
