### ISSUE TITLE
UAA authentication does not work properly if env var `BOSH_USER` is set

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-cli#48]
UAA authentication does not work properly if env var `BOSH_USER` is set. BOSH director will return 401 if BOSH_USER is set.

```
$ export BOSH_USER=admin

$ bosh login
Email: admin
Password: <UAA PASSWORD>

Successfully authenticated with UAA

Succeeded

$ bosh deployments
Using environment '<DIRECTOR_URL>' as user 'admin'

Finding deployments:
  Director responded with non-successful status code '401' response 'Not authorized: '/deployments'
'

Exit code 1

$ unset BOSH_USER

$ bosh deployments
Using environment '<DIRECTOR_URL>' as '?'

Name           Release(s)                     Stemcell(s)                                     Cloud Config
concourse      concourse/2.4.0                bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3263.8  latest
               garden-runc/1.0.0
concourse-cpi  concourse/2.4.0                bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3263.8  outdated
               garden-runc/1.0.0

3 deployments

Succeeded
```

**Comment by dpb587-pivotal** [comment]
Happened to see [this comment](https://github.com/cloudfoundry/bosh/issues/1273#issuecomment-220199941) from DK about the ruby cli. Probably the same holds true in go...

 > I believe BOSH_USER/PASSWORD env vars are not meant to be used with login command but rather you can just set them before running any other command (when basic auth is used) and you will be authenticated.

It does look like there is no environment referencing in the UAA prompts: https://github.com/cloudfoundry/bosh-cli/blob/47ea06453290186de2610150498d3901d16c4131/cmd/uaa_login_strategy.go#L90.

**Comment by cppforlife** [comment]
@ljfranklin any recommendation for what should happen? error message if BOSH_USER/BOSH_PASSWORD is specified when UAA is in use?

**Comment by tjvman** [comment]
Closing - with the completion of https://www.pivotaltracker.com/story/show/135458531, BOSH_USER and BOSH_PASSWORD are no longer supported. If there is a similar issue with those changes, though, please open a new issue.
