### ISSUE TITLE
Time format RFC3339 didn't have same cross UTC and other timezones

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/bosh-cli#481]
Hi, I was faced with a bosh-cli problem when I deployed bosh 266.7.0 on *Mac*.
```
bosh -v
version 5.3.1-8366c6fd-2018-09-25T18:25:48Z

Succeeded

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Setting VM metadata to map[created_at:2018-10-08T13:31:57+02:00 index:0 director:bosh-init deployment:bosh job:bosh instance_group:bosh]:
        CPI 'set_vm_metadata' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Setting metadata for vm '**********': Settings tags on virtualGuest '**********': SoftLayer_Exception_InvalidValue: Invalid value provided for 'tags'. Invalid tag names: created_at:2018-10-08t13:31:57+02:00. (HTTP 500)","ok_to_retry":false}

Exit code 1
```

This invalid charater is `+` from Softlayer side. It caused deployment failure. But this issue didn't didn't happen on Linux(`created_at:2018-09-21t09:14:05z`). 

And I found bosh-cli code snippet which used RFC3339(RFC3339     = “2006-01-02T15:04:05Z07:00”):
https://github.com/cloudfoundry/bosh-cli/blob/master/deployment/vm/manager.go#L117

I am confused that datetime format `created_at:2018-10-08t13:31:57+02:00` on *Mac* was not same with *Linux's* (`created_at:2018-09-21t09:14:05z`).

**Comment by edwardstudy** [comment]
I thought it was timezone issue. My Linux timezone is:
```
cat /etc/timezone
Etc/UTC
``` 

And setting Mac’s timezone to UTC resolves the issue.

**Comment by dpb587-pivotal** [comment]
This is expected because you ran the command from machines configured with two different timezones which results in two different date formats due to the TZ suffix being lazy-expanded. The following [example](https://play.golang.org/p/Ul-ckRdnc82) uses the same time and `time.RFC3339` format in two different time zones:

```
2009-11-10T23:00:00Z
2009-11-11T01:00:00+02:00
```
