### ISSUE TITLE
CPI Quota Error doesn't specify the resource 

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh-cli#488]
If a deployment fails due to an exceeded quota the error is:
```
Error: Unknown CPI error 'Unknown' with message 'Your quota allows for 0 more running instance(s). You requested at least 1' in 'create_vm' CPI method
```

Could the error include the specific resource (e.g. r4.2xlarge on demand instance), how many were requested, or how many are available?

**Comment by jaresty** [comment]
@xtreme-conor-nosal Can you please open this issue on the repository for the CPI you are using?  The bosh-cli is only showing messages it receives from the bosh director, so this issue can be better resolved from the CPI.

**Comment by xtreme-conor-nosal** [comment]
Refiled https://github.com/cloudfoundry/bosh-google-cpi-release/issues/310

**Comment by jaresty** [comment]
Thanks!
