### ISSUE TITLE
bosh task --cpi returns no logs

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh-cli#493]
cli version: 5.3.1-8366c6fd-2018-09-25T18:25:48Z
director version: 266.4.0
CPI: gcp

`bosh task <id>` and `bosh task <id> --debug` provide the expected output, 
e.g.
```
$ bosh task 56356
Using environment 'https://10.0.0.6:25555' as client 'admin'

Task 56356

Task 56356 | 23:17:23 | Preparing deployment: Preparing deployment (00:00:01)
Task 56356 | 23:17:24 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 56356 | 23:17:24 | Creating missing vms: fim/6d2b1ca4-bad8-4dce-b111-b82fb99652a7 (0) (00:01:18)
Task 56356 | 23:18:42 | Updating instance fim: fim/6d2b1ca4-bad8-4dce-b111-b82fb99652a7 (0) (canary) (00:00:17)

Task 56356 Started  Fri Nov  9 23:17:23 UTC 2018
Task 56356 Finished Fri Nov  9 23:18:59 UTC 2018
Task 56356 Duration 00:01:36
Task 56356 done

Succeeded
```

but `bosh task <id> --cpi` returns no useful output:
```
$ bosh task 56356 --cpi
Using environment 'https://10.0.0.6:25555' as client 'admin'

Task 56356. Done

Succeeded
```

**Comment by voelzmo** [comment]
Hey @xtreme-conor-nosal,

Thanks for raising this issue. This isn't an issue in the bosh cli, but rather something that was incorrect in the GCP CPI: https://github.com/cloudfoundry/bosh-google-cpi-release/issues/278

This should be working with a new version of the CPI. If now, please reach out to the GCP CPI maintainers, e.g. by re-opening the above issue.

Thanks!
