### ISSUE TITLE
Can't retrieve manifest of failed deployment

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh-cli#497]
Bosh release: 266.4.0
Bosh CLI: version 5.3.1-8366c6fd-2018-09-25T18:25:48Z

I have an unhealthy deployment created by an automated pipeline. Attempting to retrieve the manifest to review the configuration returns a null manifest.

```
$ bosh deployments
Using environment 'https://10.0.0.6:25555' as client 'admin'

Name  Release(s)                   Stemcell(s)                                   Team(s)
cfcr  bpm/0.13.0                   bosh-google-kvm-ubuntu-xenial-go_agent/170.6  -
      cfcr-etcd/1.5.0
      docker/32.1.0
      kubo/0.24.0
      oscap/0.1.14+dev.1542634755

1 deployments

Succeeded
```

```
$ bosh -d cfcr manifest
Using environment 'https://10.0.0.6:25555' as client 'admin'

Using deployment 'cfcr'


Succeeded
```

From CLI Debug log:
```
[clientRetryable] 2018/11/19 11:06:42 DEBUG - [requestID=6860a01a-f855-40fe-4ec4-37e11398bf6a] Requesting (attempt=1): Request{ Method: 'GET', URL: 'https://10.0.0.6:25555/deployments/cfcr' }
[director.clientRequest] 2018/11/19 11:06:42 DEBUG - Dumping Director client request:
GET /deployments/cfcr HTTP/1.1
Host: 10.0.0.6:25555
Authorization: [removed]

[director.clientRequest] 2018/11/19 11:06:42 DEBUG - Dumping Director client response:
HTTP/1.1 200 OK
Connection: close
Content-Length: 17
Content-Type: text/html;charset=utf-8
Date: Mon, 19 Nov 2018 16:06:42 GMT
Server: nginx
Www-Authenticate: Basic realm="BOSH Director"
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

{"manifest":null}

[CLI] 2018/11/19 11:06:42 DEBUG - Succeeded

Succeeded
```

**Comment by BeckerMax** [comment]
Hi @xtreme-conor-nosal is this the initial deployment that is failing? If yes, then it is the currently expected behaviour that you do not get a manifest returned. Bosh uploads (or updates) the manifest only after a successful deploy.
Found this to [retrieve a manifest if the deploy failed](https://github.com/kkallday/deployment-extractor) though I haven't tried it (from https://github.com/cloudfoundry/bosh/issues/245#issuecomment-253396842).

**Comment by xtreme-conor-nosal** [comment]
Yes, this was an initial deployment.

This behaviour isn't clearly documented. `bosh manifest` only says "Show deployment manifest", which I interpret to mean "show the current manifest for (or desired state of) the deployment". Your description sounds like `bosh manifest` returns the last known-good manifest.

Presumably the same behaviour applies to an updated deployment: if the first deployment succeeds and after changing the manifest redeployment fails, `bosh manifest` will return the initial manifest? That seems misleading, unless `bosh manifest`'s primary use case is for reverting deployments rather than inspecting deployments?

**Comment by BeckerMax** [comment]
Created a change in bosh-docs:
https://github.com/cloudfoundry/docs-bosh/pull/617

@xtreme-conor-nosal Would this have helped you?

**Comment by xtreme-conor-nosal** [comment]
@BeckerMax That doc change is clear for the current behaviour. It may be useful to explicitly call out that a blank manifest is expected for a failed initial deployment?

Could the CLI output (at least for the null case) be clarified as well? Acknowledging that there's no successfully deployed manifest might be more intuitive than reporting successful retrieval of a blank manifest.

Could an optional `--current` flag be added to `bosh manifest` so the failed manifest is accessible? (for principle of least surprise I would expect `current` to be the default behaviour and have an optional `last-successful` flag but that would break backwards compatibility). I believe the director should be the source of truth for the currently deployed manifest. For manifests that are generated/deployed by concourse (or just deployed from another workstation) it would be more straightforward (and less error-prone) to retrieve the manifest from the director than to review pipeline output or manually run tasks to re-synthesize the manifest.

**Comment by dpb587-pivotal** [comment]
I'm not sure how much this has been surfaced previously, but internally we have discussed migrating deployment manifests to have the same lifecycle/workflows as generic configs and use them internally (more or less). This helps provide some of the versioning capabilities that those configs already have and provide the option for retrieving pre-deployed, partial-deployed, or previously-deployed manifests.

So, conceptually, agreed with the intent behind `--current`, but we probably should avoid introducing new flags like that until we're able to solve some of the deployment manifest problems in a more generic way.

To your use cases and needs, would a theoretical workflow like the following be useful to you?

```
# optionally send a deployment manifest in advance
$ bosh update-config --type=deployment --name=cfcr manifest

# deploy using latest configs
$ bosh -d cfcr deploy # optionally pass manifest here (to internally create new deployment config)

# review active versions of configs (deployment, cloud, runtime)
$ bosh -d cfcr deployment --column=configs

# review last 10 versions of the deployment manifest
$ bosh configs --type=deployment --name=cfcr --recent=10

# review specific deployment
$ bosh config --type=deployment --name=cfcr 122
```

**Comment by xtreme-conor-nosal** [comment]
Yes, that would work for me

**Comment by jaresty** [comment]
@xtreme-conor-nosal Could you please reopen this issue on the [bosh director repository](https://github.com/cloudfoundry/bosh) with a description of your desired workflow? While it will require a small change to the bosh CLI, the majority of this change will need to happen there to enable the proposed workflow.
