### ISSUE TITLE
[Feature] Provide a command to cancel all queued tasks at once

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-cli#499]
This feature request is the CLI part of the request on [Bosh side](https://github.com/cloudfoundry/bosh/issues/2087). There is also context why this feature is helpful. The request here is to provide a CLI command, which can leverage the director API to cancel all queued tasks at once.

**Comment by friegger** [comment]
Implemented with https://github.com/cloudfoundry/bosh-cli/commit/edc54b376a38f646d0d1a920c9c866cf43041176
