### ISSUE TITLE
`bosh create release` fails if never created a final release before

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#5]
When `config/final.yml` isn't there, `bosh create-release` fails:
```
bosh create-release
Expected non-empty 'final_name' in config '/Users/<user>/workspace/<my-release>/config/final.yml'
```

**Comment by cppforlife** [comment]
@voelzmo cli requires config/final.yml to be present. are you proposing a better error message?

**Comment by voelzmo** [comment]
The ruby CLI creates `config/final.yml` when the first final release is created. Until then I can just release dev releases in version `0+dev.x`. With the go CLI that is not possible.

So here is my scenario:
* I'm working on a new release
* I haven't done a final release
* I want to create a dev release

That should be possible somehow, currently it isn't.

**Comment by cppforlife** [comment]
@voelzmo it's possible. just make a `config.yml` with a final_name. ideally we should rename `final_name` to really just `name`.

**Comment by voelzmo** [comment]
What I mean is: this used to work without me having to do anything manually. The ruby CLI asked me for a release name and did its magic. The go cli doesn't do it. Why should I have to create such a file manually now?

**Comment by cppforlife** [comment]
what would happen in the non-interactive case?

`bosh init-release --dir my-fancy-new-release` does create config/final.yml with base name as the default name. this only applies to existing releases that dont have the name.

**Comment by voelzmo** [comment]
ah, so I might have done the `bosh init-release` with the ruby cli is what you're saying? That might be possible, damn. As long as the go cli is consistent, I guess its fine.

**Comment by voelzmo** [comment]
One more thing: choosing the directory's name as release name is a problem:
* Directories are named after github repos
* those contain '-release' usually
* release names shouldn't contain '-release'

So what about removing '-release' at the end before picking it as name?

**Comment by cppforlife** [comment]
@voelzmo made a tiny commit after you closed the issue to address -release ;) will push tomorrow.

**Comment by cppforlife** [comment]
Fixed by https://github.com/cloudfoundry/bosh-cli/commit/6e0d8def138b6c529cda49d80b09d7047d0666bd

**Comment by addisflava** [comment]
this flag is not working at all  tried with --release or -release . i have a release and the directory name is diffrent that the release name but it always uses the directory as a name

```
bosh init-release --release iptables
unknown flag `release'

Exit code 1

bosh init-release --dir=/mnt/deployments/cf-presagia/presagia_boshreleases/iptable-boshrelease/ -release iptable
unknown flag `r'

Exit code 1

```
