### ISSUE TITLE
Include deployment name into `instances -f --json` output

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-cli#501]
The command `bosh instances --failing --json` is useful to have an overview of all failing instances. Most of the time you need also the deployment name to which the instance belongs. The request here is to include the deployment name in the json output. 

Another improvement to the command could be to write also the deployment name when standard output is redirected to a file. E.g. `bosh instances --failing 2>&1 > file` doesn't have any deployment names when `bosh instances --failing` prints also deployment names.  Also when executing `bosh instances --failing` it should not show deployments that doesn't have failing instances.

**Comment by friegger** [comment]
There are two aspects here:

1. It makes sense to have the deployment name available to the `--json` output and potentially also to the standard output
2. `--tty` is probably sufficient to get the requested information when redirected into a file

**Comment by friegger** [comment]
@mfine30 What do you think about adding the deployment to at least the json output. It is really annoying to deal with failing instances programmatically.

**Comment by beyhan** [comment]
Slack discussion: https://cloudfoundry.slack.com/archives/C094QRLEQ/p1559830918009800

**Comment by s4heid** [comment]
Fixed in https://github.com/cloudfoundry/bosh-cli/commit/410ce8162af8eee453d36b1213b27a8d3f117dda
