### ISSUE TITLE
Extend interpolation library to allow default values for variable substitution in CF CLI

### ISSUE THREAD

**Issue by ihrigb** [cloudfoundry/bosh-cli#502]
see https://github.com/cloudfoundry/cli/issues/1514 for more information.

**Comment by xtreme-conor-nosal** [comment]
BOSH's main use case for variable interpolation is to prevent including credentials in the deployment manifest. Allowing hardcoded defaults would not be recommended.

It's possible to override variables, so providing defaults could be accomplished by either:
```
export DEFAULTS_var=default_value
bosh int manifest.yml --vars-env DEFAULTS [-v var=override_value]
```
or
```
echo "var: default_value" > defaults.yml
bosh int manifest.yml -l defaults.yml [-v var=override_value]
```
