### ISSUE TITLE
`bosh curl` should take data just like curl does

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#507]
with commandline `curl` you can pass in the data for a request using `-d`, which also allows reading it directly from a file with `-d @<filename>`. I'm not sure why a `--body` parameter was introduced instead, I'd say we can deprecate this at the same time.

`cf curl` does it as well: https://github.com/cloudfoundry/cli/blob/7694580f3bcc15a6d275372bfb4077c3b706c267/cf/commands/curl.go#L42

**Comment by h4xnoodle** [comment]
@voelzmo what kind of requests are being made such that you can't use a bosh cli command and curl must be used? If it's a common action for users, we could consider adding a formal command.

AFAIK `bosh curl` isn't a fully featured command.

**Comment by xtreme-conor-nosal** [comment]
For context, `bosh/cf curl` are wrappers around different http client packages, and aren't shelling out to curl, so adding new flags isn't a trivial pass-through change. It's not our goal to support all curl flags.

**Comment by voelzmo** [comment]
Thanks for the context, @xtreme-conor-nosal!

I understand that `bosh curl` isn't really using `curl` and that the different CLIs use different libraries to implement this functionality.

My point here is not about adding a new functionality, nor was I suggesting that this is a trivial pass-through change. I also wasn't suggesting to support all `curl` flags. The command is named `bosh curl` for a reason, though, so ideally the features and flags which *are* present should – if possible with reasonable effort – behave in a similar way that `curl` does.

Back to the original issue: Passing data to the command should happen in the same way that `curl`, `cf curl`, and `credhub curl` decided to implement it: `-d` for passing literal data as string and allowing for `@` to pass in a file.

Does this make sense?

**Comment by h4xnoodle** [comment]
This makes a lot of sense if we wanted `bosh curl` to be just like `curl`, or to be like `cf curl` or any other `curl`-like patterns.

>  The command is named bosh curl for a reason, though, so ideally the features and flags which are present should – if possible with reasonable effort – behave in a similar way that curl does.

Why does it need to behave in a more similar way to `curl`? This tool is performing as intended. We don't intend to have it behave like the independent program `curl` with those exact arguments. The `--body` argument is in place of `-d` as `-d` is already for deployment right now. 

We don't have any other signals that other users need `bosh curl` to follow `curl`'s argument patterns. 

Would it help if we renamed the command so it is _not_ `curl`? Perhaps `bosh request` or something?

**Comment by voelzmo** [comment]
Hey everyone,

After giving this some time and re-reading our interactions here, I realized how terrible my tone was in this conversation. I want to offer my sincere apologies, especially to you, @h4xnoodle. Sorry for any trouble and negativity caused.
Warm regards
Marco

**Comment by h4xnoodle** [comment]
No worries at all @voelzmo! I didn't get the sense there was any negativity :)

I do appreciate your feedback about the command and drawing on the similarities/differences between others. Thanks for pointing that all out.

~ Rebecca
