### ISSUE TITLE
CLI hangs indefinitely when BOSH_ALL_PROXY private key does not match host

### ISSUE THREAD

**Issue by jamesjoshuahill** [cloudfoundry/bosh-cli#508]
Hi BOSH team

This issue was reported for the BBR CLI which depends on `bosh-cli`: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/issues/25

## Scenario
- Given I use `bosh-cli` v5.4.0.
- And I export `BOSH_ALL_PROXY` with the `ssh+socks5` scheme.
- And the SSH private key does not match the proxy host.
- When I run `bosh deps`.
- Then the command hangs indefinitely.

## Cause
We have identified the cause in the `github.com/cloudfoundry/socks5-proxy` package. This is a dependency of the `bosh-utils` package.

We have submitted a PR to fix this issue: https://github.com/cloudfoundry/socks5-proxy/pull/13.

Best wishes
Josh

**Comment by jamesjoshuahill** [comment]
`socks5-proxy` v0.1.0 has a fix for this issue.

A pull request has been opened to bump this dependency in `bosh-utils`: https://github.com/cloudfoundry/bosh-utils/pull/67.

**Comment by jamesjoshuahill** [comment]
The `bosh-utils` PR has been merged: https://github.com/cloudfoundry/bosh-utils/pull/67

**Comment by jamesjoshuahill** [comment]
`bosh-utils` dependency was bumped to include the fix for this issue in https://github.com/cloudfoundry/bosh-cli/commit/a06775948d50696cdfedd9abf27d3978f48b6791

**Comment by jaresty** [comment]
I'm assuming that the issue was resolved based on the comments above. Feel free to reopen if it's still an issue.
