### ISSUE TITLE
`bosh instances -fp` does not show jobs that failed in pre-start

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh-cli#514]
If a bosh deployment fails in prestart, I would expect `bosh instances --failing --ps` to list those jobs.

Actual behaviour: `bosh instances  --failing --ps` does not list any jobs from the expected VMs.

Because bosh doesn't setup /var/vcap/monit/job if there's a prestart failure, monit isn't aware of any processes. This appears to result in bosh treating the processes as non-existent instead of failing.

**Comment by s4heid** [comment]
In theory, I think agent might be able to install process configuration before pre-start. I think during an update of an existing VM we leave the job's monit configuration files and we are able to rely on `unmonitor` to have disabled them. If there was a way for agent to proactively unmonitor everything before installing them, that might help solve this. Agent would then immediately see the processes, but know they are not running.

This is probably more of a [bosh-agent](https://github.com/cloudfoundry/bosh-agent) issue since it provides the data to director/CLI, but we can probably continue the discussion here for now.

/cc @luan 

@s4heid && @dpb587-pivotal

**Comment by mrosecrance** [comment]
This isn't the behavior that I've been able to reproduce. What we see is that the vms are all created, the canary fails in the pre-start and enters a `stopped` (failed) state. The other vms are listed as running but this is desired behavior in the upgrade case.

```
$ bosh instances --failing
Instance                                          Process State  AZ  IPs
zookeeper/52a28d62-7ea8-4a14-a2a0-d88487611473    stopped        z1  10.244.0.2
```
```
$ bosh instances -p
Deployment 'zookeeper'

Instance                                          Process  Process State  AZ  IPs
zookeeper/52a28d62-7ea8-4a14-a2a0-d88487611473    -        stopped        z1  10.244.0.2
zookeeper/84dc99ae-038b-4454-8eba-641ffbfbd3fd    -        running        z2  10.244.0.5

2 instances
```

Are you running an upgrade or a fresh deploy? What version of the director are you using?

**Comment by xtreme-conor-nosal** [comment]
If I request the failing processes, I expect the output to include the process names. 

For example, if I break my pre-start script and create a new deployment, the result of `bosh instances --failing --ps` is:
```
Instance                                       Process  Process State  AZ  IPs
clamav_1/daebaa78-259e-45fa-a08b-6bd88c4f2d8b  -        stopped        z1  10.0.0.2
```
The clamd process isn't explicitly listed as unhealthy. 

But if I break my start script and deploy, the result of `bosh instances --failing --ps` is:
```
Instance                                       Process  Process State  AZ  IPs
clamav_1/daebaa78-259e-45fa-a08b-6bd88c4f2d8b  -        failing        z1  10.0.0.2
~                                              clamd    unknown        -   -
```
The clamd process is explicitly listed as unhealthy. 

Director: 268.5.0
CLI: 5.4.0-891ff634-2018-11-14T00:21:14Z

**Comment by mrosecrance** [comment]
Ah got it. I misunderstood what you were getting at earlier.

**Comment by pnikonowicz** [comment]
Current strategy is to change:

```
Instance                                       Process  Process State  AZ  IPs
clamav_1/daebaa78-259e-45fa-a08b-6bd88c4f2d8b  -        failing        z1  10.0.0.2
~                                              clamd    unknown        -   -
```

to:

```
Instance                                       Process  Process State  AZ  IPs
clamav_1/daebaa78-259e-45fa-a08b-6bd88c4f2d8b  -        -        z1  10.0.0.2
~                                              clamd    unknown        -   -
```

Change process state `failling` to a dash (`-`) since monit has not yet started.
