### ISSUE TITLE
leading zeros removed from numeric release version 

### ISSUE THREAD

**Issue by jason-matthew** [cloudfoundry/bosh-cli#515]
Leading zeros are removed from each semantic version value when uploading bosh releases.  It appears this only occurs if the value is numeric.  

A few examples of release.MF content followed by `bosh releases` identification:

`version: "1.09.12"` -> `1.9.12`
`version: 01.02.03` -> `1.2.3`
`version: 01a.002` -> `01a.2`
`version: "01a.0b2.c03.04"` -> `01a.0b2.c03.4`
`version: "1.2.00"` -> `1.2.0` 

A few notes:
- Attempting to upload `version: "1.2.0"` gave notice of existing package.
- Quoting the version within release.MF produces the same results
- Bosh environment details below.  I've seen this behavior on 268.6.0 as well as 266.7.0

I conceed this is not a major pain.  Struggle here is I only consume (and do not author) bosh releases.  Validating the director's state becomes more tedious.  

```
bosh env

Name      ocf23
UUID      397c4447-0883-4a03-8e00-d7b888ea8288
Version   268.6.0 (00000000)
CPI       vsphere_cpi
Features  compiled_package_cache: disabled
          config_server: disabled
          local_dns: enabled
          power_dns: disabled
          snapshots: disabled
User      admin
```

Closest issue I could find: https://github.com/cloudfoundry/bosh-cli/issues/208

**Comment by dpb587-pivotal** [comment]
Interesting; I was able to reproduce. Sounds like something is parsing the semver and then reconstructing it again instead of using the original value.

**Comment by aashah** [comment]
I believe removing leading zeros is intentional, and happens during `bosh upload-release`. Leading zeros are prohibited in semver (https://semver.org/) -

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes.

Marking this as closed.

- Aakash
