### ISSUE TITLE
Compile CPI failed since PATH is hardcoded

### ISSUE THREAD

**Issue by ywei2017** [cloudfoundry/bosh-cli#519]
We tried to upgrade our BOSH environment to the latest one, together with vSphere-cpi-release-51. As it happens, the compiler we have is too old. Since it is a shared jumpbox, we can't just upgrade the system wide compiler. So we installed the compiler in a separate directory.

But the compilation still keeps on failing. After quite some digging, I found that the BOSH CLI uses a [hardcoded path](https://github.com/cloudfoundry/bosh-cli/blob/a18c72307483843b5e190c383ff5e6835b3a8bf2/installation/pkg/compiler.go#L103). Can this be changed so it uses the PATH value from the environment?

Thanks
Yansheng

**Comment by ywei2017** [comment]
See [PR 520](https://github.com/cloudfoundry/bosh-cli/pull/520) for the proposed fix. I already tested locally and it works fine.

**Comment by jaresty** [comment]
Closing this issue since we merged the PR
