### ISSUE TITLE
Please make interpolate --var-errs also report unused variables

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/bosh-cli#52]
It is great that `bosh interpolate --var-errs ...` helps point out unbound variables whose absence is likely to cause deployment failures.  In addition, it would be very helpful if bosh could report the variables that have been provided but are not being used because it would very quickly point out which variables have been renamed.  Concretely, if a variable like `diego_bbs_host` was renamed to `diego_sql_bbs_host` one would see two errors:

1. The unbound variable `diego_sql_bbs_host` is required.
2. The variable `diego_bbs_host` was provided but was unused.

From this output, it would be quick and easy for a user to realize that the name change is the problem, and should be very easy to fix.

**Comment by cppforlife** [comment]
i was just wishing i had that.

**Comment by cppforlife** [comment]
added:

```
 $ bosh int -h | grep unused
          --var-errs-unused      Expect all variables to be used, otherwise error
```

**Comment by jaresty** [comment]
Is there a planned release date for this feature?  We're using the released versions of the cli.
