### ISSUE TITLE
Show stemcell version in `bosh vms` output

### ISSUE THREAD

**Issue by tjvman** [cloudfoundry/bosh-cli#527]
Currently the only ways to determine what stemcell a given VM is running is to either ssh on to the VM or download the manifest  and look at the stemcell info for the VM's instance.

I propose adding a `Stemcell` column to `bosh vms` that would display the stemcell `name/version` slug for each VM. This could be part of the default display or gated behind a flag, no preference.

**Comment by friegger** [comment]
+1 This would be really helpful to quickly understand what stemcells are actually used in a landscape. @mgadiya What do you think?
