### ISSUE TITLE
runtime-config gives confusing error without --name flag, and help is ambiguous

### ISSUE THREAD

**Issue by markthemarkest** [cloudfoundry/bosh-cli#528]
The runtime-config command does not give a clear explanation of what is happening when no configs are found, and the help is ambiguous about whether a name is required. Help output:
```
[runtime-config command options]
          --name=        Runtime-Config name (default: '')
```

Observed behavior:
```
 2019-05-17 16:22:44  |2.3.1| |madlamp| owens in ~/workspace/monitoring-indicator-protocol
± md |master {1} ?:1 ✗| → bosh runtime-config
Using environment 'https://10.0.0.6:25555' as client 'admin'

No runtime config

Exit code 1
```

My assumption based on the help output was that running `bosh runtime-config` without the `--name` flag would result in all runtime configs. Instead, it seems to search for runtime configs without a name. I'm not sure if it's possible to have nameless runtime configs within Bosh, but the entire experience was confusing to me.

**Comment by markthemarkest** [comment]
To add to this, even something as simple as this:
```
No runtime config with name '$NAME'
```
would make things much more clear.

**Comment by belinda-liu** [comment]
Hey @markthemarkest,

Sorry for the late response. I'm a bit curious about your environment, how many runtime configs did you have when you saw this error? On a generic environment brought up using `bosh-deployment`, running `bosh runtime-config` gives me the most current runtime config, so I'm surprised that you're seeing different behavior. What version of the CLI are you using, with what director?
Nevertheless, I agree that the error message could be better. Once we have some reproduction steps we can definitely look into it more.

Thanks!

**Comment by aashah** [comment]
@ssapra made a commit to improve the output in dcd0a8c -

```
$ bosh runtime-config
Using environment 'https://10.0.0.6:25555' as client 'admin'

No default runtime config

Exit code 1
$ bosh runtime-config --name=foo
Using environment 'https://10.0.0.6:25555' as client 'admin'

No runtime config with name 'foo'

Exit code 1
```

Should be available when we cut a CLI soon.

Thanks!
