### ISSUE TITLE
`upload-stemcell` prints basic auth credentials when upload fails

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh-cli#529]
When stemcell upload with a basic auth url fails, the cli prints the error containing the url without redacting the creds:

https://github.com/cloudfoundry/bosh-cli/blob/a18c72307483843b5e190c383ff5e6835b3a8bf2/director/stemcells.go#L222

```
Task x

Task x | 05:00:27 | Update stemcell: Downloading remote stemcell (00:01:00)
                      L Error: Downloading remote stemcell failed. Check task debug log for details.
Task x | 05:01:27 | Error: Downloading remote stemcell failed. Check task debug log for details.

Task x Started  Mon May 20 05:00:27 UTC 2019
Task x Finished Mon May 20 05:01:27 UTC 2019
Task x Duration 00:01:00
Task x error

Uploading remote stemcell 'https://user:password@host/path/to/stemcell.tgz':
  Expected task 'x' to succeed but state is 'error'
```

Desired behavior:
The bosh cli redacts user and password before printing the error, similar how this https://github.com/cloudfoundry/bosh-cli/commit/e875aa00727a2abfec79d19fd635f69767b555bb fixed it for `upload-release`.

**Comment by friegger** [comment]
Fixed with https://github.com/cloudfoundry/bosh-cli/commit/ae1ba8166181d6269e08ea3289ef1e2b9c595749

**Comment by mfine30** [comment]
@friegger I'm going to close this since we've merged the PR and released a new CLI that fixes it. Please let us know if it comes up again though!
