### ISSUE TITLE
Windows binaries?

### ISSUE THREAD

**Issue by Fydon** [cloudfoundry/bosh-cli#53]
`bosh-init` didn't support Windows. The `bosh_cli` gem does work on Windows, although Windows wasn't listed on the [installation guide][1]. Is there a reason to not provide binaries for Windows?

Would it be the case of supplying a [`build-windows.yml`][3] with [`GOOS: windows`][2] or are there dependencies that require a Unix like environment?

[1]: https://bosh.io/docs/bosh-cli.html
[2]: https://github.com/golang/go/wiki/WindowsCrossCompiling
[3]: https://github.com/cloudfoundry/bosh-cli/blob/master/ci/tasks/build-linux.yml

**Comment by cppforlife** [comment]
@Fydon i think we can add that.

**Comment by Fydon** [comment]
@cppforlife Sorry I should have mentioned this in my pull request. s3 stores the Windows binary without the `exe` extension. I wasn't sure how you would like to add that, e.g an extra parameter to `build.sh`, a separate `build-windows.sh`, another task in the pipeline to rename, etc. I could make that change as well if you let me know what you'd like?

**Comment by Fydon** [comment]
As the new cli is using `tar` again, I've needed to amend the code to make the Windows version of `tar` usable. Namely I've needed to replace `\` with `/` in paths and `tar` can't reference a drive directly (only relative paths work) and so I've replaced my home directory path with `~`, as the home directory is used for `upload-release`. I'd recommend a [tar][1] library is used instead of `tar`, just as the Ruby version of the cli was changed to use a library.

Also Window prevents moving files that are currently open, which occurs [here][2] and [here][3], although closing the temporary file is causing the tests for Linux to fail. I'll create a pull request when I'll fixed that.

The compiler is currently only working with [bash][4].

[1]: https://golang.org/pkg/archive/tar/
[2]: https://github.com/cloudfoundry/bosh-cli/blob/master/installation/tarball/provider.go#L160
[3]: https://github.com/cloudfoundry/bosh-cli/blob/master/cmd/downloader.go#L78
[4]: https://github.com/cloudfoundry/bosh-cli/blob/master/installation/pkg/compiler.go#L96

**Comment by cppforlife** [comment]
@Fydon 0.0.149 was promoted to https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-0.0.149-windows-amd64.exe.

**Comment by bingosummer** [comment]
@Fydon You mentioned that `The compiler is currently only working with bash`. Is it resolved?

**Comment by Fydon** [comment]
@bingosummer Unfortunately not yet.
