### ISSUE TITLE
collection: fix `bosh curl`

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#539]
Hi everyone,

This is a collection issue to get `bosh curl` fixed. It has a number of problems that make a user's life hard every time they are trying to use this command. Some of these issues already have their individual ticket – in this case I'll link it here. It is an unfortunate combination of insufficient/incorrect help text and unexpected behavior when coming from 'real curl' or things like `cf curl`.

* [cli help missing all parameters](https://github.com/cloudfoundry/bosh-cli/issues/480)
* [data input is different than in `curl`](https://github.com/cloudfoundry/bosh-cli/issues/507)
* verbosity  cannot be enabled, like `curl -v`. There is `--show-headers`, but that's it.
* no `-L` for following redirects
  * also: [Director doesn't redirect correctly](https://github.com/cloudfoundry/bosh/issues/1253)

**Comment by h4xnoodle** [comment]
Thanks for bringing this to our attention @voelzmo.

AFAIK `bosh curl` isn't meant to be used heavily and thus does not provide full curl functionality. What kind of common tasks are being executed with `bosh curl`? Is this to avoid another command or is there a command missing?

**Comment by xtreme-conor-nosal** [comment]
We've fixed the cli help missing options, and the director stripping ports from redirects.

The http client is following redirects, so -L isn't needed.

For verbosity there's BOSH_LOG_LEVEL=DEBUG, which still redacts fields. 

We can continue the conversation for the data flag in #507, so we'll close this issue.

**Comment by voelzmo** [comment]
Thanks for pointing me to `BOSH_LOG_LEVEL`, not sure how I missed this for debugging `bosh curl`!
