### ISSUE TITLE
tls handshake timeout 

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/bosh-cli#54]
We see the following output when running a `bosh deploy` command.

```
Updating deployment:
  Getting task state:
    Performing request GET 'https://10.0.0.6:25555/tasks/26':
      Performing GET request:
        Get https://bosh-user:bosh-password@10.0.0.6:25555/tasks/26: net/http: TLS handshake timeout

Exit code 1
```

We notice that the bosh task still continues, its just that the CLI times out.

Also it would be nice to sanitize the output so that the bosh director's username and password isn't shown in the output.

**Comment by dpb587-pivotal** [comment]
Recent versions of `bosh` sanitize the credentials - try getting a newer version.

The timeout issue sounds like a connectivity issue, or maybe director became briefly overloaded and couldn't respond in time? If you ran `bosh task 26` from the environment was it able to reconnect?

**Comment by cppforlife** [comment]
@wfernandes it seems that we set timeout to 30s for tls handshakes: https://github.com/cloudfoundry/bosh-utils/blob/master/httpclient/default_http_clients.go#L42 (pretty good default). i think we can definitely improve retry logic around director/uaa client.

**Comment by cppforlife** [comment]
related: https://www.pivotaltracker.com/story/show/135739609

**Comment by cppforlife** [comment]
we believe that it was fixed by generic retry logic.
