### ISSUE TITLE
Cannot assign ~ or nil or null value to variable when using in bosh-ops files

### ISSUE THREAD

**Issue by sravankumar777** [cloudfoundry/bosh-cli#541]
In bosh ops file, we are tried to provide ~ or nil or null value for a variable substitution. 
However, bosh-cli complains about this variable substitution as "missing value within" for this particular variable. 

Example:
- type: replace
  path: /variable-submitted-with-nil-value
  value: ~ or nil or null

Is the direct substitution of this values is not supported bosh ops files?

We tried with character escaping provided from https://bosh.io/docs/cli-ops-files/#escaping.
But this escape characters, did not worked. 

We found a workaround method for providing ~ or nil or null value as below.
Declare a variable with name nil_value in any yaml file & use this variable for substitution in bosh ops file.

Example:
some-file.yaml

# use nil value for variable with ~
nil_value: ~

- type: replace
  path: /variable-submitted-with-nil-value
  value: ((nil_value))

This way it worked for us.

**Comment by h4xnoodle** [comment]
Hi @sravankumar777 

You can also use `remove` as a `type`.

```
- type: remove
  path: /variable-submitted-with-nil-value
```

Would this work for your case? Are you trying to remove the value completely?

**Comment by sravankumar777** [comment]
Hi @h4xnoodle,

Thanks for your response.
We are not trying to remove the value or property in bosh ops file.

We would like to retain this property or value with value assigned as **~** or **nil** or **null**

Thanks.

**Comment by xtreme-conor-nosal** [comment]
Is there a need for explicit vs implicit null?

**Comment by sravankumar777** [comment]
In our case, we require to provide the value of null explicitly.

**Comment by aashah** [comment]
This issue sits a bit further down in the `go-patch` library used by the CLI. The library requires a `value` for the replace operation - https://github.com/cppforlife/go-patch/blob/90228d47281247384683e5fded0f15afa3e5d29a/patch/op_definition.go#L68-L70.

Going forward, this isn't something we intend to support. The workaround you've found is probably the best way to achieve this.

\- Aakash && @ssapra
