### ISSUE TITLE
target should continue to be supported

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh-cli#55]
In order to provide a consistent developer experience, which promotes developer experience and the principal of least surprise, `bosh target` should allow for selecting a remote bosh server.  

As a typical bosh developer would use `cf target` and `uaac target` on a daily basis, changing the syntax to something not consistent with that does not appear to further bosh goals.

**Comment by cppforlife** [comment]
@sharms we've decide to follow fly's explicitness and require to specify environment (`-e`) and deployment (`-d`). you can also use BOSH_ENVIRONMENT and BOSH_DEPLOYMENT environment variables (with direnv) to simulate statefulness per terminal session.

**Comment by sharms** [comment]
I can't find references in `uaac` and `cf-cli` which show them moving towards that shared syntax.  My issue is based on ecosystem consistency, where `bosh`, `cf`, `fly`, and `uaac` share common tenants to ensure they can be used in a simple, expected manner.  

For example, Linux and Posix define simple primative system calls such as `open`, rather than one calling it `open-...` etc.  There are only ~300 system calls and they are consistent across the toolset.

**Comment by mfine30** [comment]
Seems like this thread has gone a little bit stale. AS DK mentioned above, we're not planning to change this behavior, as we're moving towards the explicitness of declaring a target in each command. If you'd like to continue the conversation, feel free to reopen.
