### ISSUE TITLE
Using bosh 6.2.0 does not work with socks5 proxy

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/bosh-cli#552]
I just updated to bosh-cli 6.2.0 and I usually setup a ssh proxy and set BOSH_ALL_PROXY to be this ...

BOSH_ALL_PROXY=socks5://localhost:60031

This works with bosh-cli 6.1.0 but hangs with bosh-cli 6.2.0

Working version is this ...

➜  ~ bosh -v
version 6.1.0-9c1c210c-2019-09-18T17:33:48Z

➜  ~ /usr/local/bin/bosh.new -v                                                                          <<<
version 6.2.0-e5ce64ab-2020-01-16T19:22:06Z

Fails!

**Comment by jfmyers9** [comment]
@andrew-edgar Thanks for bringing this to our attention. I was able to reproduce the problem and will hopefully have a fix for the issue soon.

**Comment by andrew-edgar** [comment]
@jfmyers9 that's good news!  thanks

**Comment by andrew-edgar** [comment]
works like a charm now!  thanks
