### ISSUE TITLE
bosh create-env does not pass tags to CreateVM call

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-cli#553]
In https://github.com/cloudfoundry/bosh-aws-cpi-release/issues/93 we asked for the ability to have tags passed to AWS during the RunInstances API call, as we have security policies preventing VM creation unless certain tags are included in that call. It also helps us restrict the IAM policy assigned to BOSH so that it only has scope over its own VMs. 

This was implemented in the aws-cpi, and in the bosh director code, but when we try to do a `bosh create-env` using the latest bosh CLI (6.2.1-a28042ac-2020-02-10T18:40:57Z), RunInstances does not have any tag info included.

I think what might be needed is to apply the changes from https://www.pivotaltracker.com/n/projects/956238/stories/167657971 to the bosh-cli, but I'm basing that off of https://github.com/cloudfoundry/bosh-cli/blob/0ee5b2abedb27e521dc6e70719023e7b382cab79/deployment/vm/manager.go#L108-L127 and am not sure if that would actually be the code executed in create-env.

**Comment by ssapra** [comment]
There are two ways to pass tags to the BOSH Director.

1. The top-level key `tags` in the deployment manifest will be included in `SetVMMetadata` which sets the metadata after the VM is created.
2. The property `env[bosh][tags]` in the director's resource pool will be passed along to the CPI in its `create_vm` method which allow the tag to be created on the VM during creation.
