### ISSUE TITLE
bosh-cli should use login instead of default log-in

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh-cli#56]
Every other tool in the ecosystem currently uses the verb `login`.  While it is aliased, it is inconsistent with all other Pivotal tool verbs: `fly login`, `cf login`, `bosh login` etc

Choosing new verbs without purpose which are inconsistent with other tools in the same ecosystem is a waste of time, effort and hinders developer adoption.

**Comment by cppforlife** [comment]
`bosh login` works as of https://github.com/cloudfoundry/bosh-cli/releases/tag/v0.0.101

**Comment by sharms** [comment]
Unfortunately the default help command references `log-in`, so while `login` does work it is neither obvious nor congruent with the other tooling, which call has a help document referencing `login`.

**Comment by sharms** [comment]
Reference:
```
root@boshtest:/tmp/build/8e72821d# bosh-cli -e env
Please specify one command of: add-blob, alias-env, attach-disk, back-up, blobs, cancel-task, clean-up, cloud-check, cloud-config, cpi-config, create-env, create-release, delete-deployment, delete-disk, delete-env, delete-release, delete-snapshot, delete-snapshots, delete-stemcell, delete-vm, deploy, deployment, deployments, disks, environment, environments, errands, events, export-release, finalize-release, generate-job, generate-package, help, ignore, init-release, inspect-release, instances, interpolate, locks, log-in, log-out, logs, manifest, recreate, releases, remove-blob, reset-release, restart, run-errand, runtime-config, scp, snapshots, ssh, start, stemcells, stop, sync-blobs, take-snapshot, task, tasks, unignore, update-cloud-config, update-cpi-config, update-resurrection, update-runtime-config, upload-blobs, upload-release, upload-stemcell or vms
```
