### ISSUE TITLE
Consider enhancements for blobstores via git-lfs (i.e. lowering 'barrier to blobstore')

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/bosh-cli#567]
In order to lower the maintenance burden (or barrier to entry entirely) for boshrelease maintainers, consider general workflow enhancements to enable creating bosh releases via blobs without an IaaS-provided blobstore-- specifically, `git-lfs`.

## background

I'm intrigued by this starkandwayne blog post (https://www.starkandwayne.com/blog/bosh-releases-with-git-lfs/) and then this corresponding github issue (https://github.com/cloudfoundry/bosh-cli/pull/395)

There are boshreleases which require externally-sourced blobs that aren't _huge_, but wouldn't be appropriate to cram into the `src/` dir via regular `git`. But creating a blobs bucket is heavyweight enough that it deters creating a boshrelease altogether. Or creating a corporate bucket is a pain because you have to get approvals for S3 and S3 hardcoded credentials and all that, bleh. Having to use an IaaS-provided S3-compatible blobstore for a boshrelease makes maintaining a boshrelease (namely a smaller one) kind of niche and a pain, which can be disappointing when managing blobs are the biggest hassle to an otherwise straightforward boshrelease--

For example: I have a lil' [`vector-boshrelease`](https://github.com/timberio/vector) which operationalizes and uses the built `vector` binary. It's only ~60MB decompressed, and it's the only binary that's used. It wouldn't be appropriate to commit it to `src/` directly (though I do currently), and it'd be such a pain to create and maintain an S3 bucket for just that one blob and for any storage when creating a final package/release. I'd like to keep things as close to the `git` source as possible-- all the `job` code is in git, the `vendir` config to download the blob is in git, the ci/cd is in git, issue tracking, base manifests, etc. etc., and the built `vector-boshrelease-x.y.z.tgz` are all in git (or github releases), and it feels like the last step would be to have the boshrelease blobstore be close to `git` as well, presumably via `git-lfs` (which I know isn't perfect, but it's lower barrier-to-entry than needing an AWS / google cloud account).

I think there are other examples of this where there would be user-driven boshreleases of {some product, like vector, splunk, x, y, z}, but the external blobstore requirement turns folks away, or turns folks to do things like "you have to do `bosh create-release` yourself".

## action

With all this said, to summarize, this is a general issue asking **if the bosh/bosh-cli team would consider creating or prioritizing workflow stories to enable enhancing the `local` blobstore provider so boshrelease maintainers have the option to use tools like `git-lfs` to manage blobs and create actual (final) boshreleases as a first-class feature** (rather than as something "you _can_ do if you hack around it").

... or, if not a first-class feature, then at least maybe reconsidering if there are things that can be done to improve hacking around releases which use `local` as a blobstore provider (like https://github.com/cloudfoundry/bosh-cli/pull/395 ?)

Thanks again for any time and consideration, I know you all are busy, and I appreciate the time anyone puts into reading this, even if the answer is "no" 😉 👍

**Comment by rkoster** [comment]
Thanks for submitting this issue, it helped me rediscover: https://github.com/cloudfoundry/bosh-cli/pull/395 (reencountered this exact issue in the wild today).
