### ISSUE TITLE
Homebrew formulae for install

### ISSUE THREAD

**Issue by christopinka-smarsh** [cloudfoundry/bosh-cli#571]
Would be nice to have a homebrew formula for installing. https://docs.brew.sh/Formula-Cookbook#:~:text=A%20formula%20is%20a%20package,provides%20various%20Homebrew%2Dspecific%20helpers.

**Comment by ystros** [comment]
Hi @christopinka-smarsh!

We actually provide a Homebrew tap for installing Cloud Foundry related CLIs, including the latest version of the BOSH CLI. See:
https://github.com/cloudfoundry/homebrew-tap/
https://github.com/cloudfoundry/homebrew-tap/blob/HEAD/bosh-cli.rb

I'm unsure if this needs to / should go in Homebrew core.
