### ISSUE TITLE
Unable to go get bosh-cli package

### ISSUE THREAD

**Issue by Anthonyhawkins** [cloudfoundry/bosh-cli#572]
I need to work on a contribution to the Terraform provider for cloud foundry which lists this package as a dependency.  Upon trying to go get the package I run into the following error:
**What's Wrong**
```
bash-3.2$ go get -d github.com/cloudfoundry/bosh-cli
go: downloading github.com/cloudfoundry/bosh-cli v0.0.159
go: downloading github.com/cloudfoundry/bosh-cli v6.4.1+incompatible
go get: github.com/cloudfoundry/bosh-cli@v6.4.1+incompatible: stream error: stream ID 9; NO_ERROR
```

**What's Expected**
I expect the package to be installed similar to this example from Google
```
bash-3.2$ go get github.com/google/codesearch/index
go get: added github.com/google/codesearch v1.2.0
```

**Versions of Tools listed as Dependencies according to the README**
```
bash-3.2$ go version; hg version; git version
go version go1.16.4 darwin/amd64

Mercurial Distributed SCM (version 5.9)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2021 Olivia Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

git version 2.31.1
```

**Comment by rkoster** [comment]
If you want to use the bosh cli, please follow the installation instructions as documented here: https://bosh.io/docs/cli-v2-install/.

This is also mentioned in the README: https://github.com/cloudfoundry/bosh-cli#install

Instruction on how to use it as a library are documented here: https://github.com/cloudfoundry/bosh-cli#client-library
