### ISSUE TITLE
Cannot update go module to use higher version then v6.4.1

### ISSUE THREAD

**Issue by FelisiaM** [cloudfoundry/bosh-cli#576]
## Background 

We use `github.com/cloudfoundry/bosh-cli` v6.4.1 as a Go module dependency in [ODB](https://github.com/pivotal-cf/on-demand-service-broker/blob/60daca88b6fde74867389cc4a4ef9c33970fc08f/go.mod#L10) and it is already labelled as `incompatible`.

When attempting to update it use the latest v6.4.7 it fails.

### Steps to reproduce:

1. In a repo that is already using v6.4.1 run 
  ```
  go get -d github.com/cloudfoundry/bosh-cli@v6.4.7
  ``` 

### Expected behaviour:
- It should update to the latest v6.4.7

### Actual behaviour:
- It fails with an error ` invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v6`

See: 
```
go get -d github.com/cloudfoundry/bosh-cli@v6.4.7
go get: github.com/cloudfoundry/bosh-cli@v6.4.7: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v6
```

### Issue
Since `bosh-cli` has moved to use Go modules and the latest Go version and it releases a major version higher than 1 it should provide that version as a `bosh-cli/v6` module.  This is described in [this](https://golang.org/doc/modules/major-version) Go modules doc. 
What that means is that the module should be declared including the major version in the name and it should be used in all dependant code with the major version in the name as well.

That would allow us to do:
```
go get github.com/cloudfoundry/bosh-cli/v6@v6.4.7
``` 

Our team dealt with this issue in the [`brokerapi`](https://github.com/pivotal-cf/brokerapi) repo and have written up [this](https://github.com/pivotal-cf/brokerapi/wiki/Releasing-new-BrokerAPI-major-version) summary that might be useful if you decide to  go down this road.

### Request

- We would like to use the latest BOSH CLI since it's the one getting all the updates. Do you plan on supporting the usage of the latest bosh-cli as a Go mod package? 

---

**Alternative** `go get` commands that I have tried:
```
go get -d github.com/cloudfoundry/bosh-cli
```

Result:  It makes changes only in the indirect required dependencies.

**Comment by rkoster** [comment]
Was able to bump to the latest bosh-cli in my local copy of the on-demand-service-broker using:
```
