### ISSUE TITLE
BOSH CLI commands to automatically add diego cell or Create VM on which containers can be deployed on .

### ISSUE THREAD

**Issue by viju2008** [cloudfoundry/bosh-cli#577]
Detailed Description
BOSH CLI commands to automatically add diego cell or Create VM on which containers can be deployed on .

Currently a new diego cell has to be provisioned manually on Vsphere environment

Context
. We wish to automate it using scripts so that based on load a new diego cell can be provisioned automatically on Vsphere/AWS/Azure using the respective CPI 

This will help users to not only scale containers but also the underlying VMs on which containers are deployed on

Possible Implementation
Bosh CLI could provide commands to provision new diego Cells, so that they can be provisioned by scripts

Complexity
Medium

**Comment by beyhan** [comment]
We discussed this topic in cloudfoundry/bosh-deployment#426.
