### ISSUE TITLE
[Question] About release v6.4.8

### ISSUE THREAD

**Issue by chenrui333** [cloudfoundry/bosh-cli#578]
👋  Just to check if the v6.4.8 is intended to be the latest release. If so, it would be better to mark the release as `latest release`. Thanks!

Also, it looks like the commit got re-tagged from the latest release which caused the checksum mismatch for [go 1.17.3 update](https://github.com/Homebrew/homebrew-core/pull/88775) on the homebrew side.

**Comment by beyhan** [comment]
@rkoster the release `v6.4.8` is in `draft` mode. Is it a manual process to publish it or did some automation break here?

@chenrui333 I couldn't follow on the second part. What do you mean the "commit got re-tagged from the latest release..."?

**Comment by rkoster** [comment]
v6.4.8 has been published, thanks @chenrui333 for bringing this up. Not really sure what to do about the checksum mismatch. Could you maybe describe the solution you are seeing for the case where the re-tagging has already happened? Or is this more a heads up to not re-tagg going forward?

**Comment by iMichka** [comment]
Hi. I'm also a homebrew maintainer.
Thanks for the information.

Ideally you should not retag, if possible. Some projects use "x.y.z.RC" tags, or "alpha/beta" tags. You could also mark it as "pre-release" in GitHub too; with should trigger a warning on our side.

Closing here as the situation has been mitigated.

**Comment by carlocab** [comment]
Re-tags should be avoided where possible. Where avoiding them isn't possible, the re-tag should be made as conspicuous as possible.

See the [Git docs](https://git-scm.com/docs/git-tag#_on_re_tagging) for more in this; it actually has some rather strong words about re-tagging.

**Comment by rkoster** [comment]
Closing issue since it has been mitigated on the homebrew side of things
