### ISSUE TITLE
Release binaries for arm64

### ISSUE THREAD

**Issue by odidev** [cloudfoundry/bosh-cli#591]
Hi team,  

  

I was trying to build **relintdockerhubpushbot/cf-deployment-concourse-tasks** image on arm64 platform but it was failing as **cloudfoundry/bosh-cli** binary is not available for arm64. 

Do you have any plans to release **cloudfoundry/bosh-cli** binary for arm64? 

It will be very helpful if cloudfoundry/bosh-cli binaries is released for arm64.

**Comment by lnguyen** [comment]
Hello are you talking about arm64 for apple silicon? We release arm64 for darwin - https://github.com/cloudfoundry/bosh-cli/releases/tag/v6.4.14

**Comment by lnguyen** [comment]
@odidev closing as we cut arm64 bosh-cli
