### ISSUE TITLE
`--ca-cert` should have better error handling when the path given is bad

### ISSUE THREAD

**Issue by JesseTAlford** [cloudfoundry/bosh-cli#6]
`--ca-cert` might have a bad path.
- it might point to a directory instead of a file
- it might point to an empty file
- it might point to an invalid cert
- it might point to a nonexistent file

There should be a useful error for each of these.  Currently, instead of handling all the separate cases, it seems to behave as if there are only two failure modes:
- If it points to a non-existent file, it always displays:

```
gosh --ca-cert=/tmp/nonexistent/file --user=admin --password='xxx' environment
Current environment is 'xxx'

Validating Director connection config:
  Parsing CA certificate: Missing PEM block

Exit code 1
```
- If it points to an invalid/empty file or a directory, it always silently attempts to use the file:

```
gosh --ca-cert=/tmp --user=admin --password='xxx' environment
Current environment is 'xxx'

Fetching info:
  Performing request GET 'https://xxx:25555/info':
    Performing GET request:
      Get https://admin:xxx@xxx:25555/info: x509: certificate signed by unknown authority

Exit code 1
```

Interestingly, this is also a shorter error than you'd get by entirely excluding the flag:

```
    Performing GET request:
      Get https://...xxx:25555/releases: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "serial:11221279690464167074")

Exit code 1
```

This was seen in version 0.0.54-a29688a-2016-09-06T16:34:2.

**Comment by cppforlife** [comment]
--ca-cert flag handling was improved in later versions.
