### ISSUE TITLE
Support generation of AES keys

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh-cli#60]
Manifests often need encryption keys (e.g. a 128-bit hex-encoded AES key). I don't have any favorite keys, so wouldn't mind (and would in fact love) if bosh created keys for me!

Maybe even getting to specify the algorithm, encryption mode, encoding, and key length would be snazzy.

Thank you so very much,
@wendorf & @drich10

**Comment by cppforlife** [comment]
@wendorf any concrete places?

**Comment by cppforlife** [comment]
cc @pivotal-danjahner @ishustava would be nice to have a PR to config-server since this type is needed for bootstrapping.

**Comment by pivotal-danjahner** [comment]
I've created a story for my team to submit the requested PR.

**Comment by pivotal-danjahner** [comment]
We’ve decided to change the AES key value provided by the user from a hex string to a random string that is used to derive a key to match the behaviour of other CF components. If CredHub is the only use case for the hex string, you should be able to close this issue.
