### ISSUE TITLE
TLS handshake failure occurs when downloading bosh-release

### ISSUE THREAD

**Issue by kei-yamazaki** [cloudfoundry/bosh-cli#602]
## Description

Since about 2022/10/4, I got a `remote error: tls: handshake failure` when trying to download bosh-release, which uses a let's encrypt certificate, and it fails.

## Error log

```shell
bosh create-env <some args>

Started validating
  Downloading release 'bosh'... Finished (00:00:40)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bpm'... Finished (00:00:16)
  Validating release 'bpm'... Finished (00:00:01)
  Downloading release 'bosh-openstack-cpi'... Failed (00:00:01)
Failed validating (00:01:23)
Failed to download from 'https://bosh.io/d/github.com/cloudfoundry/bosh-openstack-cpi-release?v=44':

  Unable to download:
    Performing GET request:
      Get "https://bosh.io/d/github.com/cloudfoundry/bosh-openstack-cpi-release?v=44": remote error: tls: handshake failure
Exit code 1
```

## Investigation

Just at the time and date of the error, bosh.io's lets encrypt certificate was being renewed.

```shell
$ openssl s_client -connect bosh.io:443 < /dev/null 2> /dev/null | openssl x509 -noout -subject -dates
subject=CN = *.bosh.io
notBefore=Oct 4 01:52:31 2022 GMT
notAfter=Jan 2 01:52:30 2023 GMT
```

I suspect the problem is on the bosh-cli or golang library side, since I can download `https://bosh.io/d/github.com/cloudfoundry/bosh-openstack-cpi-release?v=44` via wget etc. I am not sure what the problem is, but I am sure that it is a golang library issue.

## bosh-cli version

6.4.1

**Comment by rkoster** [comment]
So you are saying that the bpm release download was started before Oct 4 01:52:31 2022 GMT?

**Comment by kei-yamazaki** [comment]
No. The bpm download was done after Oct 4 01:52:31 2022 GMT.

Additional information, TLS handshake failure does not seem to occur with bosh-cli version 7.0.1.
