### ISSUE TITLE
Specifying instances by index ambiguous

### ISSUE THREAD

**Issue by risicle** [cloudfoundry/bosh-cli#605]
Using bosh-cli 7.1.0 on macos 12 (against BOSH 276.1.0), we noticed something that caught us off guard, and doesn't seem to be noted/acknowledged anywhere.

Because bosh-cli both attempts to support specifying instances by-index *and* by-guid-prefix, trying to e.g ssh in to router instance number 29 via `bosh ssh router/29` will actually log you in to any instance you might happen to have with a guid beginning `29...` in preference to the instance with index 29. It's not at all obvious when this has happened and could lead to some serious mistakes.

**Comment by beyhan** [comment]
I couldn't reproduce this. I tested with bosh CLI version `7.0.1-799538d1` (there a no [noticeable changes](https://github.com/cloudfoundry/bosh-cli/compare/v7.0.1...v7.1.0) between `7.0.1` and `7.1.0`) and bosh director version `v276.0.0`. I had three instances:
```
test/13099bcd-f2c7-4472-8359-66ab398e9b4a
test/2aa1bea1-7c74-4f50-87c3-ac435a47c41b
test/ffab33ac-c864-4d47-95b1-7126f320374d
```
With `bosh -d test ssh test/1` I landed in the `test/2aa1bea1-7c74-4f50-87c3-ac435a47c41b` instance. With bosh `bosh -d test ssh test/2` I landed in the `test/ffab33ac-c864-4d47-95b1-7126f320374d` instance. So the indexes were preferred.

Also looking into the bosh CLI code [here](https://github.com/cloudfoundry/bosh-cli/blob/c2ae4c63115c6bc6532773281f46f952ee560a65/director/ssh.go#L167-L186) and in bosh director [here](https://github.com/cloudfoundry/bosh/blob/main/src/bosh-director/lib/bosh/director/jobs/ssh.rb#L101-L119) it should try to match the value after `<job >/...` to an index when it is only with digits (this [line](https://github.com/cloudfoundry/bosh/blob/main/src/bosh-director/lib/bosh/director/jobs/ssh.rb#L110)). Which director version do you use?

**Comment by risicle** [comment]
This is director version 276.1.1. I'm having trouble reproducing it myself but I saw it with my own eyes on a colleague's machine. Will see if I can get them to reproduce it.

**Comment by risicle** [comment]
Neither of us can reproduce this now so I'm going to close this issue. But I'm still suspicious that there may be an issue here.
