### ISSUE TITLE
Updating package via bosh `vendor-package --prefix` does not honor prefix on dependent packages

### ISSUE THREAD

**Issue by jrussett** [cloudfoundry/bosh-cli#606]
## Summary

When you **update** a package via `bosh vendor-package --prefix` and the desired package has dependent packages, the dependent packages are not updated with a prefix.

#### Note
On the first invocation of `bosh vendor-package` with `--prefix`, the desired package **and** its dependent packages will all be vendored with a prefix. This error only occurs when re-vendoring the package to update it. 

## Steps to Reproduce
For this specific example, we will use the [`healthchecker` package](https://github.com/cloudfoundry/healthchecker-release/blob/develop/packages/healthchecker/spec#L5), which requires the `golang-1-linux` package to compile the binary. The `healthchecker` package is intended to be vendored into releases like `silk`, `cf-networking`, and `garden-runc`.

When vendoring another bosh package with a PREFIX that depends one of the `golang-*-linux` packages, the `golang-*-linux` will be vendored with prefix (e.g. `PREFIX-golang-*-linux`).

If I run the following
```bash
cd ~/workspace/silk-release
bosh vendor-package healthchecker ~/workspace/healthchecker-release --prefix silk
```

Then I end up with the following packages:
```bash
silk-healthchecker/
silk-golang-1-linux/
```

Where `silk-healthchecker/spec.lock` looks something like:
```yaml
name: silk-healthchecker
fingerprint: 11fec354b909c9d6463e9edd3c92bb7c01423eb0df21c2f7ebe742c5d6f34e28
dependencies:
- silk-golang-1-linux
```

### Running `bosh vendor-package --prefix` again to update the package
Now, when I want to update the `healthchecker` package, I see that the `silk-golang-1-linux` dependency is renamed, removing the prefix entirely!

```diff
diff --git a/packages/silk-golang-1-linux/spec.lock b/packages/silk-golang-1-linux/spec.lock
 name: silk-golang-1-linux
-fingerprint: b55bf89806a951e9b3812e987bd526ef931550ab01360f002b38e00d83f8296b
+fingerprint: db9120088b5e3ad5c6f52742a8f1c21a9b234a3b79cf916d48b22660c7ac422e

diff --git a/packages/silk-healthchecker/spec.lock b/packages/silk-healthchecker/spec.lock
 name: silk-healthchecker
-fingerprint: 11fec354b909c9d6463e9edd3c92bb7c01423eb0df21c2f7ebe742c5d6f34e28
+fingerprint: d823a8fec682820aa8e56d115e3d0aa15c309e2120dc183854b80e5e69fb3dcf
 dependencies:
-- silk-golang-1-linux
+- golang-1-linux
```

### Expected Results
When I'm updating the `healthchecker` package via `bosh vendor-package --prefix`, only the `fingerprints` indicating the updated package should change. The names of the dependencies should stay the same:

```diff
diff --git a/packages/silk-golang-1-linux/spec.lock b/packages/silk-golang-1-linux/spec.lock
 name: silk-golang-1-linux
-fingerprint: b55bf89806a951e9b3812e987bd526ef931550ab01360f002b38e00d83f8296b
+fingerprint: db9120088b5e3ad5c6f52742a8f1c21a9b234a3b79cf916d48b22660c7ac422e

diff --git a/packages/silk-healthchecker/spec.lock b/packages/silk-healthchecker/spec.lock
 name: silk-healthchecker
-fingerprint: 11fec354b909c9d6463e9edd3c92bb7c01423eb0df21c2f7ebe742c5d6f34e28
+fingerprint: d823a8fec682820aa8e56d115e3d0aa15c309e2120dc183854b80e5e69fb3dcf
```

## Additional Text Output, Screenshots, contextual information (optional)

Adding `--prefix` to `bosh vendor-package`: https://github.com/cloudfoundry/bosh-cli/pull/603

**Comment by ramonskie** [comment]
i never tested this with a package that also had a dependency.
i will look in to it.

**Comment by jpalermo** [comment]
Hey @jrussett, can you try v7.1.3 and see if it fixes the problem?

**Comment by jrussett** [comment]
Hey @jpalermo 

I just tested this in our CI after confirming our docker image had the new bosh cli. The BOSH cli was able to successfully vendor the package with a prefix without clobbering the dependencies! ✅
https://github.com/cloudfoundry/garden-runc-release/commit/46efe910f7d3e9a04e4342a5655bed1dee7df1f2

Thank you all!
