### ISSUE TITLE
Cannot use a -o file to replace a key with an empty string

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh-cli#64]
If my manifest YAML looks like this:

```
---
great_singer:
  first_name: madonna
```

...but my release needs to know my great singer's last name, I might want to add a -o file to set her last name to an empty string:

```
---
- type: replace
  path: /great_singer/last_name?
  value: ""
```

When I try to build the final YAML file with `bosh int manifest.yml -o madonna_is_very_special.yml`, this will unfortunately error:

```
invalid argument for flag `-o, --ops-file' (expected []cmd.OpsFileArg): Deserializing ops file 'madonna_is_very_special.yml': yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `` into *interface {}

Exit code 1
```

I would like this to succeed and give me the following final YAML:

```
---
great_singer:
  first_name: madonna
  last_name: ""
```

Cheers,
@wendorf and @drich10

**Comment by cppforlife** [comment]
Looks like a bug in go-yaml: https://github.com/cppforlife/go-patch/blob/master/patch/yaml_compat_test.go#L12

**Comment by cppforlife** [comment]
Ideally this would get fixed in go-yaml.

**Comment by cppforlife** [comment]
Opened following issue: https://github.com/go-yaml/yaml/issues/229

**Comment by cppforlife** [comment]
Fixed in https://github.com/cloudfoundry/bosh-cli/releases/tag/v0.0.131
