### ISSUE TITLE
bosh-cli didn't read the trailing zero '0' of stemcell version in manifest

### ISSUE THREAD

**Issue by scottgai** [cloudfoundry/bosh-cli#643]
1) stemcell version 1.360 is set in manifest
`---
name: testvm
stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: 1.360
`
2) `bosh deploy` command shows '1.36' instead of '1.360'
`$ bosh -d testvm deploy testvm.yml
Using environment '10.225.31.65' as client 'ops_manager'

Using deployment 'testvm'

+ stemcells:
+ - alias: jammy
+   os: ubuntu-jammy
+   version: '1.36'`

And the command finally failed with complaint of non-existent stemcell version 1.36
`Task 56

Task 56 | 00:47:23 | Preparing deployment: Preparing deployment (00:00:00)
                   L Error: Stemcell version '1.36' for OS 'ubuntu-jammy' doesn't exist
Task 56 | 00:47:23 | Error: Stemcell version '1.36' for OS 'ubuntu-jammy' doesn't exist

Task 56 Started  Wed Mar 20 00:47:23 UTC 2024
Task 56 Finished Wed Mar 20 00:47:23 UTC 2024
Task 56 Duration 00:00:00
Task 56 error

Updating deployment:
  Expected task '56' to succeed but state is 'error'

Exit code 1`

3) It could work if enclose stemcell version with either single quote or double quote. For example,
`---
name: testvm
stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: "1.360"
`

**Comment by jpalermo** [comment]
Yeah, this is a yaml "feature" not really a bosh-cli problem.

An unquoted number with a single dot in yaml is treated as a floating point number so the "0" is extra data and thrown away.
