### ISSUE TITLE
[feature request] If an ops-file produces an error, tell me which file and which line

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-cli#68]
That would be more helpful than
```
Expected to find a map key 'openstack' for path '/instance_groups/name=bosh/properties/openstack'

Exit code 1
```

**Comment by jfmyers9** [comment]
Going to close and reopen to generate a tracker story.

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty

**Comment by aashah** [comment]
Hey, we took a look at this issue and think it ought to be discussed with our PM. We gave the story a label (`pre-ipm`) to ensure we discuss it this coming Friday.

Thanks,
Aakash & @jaresty
