### ISSUE TITLE
`update-cloud-config` (and `update-runtime-config`) should show a diff before confirmation

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/bosh-cli#7]
When running `bosh deploy`, we get a nice diff of the changes we are going to apply:

```
gosh deploy -d cf --var-files=deployments/cf/env-vars.yml  deployments/cf/cf-deployment.yml
Using environment '104.198.99.5' as user 'admin'

Using deployment 'cf'

  networks:
  - name: private
    subnets:
    - range: 10.0.16.0/20
      cloud_properties:
+       ephemeral_external_ip: true
    - range: 10.0.32.0/19
      cloud_properties:
+       ephemeral_external_ip: true
```

When running `gosh update-cloud-config`, however, we do not see any diff; just a confirmation question:

```
gosh update-cloud-config deployments/cf/cloud-config.yml
Using environment 'xxx' as user 'admin'

Continue? [yN]: y

Succeeded
```

It would be nice if we could see a diff of the cloud config when we are updating it, rather than having to wait until running `bosh deploy` to see the changes. Of course, the new properties will not be applied to existing deployments until `deploy` is run, so perhaps the diff should note that, too.

```
gosh --version
version 0.0.54-a29688a-2016-09-06T16:34:29Z

Exit code 1
```

**Comment by voelzmo** [comment]
Just adding cpi-config here for the record.

**Comment by tjvman** [comment]
This behavior is present in [CLIv2.0.30](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.30). Closing.

**Comment by geofffranks** [comment]
This might warrant being added to the release notes of v2.0.30?
