### ISSUE TITLE
Failing BOSH ssh never times out or clean up

### ISSUE THREAD

**Issue by tushar-dadlani** [cloudfoundry/bosh-cli#70]
We have a CI task that runs `bosh ssh` every 15 minutes we noticed that if you do something like `gobosh ssh cell_z1 "uptime"` and if it cannot complete the running of the ssh command on any one cell due to any reason, the task never times out. One of these tasks ran for over 5 hours.

Also below is a snapshot from `htop` output and there are a bunch of defunct `userdel` processes on the cell that failed execution of the command that ran through ssh. 

``` 411 root       10 -10 30520  2652  2376 D  0.0  0.0  0:00.00 userdel -r bosh_3bcf42f4653a4c2b
  464 root       10 -10 30520  2560  2280 D  0.0  0.0  0:00.00 userdel -r bosh_5acd16925af14659
  674 root       10 -10 30520  2664  2376 D  0.0  0.0  0:00.00 userdel -r bosh_50c65c57e87f446a
 1083 root       10 -10 30520  2620  2348 D  0.0  0.0  0:00.00 userdel -r bosh_07cc71693f4e43dc
 1255 root       10 -10 30520  2564  2280 D  0.0  0.0  0:00.00 userdel -r bosh_aa086c7010674683
```

All the userdel processes have bosh-agent as their parent.

/cc @supertopher

**Comment by cppforlife** [comment]
@tushar-dadlani per our debug session, it's not that the CLI didnt clean up (it does) but rather userdel is in the disk wait step which cannot be interrupted. unfortunately we cant even kill -9 them.

**Comment by jfmyers9** [comment]
I'm going to close this due to inactivity. Please feel free to reopen if you have further questions.
