### ISSUE TITLE
`bosh create-release` does not follow symlinks (in jobs) when generating tarball

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/bosh-cli#79]
When we generate a bosh release of the [loggregator]() release, with this CLI and try to deploy on Windows, it complains that the templates for `metron_agent_windows` are missing.

The templates for that job are symlinked with the templates found in `metron_agent`. That way we can edit once and it affects both jobs.

We are able to verify that the symlinks work with the old `bosh_cli` Ruby gem with no problems.

Steps to reproduce:

1.

```
git clone https://github.com/cloudfoundry/loggregator
cd loggregator
bosh create-release --tarball=loggregator.tgz
```

2. Untar `loggregator.tgz/jobs/metron_agent_windows.tgz`

3. Notice that `templates` has symlinks that go nowhere.

**Comment by tjvman** [comment]
This behavior has been added in [version 2.0.28](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.28). Closing.
