### ISSUE TITLE
Support turning off director certificate validation

### ISSUE THREAD

**Issue by sslavic** [cloudfoundry/bosh-cli#82]
With bosh cli v2, release 0.0.141, there seems to be no documented way to turn off validation of director certificate. Please support this switch and have it documented.

At least please support switch that would accept self signed certificates.

Currently one can get these errors instead:
```
gosh deployments -e https://localhost:25555
Fetching info:
  Performing request GET 'https://localhost:25555/info':
    Performing GET request:
      Get https://localhost:25555/info: x509: certificate signed by unknown authority

Exit code 1
```

**Comment by cppforlife** [comment]
We've opted in to always strictly verify certificates for the Director and associated services. To discourage people from deploying Director in less secure configurations.

It's perfectly fine to use self signed certs as long as they are generated with matching common name and SANs.

If you don't want to use cloudfoundry/bosh-deployment repo, you can use CLIv2 to generate just the certificates that will work. Here is an example:

```
# Define which values to generate

$ cat certs-tpl.yml
variables:
- name: default_ca
  type: certificate
  options:
    common_name: ca
- name: director_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: ((internal_ip))
    alternative_names: [((internal_ip))]

# Generate certs and save them to certs.yml

$ bosh interpolate certs-tpl.yml -v internal_ip=1.2.3.4 --vars-store certs.yml --var-errs

# Either look at certs.yml or pull out values programatically

$ bosh interpolate certs.yml --path /director_ssl/ca
$ bosh interpolate certs.yml --path /director_ssl/certificate
$ bosh interpolate certs.yml --path /director_ssl/private_key
```

**Comment by cnelson** [comment]
FWIW, we use certstrap to generate our bosh certs.  Here is a minimal example for generating a cert chain that will work with the v2 cli:

 	certstrap init -o 'Your Organization' -ou 'Your Unit' --cn 'bosh-ca' --passphrase ''
	# replace test-net-1 address with ip of your bosh director
	certstrap request-cert --cn 'bosh' --ip '192.0.2.123' --passphrase ''
	certstrap sign 'bosh' --CA 'bosh-ca' --passphrase ''

**Comment by cppforlife** [comment]
Closing per explanation above.
