### ISSUE TITLE
`bosh cancel-task` returns success before task is `cancelled`

### ISSUE THREAD

**Issue by drich10** [cloudfoundry/bosh-cli#88]
Currently when you execute `bosh cancel-task task-id` the command returns success once the director has started to attempt the cancellation of the task. This is confusing to the user as one could reasonably assume the task has completed cancellation on return of the above command. Could the behavior change such that the command does not return until cancellation has completed? Possibly even attaching to the task so the user is able to see what is currently in progress?

Before:
```
bosh cancel-task task-id
Using environment 'director.example.com' as client 'boss'

Succeeded
```

After:
```
bosh cancel-task task-id
Using environment 'director.example.com' as client 'boss'

Attempting to cancel task task-id:

Connected to task-id

Task output 0
Task output 1
Task output 2
  L Error: Task task-id cancelled

Task task-id cancelled

Succeeded
```

-Derek

**Comment by mfine30** [comment]
Thanks @drich10. This isn't something that we're likely to get to in the near future. Could we convince you to submit a PR?
