### ISSUE TITLE
document blobstore options

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/bosh-cli#90]
We had to hunt down the the new blobstore configuration syntax. We found it in a [comment](https://github.com/cloudfoundry/bosh-cli/blob/master/releasedir/fs_config.go#L9-L22).

This should be documented somewhere since it is different from the old bosh-cli (Ruby).

/cc: @jtarchie

**Comment by dpb587-pivotal** [comment]
Moved to https://github.com/cloudfoundry/docs-bosh/issues/576
