### ISSUE TITLE
Request retry failure

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry/bosh-cli#94]
We were uploading a BOSH release and got this error message:
```
Uploading release file:
  Performing request POST 'https://192.168.124.128:25555/releases?':
    Performing POST request:
      Post https://192.168.124.128:25555/releases?: read /Users/pivotal/.bosh/tmp/bosh-platform-disk-TarballCompressor-CompressSpecificFilesInDir037061428: bad file descriptor
```

After some digging, we found out that the issue was with our authentication token getting expired too quickly.

However, the error was too cryptic. It seems that the AdjustableClient retries the request if the response error code was 401. https://github.com/cloudfoundry/bosh-cli/blob/475d68ac4a964d383c86e21448773016e1ed061a/director/adjustable_client.go#L42-L49 

But the repeated request contains a file descriptor which can not be used after the first request is finished.

It would be nice to have more descriptive error and update the retry mechanism to detect if a file handle is used in the request.

**Comment by naruraghavan** [comment]
I have a similar problem. Is there a work around available?

**Comment by alex-slynko** [comment]
@naruraghavan Check that you logged in to given BOSH environment. I.e. run `bosh  releases`.

**Comment by mfine30** [comment]
Closing and re-opening to trigger a github story

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
